### PR TITLE
Add a method to clear CM_Janus_ConnectionDescription js instance

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
type 0 is kinda strange, lgtm otherwise

**Comment by zazabe** [comment]
Is it better?

**Comment by tomaszdurka** [comment]
Yeah, better. Still not 100% sure about the clearing, you talked it over with @njam too?

**Comment by zazabe** [comment]
Maybe http://backbonejs.org/#Model-clear could be used instead...

**Comment by tomaszdurka** [comment]
Indeed this looks much better!

**Comment by zazabe** [comment]
I think we should keep those PR changes, because if we use the native `clear`, all getters (like `getIceServerList`) will return `null`...

**Comment by tomaszdurka** [comment]
I would say it's not bad. You mean that it should return empty array? I actually think empty array can be also a valid value. Null is clearly different than empty array.

**Comment by tomaszdurka** [comment]
On the other side we should probably do not run getters on empty models. That's why I am not sure if clearing model is enough. Isn't this that there is no (e.g.) server for this ConnectionDescription and it should be null? Rather then nulling properties of the server?

**Comment by zazabe** [comment]
Finally, I don't need to do this `clear` at all. I thought I would need to keep those instances persistent but actually not... :)

**Comment by tomaszdurka** [comment]
Hooray!

**Pull request closed without merging**
