### PR TITLE
Introduce a flag 'avoidPasswordManager' for forms.

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@fauvel please review.

**Comment by njam** [comment]
- CM/Form/Abstract.php: Add var-docu for `$_avoidPasswordManager`
- CM/Form/Abstract.php::isAvoidPasswordManager: Rename to `getX` (methods [should begin with verb](https://github.com/cargomedia/guides/tree/master/style#naming))
- CM/Form/Abstract.php::getAvoidPasswordManager: Add type casting
- block.form.php: Add the html with two concatenations, so we don't have unnecessary whitespace in the output?
- block.form.php: Don't add `/` when closing tag (just `<input>`)

**Comment by vogdb** [comment]
@njam please review.

**Comment by njam** [comment]
- Add type-casting to setter, but not getter
- block.form.php: Apply formatting - How about writing this in two lines?
```php
            $html .= '<input style="display:none" type="text" name="fakeusernameremembered">';
            $html .= '<input style="display:none" type="password" name="fakepasswordremembered">';
```

**Comment by vogdb** [comment]
Yes! @njam please review.

**Comment by njam** [comment]
Will these two fields affect `CM_Form_Abstract.getData()` (that's sent to the server)?
If yes, could we make them `disabled`?

**Comment by vogdb** [comment]
> Will these two fields affect CM_Form_Abstract.getData() (that's sent to the server)?

No because they are not registered in the form. Should I make them disabled on a fire case?

**Comment by njam** [comment]
> No because they are not registered in the form.

True

> Should I make them disabled on a fire case?

Can we make them disabled from the start? Or does it prevent the workaround to work?

**Comment by vogdb** [comment]
> Can we make them disabled from the start? Or does it prevent the workaround to work?

It prevents the workaround to work =(

**Comment by njam** [comment]
Ok - lgtm!

**Pull request merged**
