### PR TITLE
Update icons

### PR DESCRIPTION
**Pull request by christopheschwyzer**

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@njam maybe you want to review my second commit (Cli change)

**Comment by njam** [comment]
Code change of f5ef55e7c5903ea8bb86d411620226b93e527133 looks good.
I understand this will remove *any* horizontal whitespace? So it's not possible anymore to have an icon that doesn't use the full width? -> We don't have any such icons so it's okay!

**Comment by christopheschwyzer** [comment]
Yes. I think that's ok.

**Comment by christopheschwyzer** [comment]
I will go on and merge this

**Pull request merged**
