### PR TITLE
Rebuild test to ignore forks' terminations order

### LINKED ISSUE #1285: CM_ProcessTest::testForkAndWaitForChildren fails
I got this failure a few times already.

```
1) CM_ProcessTest::testForkAndWaitForChildren
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 Child 1 terminated after 100 ms.
-Child 2 terminated after 200 ms.
-Parent listening to children...
-Child 3 terminated after 300 ms.
 Child 4 terminated after 400 ms.
 All children terminated.
 Parent terminated.
```
https://travis-ci.org/cargomedia/CM/jobs/27387842

```
1) CM_ProcessTest::testForkAndListenForChildren
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 Parent stops listening to children...
-Child 3 heard by parent...
 Parent waiting for 100 ms...
 Child 4 terminated after 375 ms.
 Parent listening for children...
 Parent stops listening to children...
-Child 4 heard by parent...
+Child 3 heard by parent...
 Parent waiting for 100 ms...
 Parent listening for children...
 Parent stops listening to children...
+Child 4 heard by parent...
 Parent terminated.
 ```
https://travis-ci.org/cargomedia/CM/jobs/57613849

```
1) CM_ProcessTest::testForkAndListenForChildren
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 Parent stops listening to children...
-Child 3 heard by parent...
 Parent waiting for 100 ms...
 Child 4 terminated after 375 ms.
 Parent listening for children...
 Parent stops listening to children...
+Child 3 heard by parent...
 Child 4 heard by parent...
 Parent waiting for 100 ms...
 Parent listening for children...
 Parent stops listening to children...
 Parent terminated.
```
https://travis-ci.org/cargomedia/CM/jobs/57445603

```
1) CM_ProcessTest::testForkAndListenForChildren
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 Child 2 terminated after 175 ms.
+Child 3 terminated after 275 ms.
 Parent listening for children...
 Parent stops listening to children...
 Child 1 heard by parent...
 Child 2 heard by parent...
 Parent waiting for 100 ms...
-Child 3 terminated after 275 ms.
@@ @@
 Parent stops listening to children...
-Child 4 heard by parent...
 Parent waiting for 100 ms...
 Parent listening for children...
 Parent stops listening to children...
+Child 4 heard by parent...
 Parent terminated.
```
https://travis-ci.org/cargomedia/CM/jobs/57032254

```
1) CM_ProcessTest::testForkAndListenForChildren
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 Parent stops listening to children...
-Child 3 heard by parent...
 Parent waiting for 100 ms...
 Child 4 terminated after 375 ms.
 Parent listening for children...
 Parent stops listening to children...
-Child 4 heard by parent...
+Child 3 heard by parent...
 Parent waiting for 100 ms...
 Parent listening for children...
 Parent stops listening to children...
+Child 4 heard by parent...
 Parent terminated.
```
https://travis-ci.org/cargomedia/CM/jobs/57027415

### PR DESCRIPTION
**Pull request by fvovan**
Fixes #1285

### CODE REVIEW

**Comment by njam** [comment]
@tomaszdurka can you explain those changes?

**Comment by njam** [comment]
@tomaszdurka lgtm, could you also adjust `testForkAndListenForChildren`?

**Comment by tomaszdurka** [comment]
I will merge this as I would need to be Vlad's collaborator in order to push here.
Will do another issue.

**Comment by njam** [comment]
One more thing, what is the `usleep(self::FORKING_DELAY);` about?

**Comment by tomaszdurka** [comment]
Long story, will talk it over with you.

**Pull request merged**
