### PR TITLE
Adjust CMTest_TH::createStreamChannelVideoArchive()

### PR DESCRIPTION
**Pull request by fvovan**

### CODE REVIEW

**Comment by fvovan** [comment]
@tomaszdurka  please review

**Comment by njam** [comment]
@tomaszdurka @fvovan status?

**Comment by fvovan** [comment]
Ah. sorry. It is awaiting for review but I should remind about it. For some reason I checked only currently assigned issues, but not PR's. Will keep eyes on it as well

**Comment by tomaszdurka** [comment]
Looks good! :)

**Pull request merged**
