### PR TITLE
Configure bluebird Promise before loading anything else

### PR DESCRIPTION
**Pull request by zazabe**
When a bluebird promise has already been created, the bluebird promise configuration fails:

It seems to happen only with Firefox:
screen shot 2016-04-05 at 18 10 21

Note that promise cancellation is not usable at all after that:
screen shot 2016-04-05 at 18 12 43

### CODE REVIEW

**Comment by zazabe** [comment]
@vogdb please review

**Comment by vogdb** [comment]
Have you checked that
```js
Promise.config({
  cancellation: true
});
```
is not overwritten by the late call
```js
var promiseConfig = {};
//....
Promise.config(promiseConfig);
```
?

**Comment by zazabe** [comment]
Yes https://github.com/petkaantonov/bluebird/blob/v3.1.5/src/debuggability.js#L164

**Comment by vogdb** [comment]
lgtm them

**Pull request merged**
