### PR TITLE
Move functionality of CM_Paging_List to CM_Paging_Abstract

### PR DESCRIPTION
**Pull request by zazabe**
Keep only `_construct` of back-end in CM_Paging_List. All the rest should go to CM_Paging_Abstract.
The usecase is to create sync-able SK_Paging_MailboxConversation_Abstract front-end counterpart.

@zazabe please add your thoughts

### CODE REVIEW

**Comment by zazabe** [comment]
It works, but all Paging that will go through `CM_Params:encode()` will be exposed like that: `{"_class":"", "items": "<$paging->getItems()>"}`, so the payload could be pretty heavy, wdyt @vogdb @tomaszdurka @njam ?

**Comment by vogdb** [comment]
- Can we exclude items by default?
 - Shall we implement the Paging API for those lists?

**Comment by zazabe** [comment]
> Can we exclude items by default?

we could, be it means that each paging that need a JS representation will have to override this `jsonSerialize` method, with the same code i guess...

> Shall we implement the Paging API for those lists?

pagination on the client side? mmmh... it's not needed right now but i would let you implement that in a new PR :D!

**Comment by zazabe** [comment]
as discussed with @njam, it's preferable to explicitly define `jsonSerializable()` for each `Paging` that we want to expose as a collection on the client side. 

@vogdb please review

**Comment by vogdb** [comment]
well, looks fine

**Pull request merged**
