### PR TITLE
Upgrade MaxMind geolocation database weekly

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by fauvel** [comment]
@njam please review

**Comment by njam** [comment]
- weeklyUpgrade: How about rather a function `downloadGeoIpFile()` (maybe there's a better name), which just returns the file. Then instantiate the `CMService_MaxMind` instance in the maintenance task, to avoid passing along the streams..
- weeklyUpgrade: To build URL use `CM_Util::link()`?

**Comment by fauvel** [comment]
I've been looking for a `CM_Util::url()` or something, I've missed the `link()`... Thank you! :)
We would be passing the streams to the constructor of `CMService_MaxMind` anyway, so there's no real point in removing `weeklyUpgrade()`.

**Comment by njam** [comment]
I meant to inline `weeklyUpgrade` in `CM/Maintenance/Cli.php`, this way we don't need to pass the streams to the static function, plus we get rid of the static function?

**Comment by fauvel** [comment]
But we would pass the streams to the constructor in `CM/Maintenance/Cli.php` anyway if we instantiate it there directly, so what is the upside? Encapsulating the whole job's logic in a method of `CMService_MaxMind` is not bad imo, plus it is compatible with our naming convention for background jobs.

**Comment by fauvel** [comment]
We would end up with something like that:
```php
$this->_registerClockworkCallbacks('1 week', array(
    'CMService_MaxMind::upgrade' => function () {
        $geoIpFile = CMService_MaxMind::downloadGeoIPFile();
        $maxMind = new CMService_MaxMind($geoIpFile, $this->_getStreamOutput(), $this->_getStreamError());
        $maxMind->upgrade();
    }
));
```

**Comment by fauvel** [comment]
@njam please review

**Comment by njam** [comment]
- _downloadGeoIpFile: Use `null` as default for `licenceKey` (instead empty string)?
- Streamline tmp FS usage (sometimes using `getDirTmp()` sometimes `getTmp()`). Maybe introduce a function `_getTempFile($name)`?

**Comment by njam** [comment]
- _getFileTmp: Docu

Rest looks good

**Comment by fauvel** [comment]
@njam I've tried to improve the memory usage of this script. Please review!

**Comment by njam** [comment]
Did you try this with actual data, do you have numbers on memory usage?

**Comment by fauvel** [comment]
I've tested it thoroughly in dev with the latest GeoIP database. The script is not broken :) And it ran through without swapping too much on my dev box with only 4GB RAM. I've added some memory usage output between method calls with:
```php
print 'Memory usage: ' . memory_get_usage(true) . ' (peak: ' . memory_get_peak_usage(true) . ")\n";
```
Now we have a peak of "only" 6.6GB as the IP blocks are being updated, and memory is being released as early as possible:
```
Updating locations database…
Memory usage: 3145728 (peak: 3145728)
Reading old country listing…
Memory usage: 3145728 (peak: 3145728)
Downloading new country listing…
Reading new country listing…
Memory usage: 3670016 (peak: 3670016)
Comparing both country listings…
Memory usage: 3670016 (peak: 3670016)
Reading old region listing…
Memory usage: 4980736 (peak: 4980736)
Downloading new region listing…
Reading new region listing…
Memory usage: 7077888 (peak: 9175040)
Reading old location tree…
Memory usage: 884736000 (peak: 884736000)
Reading new location tree…
Downloading GeoIP database…
647440/647440 (100%)
Memory usage: 2575302656 (peak: 2958819328)
Comparing both region listings…
Memory usage: 2575302656 (peak: 2958819328)
Comparing both location trees…
Memory usage: 2579759104 (peak: 2958819328)
Updating countries database…
Memory usage: 2579759104 (peak: 2958819328)
Updating regions database…
Memory usage: 2579759104 (peak: 2958819328)
Updating cities database…
Memory usage: 1924399104 (peak: 2958819328)
Updating zip codes database…
Memory usage: 1924399104 (peak: 2958819328)
Reading new IP blocks…
5636269/5636269 (100%)
Checking overlapping of IP blocks…
5636269/5636269 (100%)
Updating IP blocks database…
5188090/5188090 (100%)
Memory usage: 713555968 (peak: 6574309376)
Memory usage: 713555968 (peak: 6574309376)
Creating elasticsearch index `location`…
Memory usage: 687079424 (peak: 6574309376)
```
So I think it should be ok in prod!

**Comment by njam** [comment]
It's still a lot, and I would not run it on www3 with this memory usage. (We had some nasty memory shortages there in the past. Especially if this runs unattended I think it's too risky.)
6.6G is a lot - maybe we look through the critical code path together to check whether this memory is really needed?

**Comment by njam** [comment]
Ideas:

Read CSV line by line:
- `$stream = fopen('php://temp','r+'); fwrite($stream, $contents); rewind($stream); fgets($stream)`
- IP blocks:
 - Write to "tmp" table, then [swap](http://dba.stackexchange.com/questions/22108/how-do-i-swap-tables-in-mysql)
 - Check overlaps in mysql?

should get memory usage to 1.8G?

**Comment by fauvel** [comment]
@njam we're down to 1.6 GB:
```
Updating locations database…
Memory usage: 3145728 (peak: 3145728)
Reading old country listing…
Memory usage: 3145728 (peak: 3145728)
Downloading new country listing…
Reading new country listing…
Memory usage: 3670016 (peak: 3670016)
Comparing both country listings…
Memory usage: 3670016 (peak: 3670016)
Reading old region listing…
Memory usage: 4980736 (peak: 4980736)
Downloading new region listing…
Reading new region listing…
Memory usage: 7077888 (peak: 9175040)
Reading old location tree…
364359/364359 (100%)
297185/297185 (100%)
Memory usage: 704643072 (peak: 704643072)
Reading new location tree…
Downloading GeoIP database…
647443/647443 (100%)
Memory usage: 1576271872 (peak: 1576271872)
Comparing both region listings…
Memory usage: 1576271872 (peak: 1576271872)
Comparing both location trees…
Memory usage: 1609564160 (peak: 1611923456)
Updating countries database…
Memory usage: 1609564160 (peak: 1611923456)
Updating regions database…
Memory usage: 1609564160 (peak: 1611923456)
Updating cities database…
Memory usage: 1020788736 (peak: 1611923456)
Updating zip codes database…
Memory usage: 1020788736 (peak: 1611923456)
Reading new IP blocks…
Memory usage: 1020788736 (peak: 1611923456)
5636271/5636271 (100%)
Memory usage: 905445376 (peak: 1611923456)
Checking overlapping of IP blocks…
5188090/5188090 (100%)
Memory usage: 561512448 (peak: 1611923456)
Memory usage: 561250304 (peak: 1611923456)
Creating elasticsearch index `location`…
Memory usage: 423100416 (peak: 1611923456)
```
Would you say it is production ready now?

Please review the last changes:
- Used buffer to extract IP geolocation files
- Used temporary file stream to extract them and read them line by line
- Used temporary table for the import of the new IP blocks
- Imported IP blocks in batches of 1000
- Used SQL query to look for overlapping IP blocks
- Added progress counters
- Throttled progress counter (1 update per second)
- Removed unused latitude/longitude from old location data
- Removed alphabetical sorting of added/removed locations
- Adjusted tests (IP blocks ordering, location ordering, condensed arrays)

**Comment by fauvel** [comment]
@njam wdyt of the [last commit](https://github.com/cargomedia/CM/commit/07d4c7decd951974ab6f68d56f2695e205c6b910) (I'm duplicating some code here to download to a file with curl)? I'm saving a few hundreds of MB of peak memory usage this way.

**Comment by fauvel** [comment]
@njam please review. I think I've optimized everything I could.

Side note: Is it any good to write to `stdout` in the context of a background job? And is it safe to write to `stderr`? Otherwise I could just redirect all output to `CM_OutputStream_Null`.

**Comment by njam** [comment]
>  Is it any good to write to stdout in the context of a background job? 

In the background jobs STDOUT and STDERR will get ignored, they're not logged anywhere.

>  I'm duplicating some code here to download to a file with curl

What's the optimization? Could we use Guzzle to abstract it?

**Comment by fauvel** [comment]
> In the background jobs STDOUT and STDERR will get ignored, they're not logged anywhere.

Should I use `CM_OutputStream_Null`, then?

> What's the optimization? Could we use Guzzle to abstract it?

The downloaded file is being written to disk directly, and not placed in memory as a php string any more. We're not using this string anyway, since we're reading downloaded files line by line. We're saving hundreds of MB of transient memory usage this way, and 50 MB of peak memory usage. Maybe we could use Guzzle, I'm looking into it.

The peak memory usage is down to 1.56 GB currently:
```
/Users/cargomedia/Projects/sk/.idea/vagrant/php /Users/cargomedia/Projects/sk/scripts/test.php
Starting upgrade...
Updating locations database…
Memory usage: 3145728 (peak: 3145728)
Reading old country listing…
Memory usage: 3145728 (peak: 3145728)
Downloading new country listing…
Download completed.
Reading new country listing…
Memory usage: 3670016 (peak: 3670016)
Comparing both country listings…
Memory usage: 3670016 (peak: 3670016)
Reading old region listing…
Memory usage: 4980736 (peak: 4980736)
Downloading new region listing…
Download completed.
Reading new region listing…
Memory usage: 6815744 (peak: 9175040)
Reading old location tree (cities)…
364665/364665 (100%)
Reading old location tree (zip codes)…
299994/299994 (100%)
Memory usage: 707002368 (peak: 707002368)
Reading new location tree…
Downloading GeoIP database…
Download completed.
651344/651344 (100%)
Memory usage: 1524891648 (peak: 1524891648)
Comparing both region listings…
Memory usage: 1524891648 (peak: 1524891648)
Comparing both location trees…
250/250 (100%)
Memory usage: 1558708224 (peak: 1560805376)
Updating countries database…
Memory usage: 1558708224 (peak: 1560805376)
Updating regions database…
Memory usage: 1558708224 (peak: 1560805376)
Updating cities database…
Memory usage: 962330624 (peak: 1560805376)
Updating zip codes database…
Memory usage: 962330624 (peak: 1560805376)
Updating IP blocks database…
Memory usage: 962330624 (peak: 1560805376)
5708623/5708623 (100%)
Memory usage: 844627968 (peak: 1560805376)
Checking overlapping of IP blocks…
5254350/5254350 (100%)
Memory usage: 490995712 (peak: 1560805376)
Memory usage: 490995712 (peak: 1560805376)
Creating elasticsearch index `location`…
```

**Comment by njam** [comment]
> Should I use CM_OutputStream_Null, then?

sorry .. didn't look at the code yet, yes I think `CM_OutputStream_Null` will be better

**Comment by njam** [comment]
It might be good to have a way to ensure we'll notice errors here.

We solved a similar problem (logging payment errors) by introducing `SK_Paging_Log_CheckoutError` which *only* contains these errors, and we check it regularly and look at every error.
We have the exception severity `FATAL` which is currently not really used. How about introducing a special log for it, and logging both "payment" errors and "location upgrade" errors to it?

**Comment by njam** [comment]
It's *a lot* of code!
I think it's okay (and coverage is good).
- Use Guzzle?
- Error handling (`FATAL` log?)
- CMService_MaxMindTest is quite slow (40secs here). Do you see some quick ways of improving it? What takes time?

**Comment by fauvel** [comment]
I'm not sure how to increase the speed of the unit tests... It looks like they all take the same time to run, about 0.6s each:
```
0.84202289581299s for testEmpty
0.44734191894531s for testCountry
0.4281120300293s  for testCountry_withoutLocation
0.42618703842163s for testCountry_unknown
0.450679063797s   for testRegion
0.44564700126648s for testRegion_withoutLocation
1.140811920166s   for testRegion_unknown
0.43296003341675s for testRegion_legacy
0.70626401901245s for testRegion_keepMissing
0.41507887840271s for testRegion_addLegacy
0.47257089614868s for testRegion_countryWithoutLocation
0.73687100410461s for testCity
0.42106986045837s for testCity_withoutRegion
0.4673159122467s  for testCity_unknownRegion
0.41287684440613s for testCity_legacyRegion
0.47756290435791s for testZipCode
0.84064984321594s for testZipCode_unknownRegion
0.63815402984619s for testZipCode_legacyRegion
0.55940699577332s for testZipCode_withoutCity
0.41702795028687s for testIpBlockCountry
0.42608904838562s for testIpBlockCity
0.51438689231873s for testImport
0.57258296012878s for testAddCountry
0.59515714645386s for testRemoveCountry
0.56543803215027s for testUpdateCountryName
0.62100386619568s for testAddRegion
0.56742215156555s for testAddRegion_duplicate
0.57329893112183s for testRemoveRegion
0.67757201194763s for testRemoveRegion_codeInUse
0.57742094993591s for testUpdateRegionCode
0.54374814033508s for testUpdateRegionName
0.56049394607544s for testUpdateRegion_numericMaxMindCodeUS
0.59714794158936s for testUpdateRegionName_numericMaxMindCodeUS
0.99788308143616s for testAddCity
0.68267583847046s for testRemoveCity
0.58459115028381s for testUpdateCityCode
0.57204985618591s for testUpdateCityCode_circular
0.60534596443176s for testUpdateCityCode_swapAcrossRegions
0.58724212646484s for testUpdateCityCode_unsetRegion
0.54882216453552s for testUpdateCityCode_deletedRegion
0.53809595108032s for testUpdateCityName
0.56312203407288s for testUpdateCityName_deletedRegion
0.66726183891296s for testUpdateCityRegion
0.65069508552551s for testUpdateCityRegion_set
0.54657816886902s for testUpdateCityRegion_unset
0.61729502677917s for testUpdateCityRegion_newRegion
0.64255785942078s for testUpdateCityRegion_deletedRegion
0.61445903778076s for testUpdateCityRegion_regionUpdatedCode
0.64274907112122s for testUpdateCityRegion_oldRegionUpdatedCode
0.70320105552673s for testUpdateCityRegion_regionsUpdatedCode
0.87204790115356s for testUpdateCityRegion_regionsSwappedCode
0.69227290153503s for testUpdateCityRegion_replaceDuplicateCity
0.59151482582092s for testUpdateCityRegion_replaceDuplicateCityInUnknownRegion
0.6407778263092s  for testUpdateCityRegion_replaceDuplicateCityFromUnknownRegion
0.55483078956604s for testUpdateCityRegion_duplicateRegion
0.73760604858398s for testAddZipCode
0.73270797729492s for testRemoveZipCode
0.45684099197388s for testOverlappingIpBlocks_noOverlapping
0.39558887481689s for testOverlappingIpBlocks_sameIpStart
0.50092005729675s for testOverlappingIpBlocks_inclusion
0.40526795387268s for testOverlappingIpBlocks_overlapping
0.09008002281189s for testExceptionAddRegionInUnknownCountry
0.43985199928284s for testExceptionUpdateRegionCodeInUnknownCountry
0.42036104202271s for testExceptionUpdateRegionNameInUnknownCountry
0.42231702804565s for testNormalizeCountryName
0.40542817115784s for testNormalizeRegionName
0.4141731262207s  for testNormalizeCityName
```

**Comment by fauvel** [comment]
Here the XDebug profiling results for `CMService_MaxMindTest`:

image

**Comment by fauvel** [comment]
Visualization with [qcachegrind](http://blog.jcmultimedia.com.au/2014/03/profiling-php-on-osx-with-xdebug-kcachegrind/) (`brew install qcachegrind && brew install graphviz`):

image

image

So it looks like recreating the Elastic search index is what consumes the most.

**Comment by fauvel** [comment]
Down to 12s without search index. Thank you XDebug!

**Comment by fauvel** [comment]
@njam please review. Is it the right place to log exceptions? Or rather in `CMService_MaxMind` (which would include command line calls)?

**Comment by njam** [comment]
lvgtm!

**Comment by njam** [comment]
Maybe do log adjustments here - see https://github.com/cargomedia/sk/pull/1299

- CM_Paging_Log_Fatal: Set deletion of old entries to 30 days here - it can be useful to keep these longer
- Rethrow exceptions in cron and make them fatal

**Comment by fauvel** [comment]
@njam is this what you meant?

**Comment by njam** [comment]
looks good, restarted build

**Comment by njam** [comment]
lgtm!

**Comment by fauvel** [comment]
Tagged 1.102.2

**Pull request merged**
