### PR TITLE
Reset offlineStamp if set on all requests

### PR DESCRIPTION
**Pull request by alexispeter**

### CODE REVIEW

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
- setOfflineStamp: Docu
- getOfflineStamp: Instead of returning early, just int-cast only in an `if`?
- CM_Session::start: Let's use type-safe comparison in `if`
- Test new functionality in `CM_SessionTest`
- Test fails: CM_Model_UserTest::testOfflineDelayed

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
lgtm

**Comment by alexispeter** [comment]
tagged https://github.com/cargomedia/cm/releases/tag/1.145.0

**Pull request merged**
