### PR TITLE
Refactor @colorFgTheme usages

### PR DESCRIPTION
**Pull request by christopheschwyzer**

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@vogdb please review

**Comment by vogdb** [comment]
Hi! Do we completely wipe out its usages? There are still exist these two:
screen shot 2015-03-13 at 10 13 01

**Comment by christopheschwyzer** [comment]
No, we still use it. (See description in SK)

**Comment by christopheschwyzer** [comment]
Wait. Will remove it! ;)

**Comment by vogdb** [comment]
lgtm!

**Pull request merged**
