### PR TITLE
Adjust navigation to page anchors.

### PR DESCRIPTION
**Pull request by vogdb**
The problem comes when page has a position fixed header. The action `anchor.scrollIntoView();` does not count in the header and the anchor line gets hidden under the header.

The fix would be just to scroll up on the volume of the header's height. Will be this artificial solution inside CM acceptable to us? I'm asking because it is dictated by the integration of CM rather than the CM itself.

@njam @fauvel please share your thoughts.

### CODE REVIEW

**Comment by vogdb** [comment]
@njam @fauvel please look.

**Comment by njam** [comment]
Hmm now we're scrolling twice - doesn't the second scoll override the first one?

**Comment by vogdb** [comment]
No, it complements the first one.

**Comment by vogdb** [comment]
@njam please look the second variant.

**Comment by njam** [comment]
Now it might really make sense to use jQuery for finding that element? :)

**Comment by vogdb** [comment]
Indeed! @njam please look.

**Comment by fauvel** [comment]
Lgtm :P

**Comment by njam** [comment]
lgtm

**Pull request merged**
