### PR TITLE
Fix for circle clickFeedback

### PR DESCRIPTION
**Pull request by christopheschwyzer**
Follow up: https://github.com/cargomedia/CM/pull/1815
Fixes Safari issue. See https://gist.github.com/adamcbrewer/5859738

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@vogdb please review

**Comment by christopheschwyzer** [comment]
@vogdb now ;)

**Comment by vogdb** [comment]
lgtm. btw where are the usages of it? Didn't we have the places where we did the same circling manually?

**Comment by christopheschwyzer** [comment]
Fix works for IOS Safari, now it breaks in Chrome. Need to investigate!

**Pull request merged**
