### PR TITLE
Don't fully decode parameters when queueing delayed jobs

### PR DESCRIPTION
**Pull request by alexispeter**
fixes https://github.com/cargomedia/sk/issues/4547

Instead of fully decoding and thereby implicitly instantiating ArrayConvertibles, they should just be jsonDecoded and passed to the job in their array-form.
Exceptions will be thrown at job-execution inside the worker as it is with non-delayed jobs.

### CODE REVIEW

**Comment by njam** [comment]
I'm not sure if this is a good idea.
Currently `Job::queue($params)` will always be passed an array of *decoded* parameters, of key-value pairs. This changeset changes that - the function will have to accept also *encoded* parameters in the future.
This works I guess because `Params::encode()` which is used in `queue()` is idempotent.
Isn't it a bit risky? Or should at least be documented for `queue()`?
Alternatively how about decoding it, but handling exceptions more gracefully?

**Comment by njam** [comment]
As discussed: let's pass `CM_Params` instead of `array` to queue() - so it can be encoded or decoded.

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
To keep it simple, let's try/catch the decoding of the params in `queueOutstanding()`, and log a warning if it fails, but continue otherwise.

**Comment by alexispeter** [comment]
Closed in favour of #2581

**Pull request closed without merging**
