### PR TITLE
CM_Jobdistribution_Cli: restart process after X job runs

### PR DESCRIPTION
**Pull request by tomaszdurka**
Goal: restart job worker processes once in a while to avoid filling up memory. Like apache (or php-fpm) we could just exit a job worker after X job runs. The CLI manager would then restart the worker.

Default: 1000

screen shot 2016-11-14 at 10 38 17

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@alexispeter or @njam please review

**Comment by alexispeter** [comment]
lgtm

**Comment by njam** [comment]
lgtm

**Comment by njam** [comment]
This will result in warnings "Respawning dead child." correct?
@tomaszdurka what do you think? Should we avoid it somehow?

**Comment by njam** [comment]
Let's use `$workloadResult->isSuccess())` to decide whether to log a *warning* or an *info*.

**Comment by njam** [comment]
I can't push to your branch.
Can you merge in this commit and release it? https://github.com/njam/CM/commit/7e476976c2bc87595b2c5a697439c603ba1714dc

**Comment by tomaszdurka** [comment]
lgtm

**Pull request merged**
