### PR TITLE
Small Request and Site improvements

### PR DESCRIPTION
**Pull request by njam**
@tomaszdurka could you review?

### CODE REVIEW

**Comment by njam** [comment]
@fauvel could you review?

**Comment by tomaszdurka** [comment]
Looks good. Rerun failing test

**Comment by fauvel** [comment]
Make sense, what are the use case you have in mind?

**Comment by tomaszdurka** [comment]
What is the name of pull-request of adding User to Request? (this commit: https://github.com/njam/CM/commit/e2a60392c2fb410c0dba49ed24ad2b6c55a04104)
Can't find it.

I was actually a bit against that. Session is something better to be stored on a request and User can be part of session instead. Wdyt?

**Comment by njam** [comment]
@tomaszdurka agree, Viewer and Session are conflicting concepts on the Request. I tried to remove Viewer in this PR, but it couldn't be done easily so I reverted it.
For now everything stays the same: Viewer has precedence.

**Comment by njam** [comment]
@fauvel uses cases for `setSession()` is the cross-site redirect, will show you!

**Pull request merged**
