### PR TITLE
'Undefined index' in CM_Paging_ModelAbstract

### PR DESCRIPTION
**Pull request by fvovan**
There are still some problems  with model paging 

ErrorException: E_NOTICE: Undefined index: a:2:{s:2:"id";s:7:"5927208";s:4:"type";s:1:"1";} in /home/{appDir}/vendor/cargomedia/cm/library/CM/Paging/ModelAbstract.php on line 41

https://github.com/cargomedia/cm/pull/2295
https://github.com/cargomedia/cm/pull/2279

### CODE REVIEW

**Comment by fvovan** [comment]
@njam please review

**Comment by njam** [comment]
Now $model will be undefined?
Also I think we *never* want to throw now, correct?
So rather `$model = isset($foo['bar']) ? $foo['bar'] : null;`?

**Comment by fvovan** [comment]
We need to throw here.
This exception is awaited in child paging.

**Comment by njam** [comment]
You mean `SK_Paging_Entity_Pinboard`? Doesn't this work equally well with `null`?:
```php
    protected function _processItem($item) {
        $entity = null;
        try {
            $entity = parent::_processItem($item);
        } catch (CM_Exception_Nonexistent $e) {
            $entity = null;
        }
```

**Comment by njam** [comment]
As discussed returning `null` is fine here.

**Comment by fvovan** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
