### PR TITLE
Ajax/Promise "throttler" to avoid multiple requests

### PR DESCRIPTION
**Pull request by vogdb**
We often times want to avoid multiple concurrent ajax requests of the same time.

Usually we do:
```js
var requestList = {};

/**
 * @returns Promise
 */
function doSomething()  {
 if (requestList['something']) {
  return requestList['something'];
 }
 return requestList['something'] = ajax();
}
```

It would be nice to wrap this into a small script, so we don't need to declare `requestList` every time, plus have a nicer interface. Preferably it would would work as kind of like a "Promise throttling":
```js
/**
 * @returns Promise
 */
function doSomething() {
 return promiseThrottler('something', function() {
  return ajax(); // returns Promise
 });
}
```

@vogdb @tomaszdurka thoughts?
Related to https://github.com/cargomedia/CM/issues/1754

### CODE REVIEW

**Comment by vogdb** [comment]
@njam @tomaszdurka please look.

**Comment by njam** [comment]
Simple enough! Add some docu to the function?

**Comment by vogdb** [comment]
Yes!

**Comment by tomaszdurka** [comment]
Looks good, what about making it not self-executed. Then store instance of it somehwere in cm app instance? It's probably the same in the end.

**Comment by njam** [comment]
Use amd.js? :P

**Comment by vogdb** [comment]
If you store it in cm app then you will not be able to access it from a global scope. Is it ok or should it be available from both global and cm app?

**Comment by tomaszdurka** [comment]
I am generally against global state which we have plenty with jquery plugins etc. I would rather make library witout self-execution code and create instance of it somwhere, it can be global too...

**Comment by njam** [comment]
But then it's a CM plugin, right? Or how would you access it without having a reference on the global context to it?

**Comment by vogdb** [comment]
So, what is the resolution of this discussion ?

**Comment by tomaszdurka** [comment]
Just against global state. I thought that `PromiseThrottler` would be a class defined within same file you've created. It would create this class in global context. We could then create instance of this class in global or cm context.

Maybe it's overkill as cm app is a global singleton anyway.

**Comment by tomaszdurka** [comment]
If I did not convince any of you guys, let stay with current solution.

**Comment by njam** [comment]
Hm, so you would suggest?:
```js
var ThrottlerClass = window.ThrottlerClass;
var throttler = new ThrottlerClass();
throttler.throttleFunction(promise);
```

I don't see the reason to have this class for this purpose, isn't this mainly a utility function? I would rather see:
```js
var throttler = window.throttler;
throttler.throttleFunction(promise);
```
or even (current):
```js
var throttleFunction = window.throttleFunction;
throttleFunction(promise);
```

wdyt?

**Comment by vogdb** [comment]
I like the latter one!

**Comment by tomaszdurka** [comment]
Ok I agree this will be the easier, kinda cleaner solution and that with not-auto-install implementation I am for reasons which we never gonna use. I just don't like that we have single global instance of something with state. Most probably there will be no use case for using multiple of these. Then I am ok with your implementation.

I guess somehting which would explain my point more is:
```js

// vendor file, doesn't influence global state
var extendWithThrottle = function(global) {
  global.throttle = function(name, promise) {
  }
};

// cm (ready?)
extendWithThrottle(window);
```

But as said, maybe it's my bad approach to those javascript vendors.

**Comment by njam** [comment]
True!

Maybe the function should store state only in itself? So like the underscore functions - return a new function that wraps the old one and is throttled?

**Comment by vogdb** [comment]
How can we store state only in itself? Consider this example http://jsbin.com/revajiribi/edit?html,js,output.

**Comment by njam** [comment]
You would need to use always the same returned function from 1 function call. Agree it's a bit inconvenient.. It works good if you use it like this:
```js
$('.foo').on('click', _.throttle(something());
```
It also has the advantage that you don't really need to care about the "key"/"id".

Would this pattern fit our use cases?

**Comment by vogdb** [comment]
I'm not sure what exactly are the use cases that we are trying to cover here.

**Comment by njam** [comment]
Anywhere where we're running AJAX requests, but want max. 1 request to be in-flight at a time. Usually we store the *current request* on the view instance.

But I can see now that in most of these use cases we usually `abort()` the previous request. I think it would be good to support both use cases:
- A: Cancel previous promise and immediately start new one
- B: Ignore new promise if old one is still "pending"

How could we support both use cases?

**Comment by vogdb** [comment]
Ok. I see. Both use cases can be supported by an additional param to the function or the second variation of promiseThrottler that cancels the previous request.

**Comment by vogdb** [comment]
Ok. The variant without cancellation http://jsfiddle.net/4hpzcpgz/. The variant with cancellation http://jsfiddle.net/ne41wyxb/1/. @njam wdyt ?

**Comment by njam** [comment]
I think it looks good.
Did you check our usages and how would could apply such a pattern there? (e.g. search for regexp `_.*request:` in files matching `*.js`)

**Comment by vogdb** [comment]
For some cases it can be difficult to apply. An example:
- CM_FormField_Suggest::ready
```js
      query: function(options) {
        if (this._request) {
          this._request.cancel();
        }
        this._request = field.ajax('getSuggestions', {'term': options.term, 'options': field.getOptions()})
          .then(function(results) {
            options.callback({
              results: results
            });
          });
      },
```
  You can see that every new promise is different from another because it is applied to a different `options.term`. So, for example I don't see an option to use a throttled promise of a term `Aus` for a term `Austra`. It is the situation where the existence of some constant key for those type of promises will solve the problem.

The above example is not the one. We have 4 of such places where we deal with requests to the same url but different arguments. As the result we have this problem. It can be solved but the solution is very very vulnerable:

Save the throttled promise outside of the callback listener and use the argument through a shared variable.
```js
var savedThrottledPromise = promiseThrottler(function(){
  return promise(shared.arg);
});
```

inside callback set the argument and call the throttled promise. Crazy!
```js
shared.arg = 5;
return savedThrottledPromise;
```

My suggestion is to have at least the second version of `promiseThrottler` where you can specify the corresponding key for the promise. The implementation that I've pushed here.

**Comment by njam** [comment]
Can't we just pass the arguments through the throttler (using `.apply()`)?
```js
    var query = promiseThrottler(function(options) {
      return field.ajax('getSuggestions', {'term': options.term, 'options': field.getOptions()})
        .then(function(results) {
          options.callback({
            results: results
          });
        });
    });
```

Should be useable like this:
```
query({term: "foo", options: {}});
```

Then pass it to the plugin:
```js
    this._$input.select2({
      [...]
      query: query,
```

**Comment by vogdb** [comment]
You are absolutely right. As always I couldn't see another option with `apply`. @njam @tomaszdurka how do you like the new version? I've pushed the updated CM_FormField_Suggest to show you the example.

**Comment by njam** [comment]
- promise-throttler.js: Remove `storage`
- promise-throttler.js: How about changing boolean `cancel` to object `options`. Possibly we can add things like `leading: false` and `trailing: true` (from underscore) - http://underscorejs.org/#throttle
- Suggest.js: Remove `_request` declaration

Rest looks very good

**Comment by njam** [comment]
How about defining those functions inline instead of in `ready()`?
E.g.:
```js
CM_View_Abstract.extend({
 _pageRequest: promiseThrottler(...)
});
```

**Comment by vogdb** [comment]
It can be done but would require to pass a link to the context as an argument to the function that we throttle.
For example now we have
```js
  var layout = this;
  this._pageRequest = promiseThrottler(function(path) {
    //...here we use layout
```
we can replace it with:
```js
  this._pageRequest = promiseThrottler(function(layout, path) {
    //...here we use layout
```

is it ok ?

**Comment by njam** [comment]
I see! Let's not do it then.
How about moving it to `initialize()` instead of `ready()`? Seems the better place - it's available directly after instantiation and not only once the "dom" is ready.

**Comment by vogdb** [comment]
ok

**Comment by vogdb** [comment]
Should all of the usages be in `initialize` or just `CM_Layout_Abstract` ?

**Comment by njam** [comment]
I think all usages when we set up "code" for the object. In `ready` I would only put things related to the DOM (events, DOM etc).

**Comment by njam** [comment]
- Layout/Abstract.js: _pageRequest: Rename to `_loadPageThrottled?
- Layout/Abstract.js: _pageRequest: Adjust docu

**Comment by njam** [comment]
lgtm

**Comment by tomaszdurka** [comment]
There is follow up in #1838

**Pull request merged**
