### PR TITLE
Update User-Agent Regexps

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@christopheschwyzer please review

**Comment by christopheschwyzer** [comment]
Not sure how to review this :) How can I test this?

**Comment by zazabe** [comment]
@christopheschwyzer hum, it's mainly about this Windows Edge detection issue so maybe double check if Edge is correctly detected :)

**Comment by njam** [comment]
@christopheschwyzer @zazabe could you finish this up?

**Comment by christopheschwyzer** [comment]
yes. Sorry. Will test it tomorrow in the office. Couldn't get the _IE Edge VB_ to work on my Mac.

**Comment by christopheschwyzer** [comment]
lgtm

**Pull request merged**
