### PR TITLE
Breaking: Allow to register multiple global handlers

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@vogdb please review

**Comment by vogdb** [comment]
looks good.

Off topic. Should we have a method to remove handler now when we can attach a multiple of them?

**Comment by zazabe** [comment]
Few improvements + add `cm.error.unregisterHandler`, please review @vogdb

**Comment by vogdb** [comment]
Why not use `reject` instead of `filter` with negation? I think you should delete this method at all. I just couldn't find any caveats in your blessed code but I so wanted to write something smart so I wrote about unregistering.

**Comment by zazabe** [comment]
I did it with love (for you?), so please, don't ask me to remove it now...

**Comment by vogdb** [comment]
petite lgtm ;-)

**Pull request merged**
