### PR TITLE
Breaking: Add tracking service for adagnit.io

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by fauvel** [comment]
@njam please review

**Comment by njam** [comment]
lgtm!
Did you test it in a browser, that the JS works well?

**Comment by njam** [comment]
Maybe `trackLogin()` and `trackSignUp()` can be called from `trackAction()` by looking at the action's attributes?

**Comment by njam** [comment]
Shouldn't we track `Site::getHost()` to be sure it's unique (some sites have the same name)?

Rest looks good!

**Comment by njam** [comment]
lgtm

**Comment by fauvel** [comment]
@njam please review (tests must be adjusted)

**Comment by fauvel** [comment]
@njam please review

**Comment by fauvel** [comment]
@njam please review

**Comment by fauvel** [comment]
@njam I've fixed a bug with virtual paths due to the fact that we reordered tracking and page rendering: Pages cannot overwrite the page path any more by calling `trackPageView()` explicitly in `prepareResponse()`, since this would be overwritten again in `_processPage()` now. I've opted for a getter to declare virtual paths on the page class.

**Comment by fauvel** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Comment by njam** [comment]
@fauvel moving all this logic out to a different class had some downsides. I now opted to just introduce a class to hold the result of processing (`ProcessingResult`).
Please have a look! What do you think?

**Comment by fauvel** [comment]
Perfect, it's a very nice trade-off between encapsulating the rendering logic and adding some more code complexity... I like it! The code looks good, too.

**Pull request merged**
