### PR TITLE
JS error handler improvements

### PR DESCRIPTION
**Pull request by zazabe**
- Recorder: _messageFormatter: Stringify objects in a space conserving way. Like just the "class name".
- CM_Http_Response_JsError: Throw warning if `$query['error']['message']` missing

### CODE REVIEW

**Comment by zazabe** [comment]
@vogdb please review

**Comment by vogdb** [comment]
lgtm, only one minor note
 - Do we need `console.log(recorder.getFormattedRecords());` in `recorderTest` ?

**Comment by zazabe** [comment]
oups, removed ;)

**Comment by zazabe** [comment]
sorry, one more small fix > a48bdb7, should be fine now!

**Comment by vogdb** [comment]
lgtm

**Pull request merged**
