### PR TITLE
Convert CM_Option into a service

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@dlondero please review

**Comment by dlondero** [comment]
If we name tables after the class name should `cm_option` become `cm_options`? Rest looks good.

**Comment by tomaszdurka** [comment]
We usually name as you said when describing models, but models refer to a single object. Here `CM_Options` refer to collection of options so I believe naming is fine. `CM_Options` could be maybe even a paging - `CM_Paging_Option_All`, but that would change logic behiing it a lot and be overkill atm imo.

**Comment by tomaszdurka** [comment]
I've readdd CM_Option class for backwards compatibility I think it would be nice to remove with new major realease only.

**Comment by tomaszdurka** [comment]
@dlondero wdyt?

**Comment by dlondero** [comment]
@tomaszdurka please merge upstream

**Comment by tomaszdurka** [comment]
Done.

**Comment by dlondero** [comment]
@tomaszdurka looks good

**Pull request merged**
