### PR TITLE
Add CM_Exception_Invalid to the front-end

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by fauvel** [comment]
@tomaszdurka please review

**Comment by njam** [comment]
Copying @fauvel
> We ran into a front-end error instead (Uncaught CM_Exception: No such exception CM_Exception_Invalid)

This comes from `CM_Exception.factory()` which is called from `CM_App.ajax()`:
```js
        if (response.error) {
          reject(new (CM_Exception.factory(response.error.type))(response.error.msg, response.error.isPublic));
        } else {
          resolve(response.success);
        }
```

Basically this means that any error that we "forward" to the client (as configured with  `exceptionsToCatch` in the config files) needs to be available on the client side as well? @vogdb can you confirm? How should we handle this? Create all JS files? Or use some automagic mechanism to create instances on the fly?

**Comment by vogdb** [comment]
> `exceptionsToCatch` in the config files) needs to be available on the client side as well? @vogdb can you confirm?

I confirm.

> How should we handle this? Create all JS files? Or use some automagic mechanism to create instances on the fly?

I would vote for automagic mechanism ^____^ and removal of already configured exceptions from the client side but let me check whether this is possible.

**Comment by vogdb** [comment]
Yep. We can do magic here. Who is up for magic?

**Comment by njam** [comment]
sgtm! Would still be great if we *could* implement specific child classes if desired (for those cases where extra logic is needed).

**Comment by vogdb** [comment]
ok, will count those in too.

**Comment by fauvel** [comment]
Should I merge this as a quick fix, though?

**Comment by vogdb** [comment]
hmm, no need no need

**Comment by fauvel** [comment]
Well I need it right now... for the next release (within 1 hour)?

**Comment by njam** [comment]
agree we can merge this. @vogdb can you open a followup?

**Comment by vogdb** [comment]
noooo

**Comment by fauvel** [comment]
@vogdb please delete all existing JS class declarations once you have implemented the "magic"!

**Comment by vogdb** [comment]
Why you have done this? I've already prepared a fix here.

**Comment by vogdb** [comment]
I did write here to wait a little bit

**Comment by vogdb** [comment]
=(

**Comment by vogdb** [comment]
='(

**Comment by njam** [comment]
sorry :no_mouth:

**Comment by fauvel** [comment]
oh I'm sorry too, I didn't think you were so quick... Underestimated your magic powers :)

**Pull request merged**
