### PR TITLE
Add styles for background previews

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by fauvel** [comment]
@njam please review

**Comment by njam** [comment]
@christopheschwyzer can you review this?
@fauvel can you give Christophe an intro?

**Comment by christopheschwyzer** [comment]
I think I understand. Wondering if the url `$params['background-image']` should consider the _static_ flag?

I remember we recently introduced `image-inline` in `CM_Asset_Css` with a similar purpose (it automatically creates a low-res background preview image). Could this be combines somehow?

**Comment by fauvel** [comment]
@christopheschwyzer please review! We've done something similar to `CM_Asset_Css` on purpose, but I'm not sure it can be combined easily...

**Comment by christopheschwyzer** [comment]
Sorry about the delay. Reviewing now :)

**Comment by christopheschwyzer** [comment]
lgtm!

**Pull request merged**
