### PR TITLE
Convert CM_Stream_Message into a service

### PR DESCRIPTION
**Pull request by tomaszdurka**
### Breaking Notice
Breaks in-code public api (class names). 
Breaks public cm commands:
- `stream start-message-synchronization` -> `message-stream start-syncrhonization`.

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by tomaszdurka** [comment]
Actually postpone this review. I meant to ask for review of #1665 first.

**Comment by tomaszdurka** [comment]
@njam This code is ready to review. I would be really glad to close all those service-related issues which have been started.

**Comment by tomaszdurka** [comment]
### Breaking Notice
This code is breaking as changes public classes and method in-code. 
Additionally cm command has changed:
`stream start-message-syncrhonization` -> `message-stream start-syncrhonization`.

**Comment by njam** [comment]
Thanks for those detailed change notes!
There's a small typo in it - "syncrhon...".
Also I would suggest to move them to the ticket description - this is where I usually look if I upgrade CM in denkmal for example, wdyt?

**Comment by tomaszdurka** [comment]
Done.

**Comment by tomaszdurka** [comment]
Strange test failure. Haven't see it before.
```
1) CM_Paging_AbstractTest::testGetItemRandMean
Failed asserting that 1.3799999999999999 matches expected 0.90000000000000002.
```

**Comment by njam** [comment]
`testGetItemRandMean` is expected to fail very rarely I think cc @fauvel

**Comment by njam** [comment]
- CM_MessageStream_Service::getAdapterClass: Null check not needed
- CM_MessageStream_Service::getInstance: Remove?
- CM_MessageStream_Service::__construct: Consider moving adapter creation into a dedicated factory? Like `CM_File_Filesystem_Factory`?
- CM/RenderAdapter/Layout.php: Introduce a variable for serviceManager?
- 

Further:
- What happens to the stored clockwork entry for `CM_Stream_Message::synchronize` - we discussed this problem with Alexis, but I don't remember what the outcome was?
- Requires adjustments on other systems (infrastructure, Procfile)..
- Full change should be acceptance tested

**Comment by tomaszdurka** [comment]
@njam 

- Null check is again needed as adapter might not be set - then it's disabled...
- Removed.
- Did so as in VideoStream.
- This has been simplified with use of newly introduced `getClientOptions()`.


Further:
- Well clockwork will be restarted with release. Old synchronize will be stored in Clockwork storage, but not used anymore. New synchronize will be started immediately and rerun every minute.
- Indeed, as in Breaking Notice.
- I will do testing while adjusting SK (example component and chat).

**Comment by fauvel** [comment]
> Maybe mock randomness? :)

Let's introduce a service for that! ;)

**Comment by njam** [comment]
- CM_MessageStream_Service: Add a test (especially for case without adapter?)

Rest looks very good

**Comment by tomaszdurka** [comment]
@njam please do final check, thanks!

**Comment by njam** [comment]
lgtmbnt (but not travis)

**Pull request merged**
