### PR TITLE
Add a TTL to CM_Queue

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by fauvel** [comment]
@njam please review

**Comment by njam** [comment]
> it's not so clear on first sight what the TTL applies to
the whole queue or the individual entry
maybe add a note to CM_Queue::setTtl?

**Comment by fauvel** [comment]
It's the whole queue (key)

**Comment by njam** [comment]
Yes, just meant that for other developer this might not be clear from the signature/docu. Should we add an explanation?

**Comment by fauvel** [comment]
@njam please review

**Pull request merged**
