### PR TITLE
Record user's UA whenever he's online

### PR DESCRIPTION
**Pull request by zazabe**
related to https://github.com/cargomedia/sk-support/issues/44#issuecomment-252866401

### CODE REVIEW

**Comment by zazabe** [comment]
@njam please review

**Comment by zazabe** [comment]
hum, it will not work i think, because `CM_Session::findById()` retrieve a `CM_Session` without any `CM_Http_Request_Abstract` when the `sessionId` cookie is set...
Let me check it...

**Comment by zazabe** [comment]
Should be fine like that, please review @njam

**Comment by njam** [comment]
`addFromRequest` is quite a heavy operation (mysql write query), so we should probably not run it for every request. How about moving it into the `if (!$user->getOnline())`?

**Comment by zazabe** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
