### PR TITLE
Extend FormFields: Date 

### PR DESCRIPTION
**Pull request by christopheschwyzer**
- Input masks for date input field

Some solutions:
- https://github.com/bguzmanrio/maskjs
- https://github.com/igorescobar/jQuery-Mask-Plugin
- https://github.com/RobinHerbots/jquery.inputmask (seems to be the best one)

We also need to adjust based on location https://en.wikipedia.org/wiki/Date_format_by_country

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
changes from https://github.com/cargomedia/cm/pull/1863 included here.

@njam I think it would make the input faster. But it also has some downsides: We need to adjust the mask depending on the location.

**Comment by njam** [comment]
Tried it here briefly: http://robinherbots.github.io/jquery.inputmask/

I'm not a big fan of this kind of input personally, also because I have the feeling it's misusing a lot of HTML features to create new features, which is usually error-prone. *But* I see that it's probably faster for typing a birth date!

Lots of opinions: http://stackoverflow.com/questions/339956/whats-the-best-ui-for-entering-date-of-birth
Not sure, not sure :)

**Comment by christopheschwyzer** [comment]
I see your point. 
Maybe a light version would be good compromise: 3 separate input fields. (Auto focus the next field after input) Could be more convenient to input especially when you trigger "number" keyboard on mobiles.

But maybe it's not worth the effort. Not sure - I see that dropdowns are are bullet-proof the most obvious.

**Comment by christopheschwyzer** [comment]
I will close this, as no perfect solution in sight and status quo is fine.

**Pull request closed without merging**
