### PR TITLE
CM_FormField_Text trigger changed values with `change` event

### PR DESCRIPTION
**Pull request by vogdb**
Trigger changed values with `change` event in CM_FormField_Text

### CODE REVIEW

**Comment by vogdb** [comment]
the alternative is: `this.trigger('change', {previous: valueLast, new: valueCurrent});`
@njam please approve the format, @zazabe please review

**Comment by njam** [comment]
I would pass an object, it's easier to extend.

**Comment by vogdb** [comment]
@zazabe please review!

**Comment by vogdb** [comment]
@zazabe ?

**Pull request merged**
