### PR TITLE
Extract ModalClose functionality into separate class

### PR DESCRIPTION
**Pull request by njam**
Preparation for https://github.com/cargomedia/sk/issues/2175

### CODE REVIEW

**Comment by njam** [comment]
@christopheschwyzer @vogdb wanna review and test?

Note that this adjustment is needed for textformatter: https://github.com/cargomedia/sk/pull/2179

**Comment by vogdb** [comment]
Looks ok. Have a problem with emoticons in CommentAdd. Researching now.

**Comment by vogdb** [comment]
yep. When I click on the emoticon icon in CommentAdd, it ToggleCloses the CommentAdd component.

**Comment by vogdb** [comment]
@njam can you see the same problem?

**Comment by christopheschwyzer** [comment]
lgtm. @vogdb wann have a look a look as well?

**Comment by vogdb** [comment]
lgtm

**Pull request merged**
