### PR TITLE
Optional $createStamp for video thumbnails

### PR DESCRIPTION
**Pull request by njam**
In preparation for https://github.com/cargomedia/cm/pull/2065

@tomaszdurka please review

### CODE REVIEW

**Comment by njam** [comment]
@tomaszdurka please review

@alexispeter fyi

**Comment by tomaszdurka** [comment]
Create stamp will be optional now, so you will pass it as `--createStamp` parameter, right?

**Comment by njam** [comment]
True, changed it!

**Comment by tomaszdurka** [comment]
lgtm

**Comment by alexispeter** [comment]
I'm a bit confused by the comments and the commit-history in here, was it manipulated? So should the createStamp be optional or not? Comment suggest so, but the code says otherwise.

**Pull request merged**
