### PR TITLE
Followup of Epom Adprovider.

### PR DESCRIPTION
**Pull request by vogdb**
Connects to #1708.

### CODE REVIEW

**Comment by vogdb** [comment]
@kris-lab please review.
@njam FYI.

**Comment by njam** [comment]
How about just passing the "accessKey" for each zone through the zone config?

**Comment by vogdb** [comment]
@njam please review.

**Comment by kris-lab** [comment]
- Maybe instead of passing array with accessKey we could do something:
`deafult.php`
```
$config->CM_AdproviderAdapter_Epom->accessKey = 'aaaaaaaaaaa'
```
`CM_AdproviderAdapter_Epom`
```
private function _getAccessKey() {
        return self::_getConfig()->accessKey;
}
```

@njam wdyt?

**Comment by vogdb** [comment]
> - Maybe instead of passing array with accessKey we could do something:
`deafult.php`
```
$config->CM_AdproviderAdapter_Epom->accessKey = 'aaaaaaaaaaa'
```
`CM_AdproviderAdapter_Epom`
```
private function _getAccessKey() {
        return self::_getConfig()->accessKey;
}
```

It was like it before =)

**Comment by njam** [comment]
@kris-lab I told Aleksei to remove that, mainly because I'm not too fond of the whole class-config-approach. Also in the ad provider case we have this zone-configuration built-in.
Potentially we could load zones from multiple epom accounts/servers, so I think configuring it on the zone level is not bad.

Restarted the travis build.

**Comment by vogdb** [comment]
@kris-lab or @njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
