### PR TITLE
Update jquery.ui.widget. from 1.9.2 to 1.11.2, jquery.fileupload.js from 5.26 to 9.8.0.

### PR DESCRIPTION
**Pull request by vogdb**
The child of #1476.

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
lgtm
Tested IE10, iPhone 4 iOS 8.0.2, Android 4.1.2 Stock Browser, Android 4.4.2 Stock / Chrome, Lumia 920 Windows Phone 8 IE11 (File Upload not supported)

**Comment by vogdb** [comment]
Can I merge if Lumia 920 does not support?

**Comment by vogdb** [comment]
Forgot to mention. @christopheschwyzer my previous question was addressed to you.

**Comment by christopheschwyzer** [comment]
yes, good to go. (Lumia didn't work before)

**Pull request merged**
