### PR TITLE
Introduce CM_View_Abstract.getChild

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@vogdb please review

**Comment by vogdb** [comment]
```js
var components = {};
```
Will be global and shared among all components. Is that ok?

Just try this:
```js
var SK_Component_ConversationList_Mailbox = SK_Component_ConversationList_Abstract.extend({

  /** @type String */
  _class: 'SK_Component_ConversationList_Mailbox',

  ready: function(){
    setTimeout(function(){
      console.log(this.getChild('SK_Form_ConversationMessage'));
    }.bind(this), 5000);
  }
});
```

```js
var SK_Component_Conversation = SK_Component_Abstract.extend({
  ready: function() {
    SK_Component_Abstract.prototype.ready.call(this);

    this.getChild('SK_Form_ConversationMessage');
  }
})
```

**Comment by zazabe** [comment]
I see, would be better to store `components` as a property, let me check ;)

**Comment by zazabe** [comment]
less cumbersome :)

**Comment by zazabe** [comment]
@vogdb please review

**Comment by vogdb** [comment]
lgtm

**Comment by vogdb** [comment]
May be `Failed to retrieve` to `Failed to get`?

**Comment by vogdb** [comment]
too late :(

**Comment by zazabe** [comment]
a... but I think those words are nearly synonyms...

**Pull request merged**
