### PR TITLE
Add color param to contentPlaceholder

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@christopheschwyzer please review

**Comment by christopheschwyzer** [comment]
Could we just use `css`?

**Comment by zazabe** [comment]
I tried, but the image generated is just a plain white img without transparency... but yes, we can also always generate it with `alpha: 100%`...

**Comment by zazabe** [comment]
@christopheschwyzer 

we can do: 
```
.contentPlaceholder img {
  visibility: hidden;
}
```

and then use any background on `.contentPlaceholder`, but I thought that having an hardcoded color for the placeholder is a little bit strange, isn't it?

**Comment by njam** [comment]
100% transparency and then using CSS sounds very good!

**Comment by zazabe** [comment]
@christopheschwyzer please review

**Comment by christopheschwyzer** [comment]
lgtm

**Pull request merged**
