### PR TITLE
Serve manifest.json from same origin

### PR DESCRIPTION
**Pull request by njam**
Addressing #1712

@dlondero @mariansollmann please review

### CODE REVIEW

**Comment by njam** [comment]
This file needs to be served from the same site as the web app:
> Please also note that manifest's URL has to be same origin, so you can't use them directly with a CDN.
http://www.w3.org/TR/appmanifest/

**Comment by njam** [comment]
@vogdb maybe you can review too?

**Comment by tomaszdurka** [comment]
Ok! Bit hacky, but there is no other way I guess.

**Comment by njam** [comment]
Unfortunately seems to be the only way. The spec is [not consistent though](https://github.com/cargomedia/CM/issues/1712#issuecomment-88882940), and this is very new technology.
Let's do it like this for now and maybe it can be changed in the future.

**Comment by vogdb** [comment]
And why did you put me on the review ? O_o I was researching about this stuff, analysing...

**Comment by njam** [comment]
@vogdb sorry, wdyt, is it okay? Feedback still appreciated! :)

**Comment by vogdb** [comment]
It's hard to say. I know a little about this topic. I was ready to spend some time on researching but now it's merged. No point =) I'm happy to return to my current task.

**Comment by njam** [comment]
I experimented with this and found that for Chrome the file *has* to be served from the same hostname, no way around it. The spec also mentions it.
So I think it's the only way.

**Comment by vogdb** [comment]
lgtm then!

**Pull request merged**
