### PR TITLE
Introduce DelayedQueue for jobs

### PR DESCRIPTION
**Pull request by njam**
Paired with @alexispeter - wanna double check?

@zazabe fyi

### CODE REVIEW

**Comment by alexispeter** [comment]
revert library/CM/Params.php

rest lgtm

**Comment by njam** [comment]
I thought it can be useful, don't you think?

**Comment by alexispeter** [comment]
But it doesn't work, you would need to pass a getter that uses the streamChannel-factory.

Jut saw another thing: CM_Model_User::offlineDelayed() can be removed.

**Comment by njam** [comment]
Oh true.

The `getStreamChannel()` can be used without a factory, in case of encoding/decoding with ArrayConvertible? I added a test. wdyt?

**Comment by alexispeter** [comment]
Ok, lgtm

**Pull request merged**
