### PR TITLE
Breaking: Update favicons

### PR DESCRIPTION
**Pull request by christopheschwyzer**
- New sizes, new favicon for Android Chrome (additional `manifest.json`)
- Drop IE9 support
- meta tag for "theme-color" Chrome 39+ (http://updates.html5rocks.com/2014/11/Support-for-theme-color-in-Chrome-39-for-Android)
- move images to dedicated folder `meta`

More info http://realfavicongenerator.net/blog/

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@njam don't know why the tests are failing :(

**Comment by njam** [comment]
can you try merging upstream?

**Comment by christopheschwyzer** [comment]
Hm it's _up-to-date_. I re-triggered the build.

**Comment by njam** [comment]
meta! :)

- function.lessVariable.php: LESS `'foo: @' . $variableName . ''` can be simplified to `'foo:@' . $variableName`

These are more about the specs:
- Layout/Abstract/default.tpl: Is there a reason to reorder the `rel="icon"` items?
- Layout/Abstract/default.tpl: You dropped `rel="icon"` with size `160x160`

**Comment by njam** [comment]
@alexispeter is checking the build

**Comment by christopheschwyzer** [comment]
About the `meta` I'm not too happy with the naming as well. I thought `favicon` is not conclusive enough as it contains the startup images as well. (And I didn't want to introduce two folders) I'm open for ideas ;)

**Comment by njam** [comment]
Don't have a better idea.
Android calls it "res(ources)", Apple "app-icons" and "launch-images".
"favicon" might be good because it's the oldest term, but "meta" is okay for me too.

- function.lessVariable.php: You can also remove the empty string in the end

**Comment by christopheschwyzer** [comment]
About the _order_ and _sizes_. I don't know about whether the order is a requirement. Will trust the http://realfavicongenerator.net/ on that. About the `160x160`, according to the changelog http://realfavicongenerator.net/change_log, it seems to be not necessary anymore .

**Comment by christopheschwyzer** [comment]
Tested w/ @NicolasSchmutz on supported devices.
@njam please review

**Comment by njam** [comment]
lgtm!

**Pull request merged**
