### PR TITLE
Fix lazyload memory leak

### PR DESCRIPTION
**Pull request by vogdb**
Currently lazyload leaks a lot with ajax-navigation. It has to be a well-known but still not fixed problem. tuupola/jquery_lazyload#269
In general we need to update the library to the latest master and custom-patch it for now to have `detroy` method.
cc @zazabe @njam

### CODE REVIEW

**Comment by vogdb** [comment]
@zazabe please review. Did I manage the placement of the new library correct? Should I move it elsewhere like `after-body-main`?

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by njam** [comment]
lgtm

I would suggest to wait a few days, to see if we get a response to those PRs, wdyt?

**Comment by vogdb** [comment]
ok. I expected them to be merged/edited quicker cause my previous requests had callbacks less than 24hours. However now it is the third day of waiting :(

**Comment by vogdb** [comment]
@njam FYI

**Pull request merged**
