### PR TITLE
Empty translation keys in admin

### PR DESCRIPTION
**Pull request by fvovan**
Probably using CM_I18n_Prase in CM_Exceptions leads to adding empty translation keys to database table. Need to add additional checkings to its constructor

### CODE REVIEW

**Comment by fvovan** [comment]
@alexispeter , please review

**Comment by alexispeter** [comment]
* Do a comparison with empty string. Using `empty()` will also return true if $phrase is `0`.
* use CM_Exception_Invalid rather than CM_Exception_InvalidParam. InvalidParam is reserved for exceptions relating to parameters supplied by the client and lead to a 404 http response.

**Comment by NicolasSchmutz** [comment]
@fvovan is this released? I can still see the empty key...

**Comment by fvovan** [comment]
Not yet. will make new CM tag and following sk PR now

**Comment by alexispeter** [comment]
The empty key is still here, but the bug that lead to it is fixed.

**Comment by NicolasSchmutz** [comment]
ok thanks!

**Pull request merged**
