### PR TITLE
Breaking: Inject layout dynamically in ajax_loadPage()

### PR DESCRIPTION
**Pull request by njam**
Part of #2327

Based on #2355 

TODO:
- Check usages of `cm.findView()` and `cm.getLayout()`

### CODE REVIEW

**Comment by zazabe** [comment]
reminder: 
- move `loadPage()`/`_loadPageThrottled` to the document
- whenever the layout has changed, replace it and then inject the page (`<div class="page-placeholder" />`)
- check usages of `cm.findView()` / `cm.getLayout()`, they may use `loadPage()` on the layout cmp
- remove the logic to reload the page when the layout has changed, [`layoutClass`, see todo](https://github.com/cargomedia/cm/pull/2363/files#diff-bcefa35f2b86b41f511e45e3780dd24eR125)

**Comment by zazabe** [comment]
It works in general, few questions still:
- [`scrollToHash`](https://github.com/cargomedia/cm/pull/2363/commits/08d003341c4b08c4b1db3271c9d77011d5d8e58f#diff-1be377e12edf0831d5bba657e9621597R142) feature: how it is supposed to work?     
for example, `cm.getDocument().loadPage('/about/help#codeOfHonor')` will load `/about/help` only, because `#codeOfHonor` is dropped by [`CM_Http_Response_View_Abstract::_createGetRequestWithUrl()`](https://github.com/cargomedia/cm/blob/master/library/CM/Http/Response/View/Abstract.php#L260)
- more questions here: https://github.com/cargomedia/sk/pull/3991

**Comment by zazabe** [comment]
@vogdb please review

**Comment by vogdb** [comment]
> - scrollToHash

We can drop it.

**Comment by vogdb** [comment]
lvgtm. One minor note. What happens to the old layout when it is replaced? Is it destroyed somehow?

**Comment by zazabe** [comment]
> What happens to the old layout when it is replaced? Is it destroyed somehow?

[`CM_View_Abstract::replaceWithHtml()`](https://github.com/cargomedia/cm/blob/master/library/CM/View/Abstract.js#L238) should take care of that, isn't it?

**Pull request merged**
