### PR TITLE
Use autotrack for google analytics

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
There's one issue with this solution, page loaded by ajax will be tracked twice, because both autotack and CM are calling `ga("send", "pageview", ...)`...
We could send "pageview" with CM on page load only, but then some custom tracking may not work anymore I guess... wdyt @njam?

**Comment by zazabe** [comment]
Note that `autotrack` will not send "pageview" when the page is loaded, only on `pushState/replaceState`...

**Comment by zazabe** [comment]
I think the best is to not use `autotrack` and to send "pageview" in `cm.route.router` directly

**Comment by njam** [comment]
sgtm!

**Comment by zazabe** [comment]
as discussed with @njam, let's drop the `pushState` tracking, to avoid having too many tracked url on GA, but let's keep the GA plugin support on `CMService_GoogleAnalytics_Client`...

**Comment by zazabe** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
