### PR TITLE
Follow-up of Form.getData.

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@njam please review.

**Comment by njam** [comment]
functionality lgtm

Disabled "integer" field looks strange:
screen shot 2015-10-10 at 13 04 00

**Comment by vogdb** [comment]
Do we need to drop value to `0` ?

**Comment by njam** [comment]
No I think we should keep the value, just meant that the left part of the bar should be visible too.
We can merge this though, and open a followup.

**Pull request merged**
