### PR TITLE
Use more specific naming for CM_StreamChannel_Definition binding methods

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Could be. Maybe `addStreamEventListener` ? :)

**Comment by zazabe** [comment]
ok, just for you ;)

**Comment by tomaszdurka** [comment]
<3

**Comment by zazabe** [comment]
I added some methods to bind actions directly, @vogdb could you take a look?

**Comment by vogdb** [comment]
Can we use `/^(\d+)\s+(.+)$/` instead of `/^(\S+)\s+(.+)$/` and remove `isNumber` check? Have you tried? If yes then lgtm

**Comment by zazabe** [comment]
The first match is a string, then we get the type number from `cm.action.types`, so the `RegExp` and the `isNumber` condition sgtm, wdyt?

**Comment by vogdb** [comment]
lgtm!

**Pull request merged**
