### PR TITLE
Move mail delivery agent configuration to protected function

### PR DESCRIPTION
**Pull request by ppp0**
Right now part of  `_send`.. awkward to overwrite in subclasses

Better: separate function

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
- _send: Docu: Only include excepections that will be thrown directly from here (`CM_Exception_Invalid`)

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
- _send: I don't think it can throw `phpmailerException` - we catch those and rethrow?

**Comment by ppp0** [comment]
@njam sorry, my bad

**Comment by njam** [comment]
lgtm

**Pull request merged**
