### PR TITLE
assertFormResponseSuccess should also check assertViewResponseSuccess

### PR DESCRIPTION
**Pull request by dlondero**
also consider assertFormResponseError

### CODE REVIEW

**Comment by dlondero** [comment]
@njam please review

**Comment by njam** [comment]
Can you elaborate on why `assertFormResponseError` calls `assertViewResponseSuccess`? When we use it do we expect the response to generally succeed, and to contain form errors?

If so, then all good

**Comment by dlondero** [comment]
That's correct: we expect the response to be successful but with form errors.

**Comment by njam** [comment]
ok, all good then!

**Pull request merged**
