### PR TITLE
Caching of query: cm_model_languagekey

### PR DESCRIPTION
**Pull request by alexispeter**
The following query is part of the translation module. When starting an application up an application (or releasing a new version), this query piles up. Since it's quite heavy this becomes a problem quickly.

> SELECT k.name AS `key`, v.value, k.variables FROM `cm_model_languagekey` as `k` LEFT JOIN `cm_langua[…]

@fvovan @alexispeter could you have a look?
Can we make the caching smarter (prevent many cuncurrent lookups)? Or can we warm up this cache in `fillCaches()`?

### CODE REVIEW

**Comment by alexispeter** [comment]
please review @njam
I added a cli-command bin/cm app fill-language-cache, which should be added to the deployment-script after the updates are run. In case any updates modified translations, this call will refill the file-cache.

**Comment by njam** [comment]
Couldn't we just run the normal `fill-caches` again? I understand if caches are already present this should take almost no time, right?

@fvovan could you review?

**Comment by alexispeter** [comment]
I don't think so. Many of the assets prepared in CM_App::fillCache() contain heavy operations that do not use caching. E.g. the javascript-assets cache, the result of the minification, but not the code that is collected by scanning the filesystem.
Using fill-caches after updates have run takes about 12 seconds, using fill-language-cache takes about 60 ms.

**Comment by fvovan** [comment]
Is it a case that `CM_PagingSource_Abstract` can be used with two cache types (local and persistent) at the same time?

**Comment by alexispeter** [comment]
No.

**Comment by fvovan** [comment]
lgtm

**Comment by alexispeter** [comment]
Had a brief talk with @njam concerning app deployment. We'll try resetting the file-cache eagerly instead of lazily. This will prevent situations where none of the caches is present in the case of language-keys created lazily by first-time access, as well as rendering the explicit refilling of the cache, after updates have been run, unnecessary.

**Comment by alexispeter** [comment]
please review @fvovan

**Comment by alexispeter** [comment]
The language-table might still get a lot of reads when a new language-key is "created" by multiple simultaneous requests. The number of affected requests will be smaller though, so it should be less of an issue than before.

**Comment by fvovan** [comment]
lgtm

**Pull request merged**
