### PR TITLE
Improve button styles

### PR DESCRIPTION
**Pull request by christopheschwyzer**
- Make buttons more flexible
- Fix button large

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@zazabe please review

**Comment by christopheschwyzer** [comment]
hm wait a second

**Comment by christopheschwyzer** [comment]
@zazabe please review

**Comment by zazabe** [comment]
lgtm, btw I added some demo buttons on the example page, you can cherry pick them here https://github.com/zazabe/cm/commit/09183b2c03a77a659c0ca783aa25a27b64e703f4

**Comment by christopheschwyzer** [comment]
Sgtm. Added your changes. 
I will merge it then.

**Pull request merged**
