### PR TITLE
Update normalize.css

### PR DESCRIPTION
**Pull request by christopheschwyzer**
v4.0.0
https://github.com/necolas/normalize.css

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@njam please review/assign

**Comment by njam** [comment]
lgtm, let's check it thoroughly in SK

**Comment by christopheschwyzer** [comment]
@njam Yes - I already found an issue :/. Will work a bit with it a few days before I merge this.

**Comment by christopheschwyzer** [comment]
I updated to the latest version again. From what I can tell everything still works as expected. 
@njam please verify

**Comment by njam** [comment]
lgtm

**Pull request merged**
