### PR TITLE
Add less-easing

### PR DESCRIPTION
**Pull request by christopheschwyzer**
https://github.com/dmnsgn/less-easing
https://github.com/emagnier/sass-less-stylus.easing

Small collection of variables for css transitions. 
- Check with http://easings.net/#
- Check off-canvas menu transition

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
I've added the file to the `css` folder, but technically it's just variables. Not sure if we should import them into the `variables.less` or move the file somewhere else. 
@njam please review

**Comment by njam** [comment]
We should make sure that these are loaded *before* any LESS code. This is why we have `variables.less`, it gets loaded in the very beginning.

I would add it to `variables.less` in the end? Maybe add a comment about where it comes from?

**Comment by christopheschwyzer** [comment]
I guess we can do it like suggested, as this will not change anytime soon. At some point we might consider splitting this file up for readability. Still ok for now. @njam please verify

**Comment by njam** [comment]
agree, lgtm

**Pull request merged**
