### PR TITLE
Add global event bus for App

### PR DESCRIPTION
**Pull request by vogdb**
In `CM_App`:
```
cm.event.trigger('notification.conversation.change', 12)
```

In view:
```
  globalEvents: {
    'notification.conversation.change': function(count) {
    }
  },
```

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review =)

**Comment by njam** [comment]
- I'd still vote for `cm.event` (and not `cm.globalEvents`). Or are there reasons to use `globalEvents` rather? Maybe then on the View call it `bindAppEvent`?

@tomaszdurka please have a look!

**Comment by vogdb** [comment]
@njam Please look. Did I understand you correctly?

**Comment by njam** [comment]
- CM/App.js: Docu should be type `Backbone.Events`?
- CM/App.js bind/unbind: Docu for `callback` lists params which are not present
- CM/App.js trigger: Make `data` optional
- CM/View/Abstract.js: Property should be `appEvents` and not `events` (latter is already used by Backbone!)

@tomaszdurka can you check and let us know what you think of this in general?

**Comment by tomaszdurka** [comment]
I am a bit confused, `events` property on view was mainly used for dom elements' bindings (via Backbone), right?. Now they are binded on global cm app instance. Won't this break whole app?

Regarding usage of `cm.app.events` I am always against extending global singleton usages :)

**Comment by vogdb** [comment]
@njam please review.

**Comment by tomaszdurka** [comment]
@vogdb I don't think @njam meant to rename `app.events` to `app.appEvents` - it was probably just about `view.events` which would conflict with Backbone ones.

I am not sure what you guys want this functionality for, but I would propose to not add `appEvents` property and rather bind in-code when needed.

**Comment by njam** [comment]
- cm.events: should be `cm.event` (as discussed all other similar objects are singular).
- cm.event: bind/unbind: Param-docu for callback should be `Array` instead of `array`?

I'm in favor of `View::appEvents` - it makes usage simpler. @tomaszdurka can you share your concerns?

**Comment by vogdb** [comment]
> cm.event: bind/unbind: Param-docu for callback should be Array instead of array?

No. Because all other like `stream` or `action` use `array`.

@njam please review.

**Comment by tomaszdurka** [comment]
I agree with @njam that it should be `Array` as this is the real type name. 
If you try typing `{array}` instead of `{Array}` in param doc-block intellij will highlight it as an error. 
Of course our `fn()` syntax is something which does not support this syntax check, but still we should use valid class names. If the param suppose to be type of `CM_Class_Abstract` you wouldn't use `cm_class_abstract` would you?

**Comment by vogdb** [comment]
So, why you have used `array` previously?

**Comment by tomaszdurka** [comment]
I think longer time ago we used lowercase array all over the project, but then intellij started to mark them as error - so we search replaced all curly bracket wrapped usages to uppercase. These were missed.

**Comment by njam** [comment]
It looks good to me now!

(btw here's the JSDoc suggestions  on the `callback` topic: http://usejsdoc.org/tags-callback.html)

**Comment by vogdb** [comment]
Yep. Such format exists but should I break the docu consistency with other code? Do you give your permission?

**Comment by njam** [comment]
I would keep it as is. The signature of the callback is pretty straight forward and well known, so I think there's no need to use this advanced syntax, wdyt?

**Comment by vogdb** [comment]
I'd use it as it is now. Do we need to wait for Tomasz's review?

**Comment by tomaszdurka** [comment]
Ok for me.

**Pull request merged**
