### PR TITLE
Allow any ArrayConvertible to be stored with model schema

### PR DESCRIPTION
**Pull request by tomaszdurka**
How about we allow to store any instance of `CM_ArrayConvertible` in `CM_Model_Schema_Definition`, by json stringifying the array structure and storing it in the persistence layer?
We're doing something similar for models already.

@alexispeter @tomaszdurka wdyt?

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam want to review?

**Comment by njam** [comment]
- Schema/Definition.php: this should *not* use `CM_Params::encode()`, because those are internally calling `jsonSerialize()` if the object implements `JsonSerializable` (recent change). For this use case we want the most minimalistic data that identifies the object, so the output of only `toArray()`. This can be retrieved by `CM_Params::encodeObjectId()`.
 - Maybe add a test with an object that also implements `JsonSerializable`
- DefinitionTest.php: How about testing that encode+decode are compatible - like sending the output of one to the input of the other?

**Comment by njam** [comment]
I'm also wondering if we should really include `_class` in the serialized value. As we discussed it's not really necessary, because we know the *base* class from the schema, and can just call `BaseClass::fromArray($data)` which should be able to create the right instance.
Storing the `_class` in the database has the disadvantage that one needs to update lots of records if the class gets renamed. So I would rather prefer to *not* store it.
wdyt?

**Comment by njam** [comment]
Three ways:
- `CM_Params::encode($object)`
- `CM_Params::encodeObjectId($object)`
- `$object->toArray()` **<--- should be sufficient here**

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
