### PR TITLE
Fix pseudo-element css selectors

### PR DESCRIPTION
**Pull request by christopheschwyzer**
Should use double colon for pseudo-elements: E.g. `::after` instead of `:after`.

Interesting article http://bitsofco.de/2015/pseudo-classes-pseudo-elements-and-colon-notation/?utm_source=CSS-Weekly&utm_campaign=Issue-169&utm_medium=email

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@vogdb please review

**Comment by vogdb** [comment]
looks very good but also we need to work on `scrollShadow` plugin.

**Comment by christopheschwyzer** [comment]
@vogdb oh you're right - missed that one ;) please verify

**Comment by vogdb** [comment]
lgtm

**Pull request merged**
