### PR TITLE
Convert CM_Stream_Video into a service

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam please review Not sure about the latest commit (moving Video Stream into separate module).

**Comment by njam** [comment]
Generally looks very good!

- CM_VideoStream_Service::rpc_*: Shouldn't these use `$this` instead of getting the videostream-service from the servicemanager?
- CM_VideoStream_Service::getInstance: remove?
- CM_VideoStream_Service: Naming - the factory method is called `createClient()` - should this be a `_Client`?
- CM/Service/Manager.php::getStreamVideo: Wrong class name `CM_Stream_Video`
- CM_Maintenance_Cli: Also replace `CM_Stream_Video`

Also:
- This will need adjustments in wowza code!
- This might need adjustments in SK?
- This should be acceptance tested

Could you prepare all these things, test them, then I can test them too and do a final review.

@kris-lab can you have a look as well?

**Comment by kris-lab** [comment]
In general I like this change. Splitting Message and Video stream makes sense. I am wondering should it be called `VideoStream` and `MessageStream`? Now we have `stream` which have adapter of type `message` of e.g. type `socket-redis`. I am wondering what could be other use case for stream adapter? In `VideoStream` is it much cleaner now imo.

I agree with @njam on adjusting other stuff and testing this in details.

**Comment by tomaszdurka** [comment]
@njam 

- rpc_* methods are static ones (it would be hard to implement)
- In each of the latest pull-requests I try to mark getInstance() methods as deprecated. In this case indeed it's a bit different as whole class has been renamed. Maybe it makes sense to remove it then.
- Oh, true. Not sure should this be Client or method createService. Wdyt? I am confused about this whole naming (Client, Manager, Service, *Mediator* :) )
- ok
- ok

Also:
- agree
- agree
- agree

@kris-lab 

As we already talked via hipchat message stream will be separated into a module too. There is separate pull-request for it https://github.com/cargomedia/CM/pull/1666 where I will implement it.

**Comment by tomaszdurka** [comment]
@njam Please review.

**Comment by njam** [comment]
- CM_Maintenance_Cli: Class name in string should be `CM_VideoStream_Service` instead of `CM_VideoStream`?

Also:
- This will need adjustments in wowza code!
- This might need adjustments in SK?
- This should be acceptance tested

@kris-lab maybe you can help with the adjustments and tests?

**Comment by tomaszdurka** [comment]
Tests are somehow not starting, any ideas on reasons?

@kris-lab let me know when/if you wanna work on this :)

**Comment by kris-lab** [comment]
@tomaszdurka on which part should I work? Call me so we can discuss details?

**Comment by njam** [comment]
Probably tests are not running because the branch cannot be merged on master.

@kris-lab I thought about the CM-wowza adjustments (CLI command name change), and to test it fully.

**Comment by kris-lab** [comment]
sure! I can do it anytime. @tomaszdurka please reach me on hipchat for 5min talk so we can procced asap

**Comment by tomaszdurka** [comment]
Ping me back after you back from "holidays" :)

**Comment by tomaszdurka** [comment]
### Breaking Notice
Breaks in-code public api (class names changes).
Breaks public cm commands:
-  `stream import-video-archive` -> `video-stream import-archive`
-  `stream import-video-thumbnail` -> `video-stream import-thumbnail`
Breaks public RPC endpoints
- `CM_Stream_Video.*` -> `CM_VideoStream_Service.*`

**Comment by tomaszdurka** [comment]
@kris-lab have you been able to test video-streaming with this pull-request?

**Comment by tomaszdurka** [comment]
@kris-lab would be great to finish this one up :)

**Comment by kris-lab** [comment]
@tomaszdurka sure, let's pair on it; it requires quite some configuration...

**Comment by kris-lab** [comment]
@tomaszdurka sorry for delay; I will combine testing of this changes with setting up new configuration for wowza -> https://github.com/cargomedia/puppet-packages/issues/898

**Comment by njam** [comment]
@kris-lab @tomaszdurka can you finish this one up?

**Comment by tomaszdurka** [comment]
Pair-reviewed with @fvovan

**Pull request merged**
