### PR TITLE
Reset service manager instances on test clearEnv

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by njam** [comment]
lgtm, any impact on test speed?

**Comment by tomaszdurka** [comment]
Travis tests took usual time.

**Comment by njam** [comment]
ok! good to go then?

@alexispeter fyu

**Comment by njam** [comment]
@tomaszdurka good to go?

**Comment by tomaszdurka** [comment]
Yes, let's do it.

**Comment by njam** [comment]
Should we now remove those calls in SK?
```php
$this->getServiceManager()->getElasticsearch()->setEnabled(false);
```

**Comment by tomaszdurka** [comment]
We can do that. Let's open issue then.

**Comment by njam** [comment]
@tomaszdurka did that (while doing the same on denkmal): https://github.com/cargomedia/sk/issues/1452

**Comment by tomaszdurka** [comment]
Sorry about that, missed that one somehow.

**Pull request merged**
