### PR TITLE
StreamChannel: Make stream-object available in canSubscribe/canPublish

### PR DESCRIPTION
**Pull request by alexispeter**
See discussion in cargomedia/sk#2432

### CODE REVIEW

**Comment by alexispeter** [comment]
please review @tomaszdurka

**Comment by tomaszdurka** [comment]
Hmm, but shouldn't canPublish/canSubscribe be run without stream?

**Comment by alexispeter** [comment]
We want to be able to use isSubscribe/isPublish inside canSubscribe/canPublish. For that we need the stream.

**Comment by tomaszdurka** [comment]
Bit confused here. Didn't you @njam comment on this one once we talked?

**Comment by njam** [comment]
I'm also not sure about this… let's discuss in https://github.com/cargomedia/sk/issues/2456

**Comment by alexispeter** [comment]
Discontinued.

**Pull request closed without merging**
