### PR TITLE
Make wowza service optional

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
- CM/Maintenance/Cli.php: Maybe only register callbacks if service is available? Like further down for maxmind.

**Comment by tomaszdurka** [comment]
@njam please check

**Comment by njam** [comment]
You changed it from 1 min to 15 min on purpose?

Otherwise lgtm

**Comment by tomaszdurka** [comment]
Copy-paste-master :panda_face:

**Pull request merged**
