### PR TITLE
Use Travis container-based infrastructure

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by njam** [comment]
@fauvel duplicate of https://github.com/cargomedia/cm/pull/1853 ?

**Comment by fauvel** [comment]
Hm looks like :) Another approach would be to white-list `mongodb-org-server` on https://github.com/travis-ci/apt-package-whitelist.

**Comment by fauvel** [comment]
See https://github.com/travis-ci/apt-package-whitelist/issues/516

**Comment by fauvel** [comment]
Looking at their PR history, I guess it should be available by the end of the week.

**Comment by njam** [comment]
Is it already available?
-> https://github.com/travis-ci/apt-package-whitelist/search?q=mongodb-org-server&type=Issues&utf8=%E2%9C%93

**Comment by fauvel** [comment]
No, it's not available yet, they only white-listed the APT source. Bumped them.

**Comment by fauvel** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Are we waiting on https://github.com/travis-ci/apt-package-whitelist/pull/597 here too?

**Comment by fauvel** [comment]
We're not waiting any more, it's mergeable. But with https://github.com/travis-ci/apt-package-whitelist/issues/516, we could improve it a bit and revert this temporary workaround (97f4c98).

**Comment by tomaszdurka** [comment]
Yes. That's what I meant with https://github.com/cargomedia/cm/commit/97f4c9840b558ce86013b2182fa0cb6be757ae2a.

Looks good!

**Pull request merged**
