### PR TITLE
Add race to bluebird Promise

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@vogdb please review

**Comment by zazabe** [comment]
@vogdb oups, I used `node tools/build.js --features "core, settle, cancel, timers, race"`, but only core and race are in the lib...

**Comment by vogdb** [comment]
What can I say here. I'm waiting.

**Comment by zazabe** [comment]
@vogdb should be fine, please review

**Comment by vogdb** [comment]
lgtm

**Pull request merged**
