### PR TITLE
Extend button_link with href

### PR DESCRIPTION
**Pull request by christopheschwyzer**

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@njam @tomaszdurka what do you think?
Theoretically you could pass now `page` and `href` - don't think it's a problem.

**Comment by njam** [comment]
Hmhmhm shouldn't we use an  `<a>` element with an `href` attribute?
Maybe we could based on if there is an `href` render `a` or `button`, and all the rest stays the same?
Let me know if you want to pair.

**Comment by christopheschwyzer** [comment]
We would need some additional css - but yes - sounds reasonable.

**Comment by christopheschwyzer** [comment]
@njam please have a look

**Comment by njam** [comment]
lgtm

**Pull request merged**
