### PR TITLE
Add getErrors in CM_Http_Response_View_Form

### PR DESCRIPTION
**Pull request by dlondero**
Allow to access errors in CM_Http_Response_View_Form.

### CODE REVIEW

**Comment by dlondero** [comment]
@njam please review

**Comment by njam** [comment]
Would be nice to know what types these are. I think they are strings, can you confirm? If so, let's change the docu to `string[]`.

**Comment by dlondero** [comment]
@njam yes, strings. Error message and sometimes fieldName as well.

**Comment by njam** [comment]
Ok, lgtm

**Pull request merged**
