### PR TITLE
Wrap "pecl install" in "travis_retry" because it fails often

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@tomaszdurka @dlondero @vogdb please review

**Comment by tomaszdurka** [comment]
This magic looks good. How many times it tries?

**Comment by vogdb** [comment]
It's hard for me to judge whether it is ok or not =) Lgtm!
Btw why did we need the `--dev` param?

**Comment by njam** [comment]
- --dev: composer changed this in recent versions, it's now default and actually shows a deprecation warning if passed...
- How many times it tries?: 3

**Comment by dlondero** [comment]
@njam lgtm!

**Pull request merged**
