### PR TITLE
Add JanusVideoServer adapter for MediaStream

### PR DESCRIPTION
**Pull request by fvovan**
Suggested API:
- rpc_publish
- rpc_unpublish
- rpc_subscribe
- rpc_unsubscribe
- checkStreams
- stopStream
- synchronize?

### CODE REVIEW

**Comment by fvovan** [comment]
@tomaszdurka please review.
actually it is just copypaste :)

**Comment by tomaszdurka** [comment]
Looks good, but let's wait for more specification from Chris and Reto

**Comment by njam** [comment]
@tomaszdurka @fvovan closeable?

**Comment by fvovan** [comment]
yes

**Pull request closed without merging**
