### PR TITLE
Include mainPaths content in browserify cache key

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@zazabe @fauvel please review

**Comment by njam** [comment]
@zazabe @fauvel please review

**Comment by zazabe** [comment]
- not sure if `$cacheKeyMainPaths` is needed, do you think we could have diff `$mainPaths` but with the same concatenated `$involvedFiles` content?

**Comment by njam** [comment]
As discussed it's needed because the list of entry points affects directly the generated code.

**Comment by fauvel** [comment]
lgtm! shortening the cache key by calling md5 iteratively definitely makes sense, too.

**Pull request merged**
