### PR TITLE
ColorPalette form field

### PR DESCRIPTION
**Pull request by njam**
For https://github.com/cargomedia/sk/issues/4251

Abstract class `CM_Type_Color` extends `MischiefCollective\ColorJizz\ColorJizz\RGB` (https://github.com/mikeemoo/ColorJizz-PHP):
- __construct($red, $green, $blue)
- brightness
- saturation
- hue
- toHexString
- factoryFromHexString

New fields:
- CM_FormField_Color
- CM_FormField_ColorPalette

### CODE REVIEW

**Comment by njam** [comment]
@christopheschwyzer it's ready. Could you review and take over?
Ping me to set up the sk/cm linking together. You need to install the new dependency in SK first.

**Comment by christopheschwyzer** [comment]
screen shot 2016-12-05 at 11 31 37

@njam wdyt?

**Comment by njam** [comment]
Looks good.

I added 2 more commits, could you review them?

**Comment by christopheschwyzer** [comment]
As discussed. Will try using radios

**Comment by christopheschwyzer** [comment]
@njam wdyt?

**Comment by njam** [comment]
lgtm
Added one more, please review

**Comment by christopheschwyzer** [comment]
lgtm

**Pull request merged**
