### PR TITLE
Breaking: Upgrade to Bluebird 3.x

### PR DESCRIPTION
**Pull request by vogdb**
See http://bluebirdjs.com/docs/new-in-bluebird-3.html
Especially: http://bluebirdjs.com/docs/api/cancellation.html

@vogdb when you find some time, let's upgrade?
cc @zazabe

### CODE REVIEW

**Comment by vogdb** [comment]
@zazabe please check VR part

**Comment by zazabe** [comment]
ok, testing...

**Comment by zazabe** [comment]
wooow, plenty of warning!

**Comment by vogdb** [comment]
Yep but they were before :)

**Comment by njam** [comment]
Does it still reject with `Promise.CancellationError`?

**Comment by vogdb** [comment]
Yes. You can try both variants:
```js
    var promise = new Promise(function(resolve, reject) {
      reject(Promise.CancellationError());
    }).catch(function(error) {
      console.log('#####', error instanceof Promise.CancellationError);
    });
```
```js
    var promise = new Promise(function(resolve, reject) {
      throw Promise.CancellationError();
    }).catch(function(error) {
      console.log('#####', error instanceof Promise.CancellationError);
    });
```

**Comment by vogdb** [comment]
or better those variants for 100%
```js
    var promise = new Promise(function(resolve, reject) {
      reject(Promise.CancellationError());
    })
      .then(function() {
        console.log('$$$$$$$$$$$$');
      })
      .catch(function(error) {
        console.log('#####', error instanceof Promise.CancellationError);
      });
```
```js
    var promise = new Promise(function(resolve, reject) {
      throw Promise.CancellationError();
    })
      .then(function() {
        console.log('$$$$$$$$$$$$');
      })
      .catch(function(error) {
        console.log('#####', error instanceof Promise.CancellationError);
      });
```

**Comment by zazabe** [comment]
yes but from what i've tested, `cancel()` is sync now and has no argument, cancelling with this method will not call `catch` anymore.

**Comment by vogdb** [comment]
@zazabe How about that? Should be more consistent now.

**Comment by njam** [comment]
So on `cancel()` the promise will *not* execute `catch()` behaviour, but it *will* execute `finally()` code?

If that's the case, then we should make sure we're using `finally()` wherever we expect a promise to be fulfilled sooner or later. For example `jquery.clickDecorators/decorators/30-spinner.js` (which uses `finally()`).

**Comment by vogdb** [comment]
Also one interesting thing:

> Note that it is an error to consume an already cancelled promise, doing such a thing will give you a promise that is rejected with new CancellationError("late cancellation observer") as the rejection reason.

So, I would keep the handling of CancellationError in error handlers. @njam ?

**Comment by zazabe** [comment]
@vogdb cargomedia/sk#2728 is working well with your branch now, VR Components are okay but we still have warning during the feature detection step, mostly because many promises are rejected without an `Error` argument.

**Comment by njam** [comment]
So *are* cancelled promises going through `unhandledrejection`? If so, then I think we should keep the handling of `CancellationError`.

**Comment by vogdb** [comment]
> So *are* cancelled promises going through `unhandledrejection`? If so, then I think we should keep the handling of `CancellationError`.

Yes. The thing is that now they are generated less than before cause direct `.cancel` call does produce `CancellationError`.

**Comment by njam** [comment]
I see!

```js
Promise.config({cancellation: true});
var p = new Promise(function() {})
 .then(function(){ console.log('then'); })
 .catch(function(){ console.log('catch'); })
 .finally(function(){ console.log('finally'); })
p.cancel();

finally
```

**Comment by njam** [comment]
- promiseThrottler: Why remove `cancelTrailing`?
- CM/Layout/Abstract.js: _loadPageThrottled: I think here we need to introduce `finally()` (since the behaviour changed we need to make sure that code that needs to be executed no matter what, also on cancellation, should go into a `finally`, right?)
- CM/App.js: ajax: In `fail()` we potentially `reject` the promise twice - should that second part go into an `else`? [this is only vaguely related]

Let's also get Michel's opinion here.

**Comment by vogdb** [comment]
> - promiseThrottler: Why remove `cancelTrailing`?

The used approach was appropriate while we could cancel promise with CancellationError. Now cancel does not reject. Thus we can't use rejection to cancel. So, I removed it cause couldn't think of solution that can cancel a trailing promise. Plus this option wasn't used.

**Comment by vogdb** [comment]
@njam @zazabe please look

**Comment by zazabe** [comment]
lgtm!

I just have one concern about the bluebird `cancel` implementation, which is sync now: a cancelled promise is directly settled and there's no way to know if the resolver code is still running or not...

It probably make sense... but it would be good also if it was possible to wait the end of the cancelled promise before doing something else...

With the `promiseThrottler` we have to be careful and check in `finally` if the promise has been cancelled, then clean up everything to ensure that the current call will not be impacted by a previous one...


```
var promise = new Promise(function(r) {setTimeout(function(){console.log('foo');r();}, 1000)}); 
promise.finally(function() {console.log('finally', promise.isFulfilled(), promise.isPending())}).cancel()
> finally false false
undefined
> foo
```

**Comment by vogdb** [comment]
Very good catch!

**Comment by vogdb** [comment]
@zazabe @njam please review. Should be fine now

**Comment by zazabe** [comment]
lgtm

@vogdb maybe not related to this ticket, but I thought about some simplification: https://github.com/zazabe/cm/commit/0953f9ff2c4b69d2e7beb6accfe9af4ed2d54523

My acceptance test:
```javascript
var foo = function(text, timeout) { return new Promise(function(r) {setTimeout(function() {console.log(text); r();}, timeout)})}; 
var step = function(text) { return function() { return foo('step ' + text, 1000);}; };

var throttle = promiseThrottler(function(text) { return step(text + ' 1')().then(step(text + ' 2')).then(step(text + ' 3')); }, {cancelLeading: true});

throttle('a'); throttle('b'); throttle('c'); 
> step c 1
> step c 2
> step c 3

var throttle = promiseThrottler(function(text) { return step(text + ' 1')().then(step(text + ' 2')).then(step(text + ' 3')); }, {cancelLeading: false});

throttle('a'); throttle('b'); throttle('c'); 
> step a 1
> step a 2
> step a 3
> step b 1
> step b 2
> step b 3
> step c 1
> step c 2
> step c 3
```

**Comment by zazabe** [comment]
@vogdb I forget the `queue: false` options... so the code will not be much simpler anyhow...

I think we can merge it like it is ;)

**Pull request merged**
