### PR TITLE
Uncovered password input

### PR DESCRIPTION
**Pull request by christopheschwyzer**
...with _hide_ option. 

See https://youtu.be/nmKMz3Fg76M?t=14m55s

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
Current approach: 
Two input fields that you can toggle. This not be the best idea as we have two input fields with the same ID and I'm not sure if that can cause problems :/

**Comment by njam** [comment]
We can't change the `type` of the input?

**Comment by christopheschwyzer** [comment]
According to http://stackoverflow.com/a/1544338 it's not possible. Haven't verified it though.

**Comment by njam** [comment]
This answer is about a jQuery restriction which they put in place because of IE.
I can't find this restriction in current jQuery. I imagine it works in IE9+?

**Comment by christopheschwyzer** [comment]
@njam You're right. I should start to read through articles.

**Comment by njam** [comment]
`togglePasswordMask` could probably be simplified into one code branch.
Maybe à la?:
```js
var showText = (type === 'password');
$input.attr('type', showText ? 'text' : 'password');
$buttonText.toggle(showText);
$buttonPassword.toggle(!showText);
```

**Comment by christopheschwyzer** [comment]
Yes!

**Comment by njam** [comment]
Code lgtm, haven't tested it.

Are we hiding the native UI for this in IE?
Should Nicolas do some testing?

**Comment by christopheschwyzer** [comment]
Native UI is my biggest concern. I didn't dare testing it yet :grin:. Also I created a new icon that is not available yet https://github.com/cargomedia/cm/pull/1857.

**Comment by christopheschwyzer** [comment]
Solved for IE!

**Comment by christopheschwyzer** [comment]
One difference is that mobile phones use to start with an uppercase letter for textfelds (opposed to password fields that are lowercase by default)

**Comment by njam** [comment]
http://stackoverflow.com/questions/5171764/how-do-you-turn-off-auto-capitalisation-in-html-form-fields-in-ios ?

**Comment by christopheschwyzer** [comment]
yep. Should be all good now.

**Comment by njam** [comment]
Cool! Code looks good.

Any more testing needed?

**Comment by christopheschwyzer** [comment]
I think technically it's fine - not sure how users will embrace it ;)

**Comment by njam** [comment]
@NicolasSchmutz you wanna test it and give your opinion?

**Comment by NicolasSchmutz** [comment]
lvgtm!

**Pull request merged**
