### PR TITLE
Check if the HTTP server is up before running QUnit tests

### PR DESCRIPTION
**Pull request by zazabe**
`bin/qunit` may fail with this error:
```
Unable to access network: fail
phantomjs://code/phantomjs-runner.js:109
```

### CODE REVIEW

**Comment by zazabe** [comment]
@njam please review

**Comment by njam** [comment]
Using a bash `trap` could be nice here, to ensure the php server is killed when the script exits:
```sh
trap "kill ${SERVER_PID}" EXIT
```
See `build-ci.sh` for an example.

Another nice pattern to implement a timeout is using the `timeout` command, e.g.:
```sh
timeout --signal=9 3 bash -c "while ! (nc -z 127.0.0.1 8080 &>/dev/null); do sleep 0.1; done"
```
If the while doesn't finish after 3 seconds it will kill it with signal "9", and the whole `timeout` command will exit with a status other than 0.

**Comment by zazabe** [comment]
nice tips, thanks!

@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
