### PR TITLE
Add user-agent parsing library

### PR DESCRIPTION
**Pull request by fvovan**
For several reason we need a user-agent parsing library (again).
The main goals are:
- Detect device category (desktop, tablet, mobile)
- Detect device vendor and model

Options:
- https://github.com/serbanghita/Mobile-Detect
- https://github.com/ua-parser/uap-php
- …possibly others - let's investigate!

Considerations:
- Wrap it somehow?
- Should work together with `CM_Http_Request_Abstract::getHeader('user-agent')`
- Should be cached, if not done in the library already?

### CODE REVIEW

**Comment by fauvel** [comment]
@njam quick review?

**Comment by fvovan** [comment]
unfortunately they rely on PHP HTTP headers format ( I mean prefixed with "HTTP_")

**Comment by njam** [comment]
How long does it take to instantiate the class and check for `isMobile()` (see `CM_Util::benchmark()` for example).

Let's remove some application specific info from the test! Otherwise looks good!

**Comment by fvovan** [comment]
>How long does it take to instantiate the class and check for isMobile() (see CM_Util::benchmark() for example).

about 3ms

**Comment by fvovan** [comment]
@njam please review.
decided together with Sebastien to add caching.

**Comment by njam** [comment]
- Use `__METHOD__`  instead of `__CLASS__, 'isMobile'`

rest lgtm

**Pull request merged**
