### PR TITLE
Make sure failing memcache connection leads to error

### PR DESCRIPTION
**Pull request by zazabe**
Currently the `CM_Memcache_Client` constructor is:
```php
    public function __construct(array $servers) {
        $this->_memcache = new Memcache();
        foreach ($servers as $server) {
            $this->_memcache->addServer($server['host'], $server['port'], true, 1, 1, 15, true, function ($host, $port) {
                $warning = new CM_Exception('Cannot connect to memcached server', CM_Exception::WARN, [
                    'host' => $host,
                    'port' => $port,
                ]);
                CM_Bootloader::getInstance()->getExceptionHandler()->handleException($warning);
            });
        }
    }
```

The problem is that if *no* server at all can be reached we only log a warning.
How it should work:
- If we can't connect to a single server, but can connect to another one we should log a warning.
- If we can't connect to any server we should throw and abort with an error

Docu: http://php.net/manual/en/memcache.addserver.php

Currently it aborts, but only logs a warning.
Example stack trace:
```
CM_Exception: Cannot connect to memcached server in /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Memcache/Client.php on line 15
0. {main} at /home/example/releases/20160824142623/bin/cm line 0
1. CM_Cli_CommandManager->run(CM_Cli_Arguments) at /home/example/releases/20160824142623/bin/cm line 18
2. CM_Process->fork(Closure) at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Cli/CommandManager.php line 175
3. CM_Process->_fork(Closure, 9) at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Process.php line 65
4. CM_Process_ForkHandler->runAndSendWorkload() at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Process.php line 228
5. CM_Cli_CommandManager->{closure}(CM_Process_WorkloadResult) at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Process/ForkHandler.php line 76
6. CM_Cli_Command->run([], CM_InputStream_Readline, CM_OutputStream_Stream_StandardOutput, CM_OutputStream_Stream_StandardError) at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Cli/CommandManager.php line 288
7. call_user_func_array([], []) at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Cli/Command.php line 27
8. [internal function] at line
9. CM_Jobdistribution_JobWorker->run() at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Jobdistribution/Cli.php line 19
10. GearmanWorker->work() at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Jobdistribution/JobWorker.php line 28
11. [internal function] at line
12. CM_Jobdistribution_Job_Abstract->_executeJob(['user' => SK_User(15502737)]) at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Jobdistribution/Job/Abstract.php line 128
13. SK_Elasticsearch_UpdateJob_UserActivity->_execute(['user' => SK_User(15502737)]) at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Jobdistribution/Job/Abstract.php line 19
14. SK_Params->getUser('user') at /home/example/releases/20160824142623/library/SK/library/SK/Elasticsearch/UpdateJob/UserActivity.php line 7
15. CM_Params->getUser('user', NULL) at /home/example/releases/20160824142623/library/SK/library/SK/Params.php line 370
16. CM_Params->_get('user', NULL) at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Params.php line 314
17. CM_Params->decode([]) at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Params.php line 535
18. CM_Model_Abstract->fromArray([]) at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Params.php line 646
19. CM_Model_Abstract->factoryGeneric(102, []) at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Model/Abstract.php line 706
20. unserialize('C:7:"SK_User":58:{a:2:{s:2:"id...') at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Model/Abstract.php line 598
21. [internal function] at line
22. CM_Model_Abstract->_construct([], NULL) at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Model/Abstract.php line 191
23. CM_Model_Abstract->_getData() at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Model/Abstract.php line 50
24. CM_Model_StorageAdapter_Cache->load(102, []) at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Model/Abstract.php line 289
25. CM_Cache_Abstract->get('CM_Model_StorageAdapter_Cache_...') at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Model/StorageAdapter/Cache.php line 6
26. CM_Cache_Storage_Abstract->get('CM_Model_StorageAdapter_Cache_...') at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Cache/Abstract.php line 51
27. CM_Cache_Storage_Memcache->_get('/home/example/releases/201608...') at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Cache/Storage/Abstract.php line 36
28. CM_Memcache_Client->get('/home/example/releases/201608...') at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Cache/Storage/Memcache.php line 23
29. MemcachePool->get('/home/example/releases/201608...') at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Memcache/Client.php line 38
30. [internal function] at line
31. {throw} at /home/example/releases/20160824142623/vendor/cargomedia/cm/library/CM/Memcache/Client.php line 15
```

@zazabe or @alexispeter maybe for you?
cc @cargomedia/devops

### CODE REVIEW

**Comment by zazabe** [comment]
Note: 
- `Memcache::addServer` vs `Memcache::addserver`:  
  - camelCase in http://php.net/manual/en/memcache.addserver.php 
  - `print_r(get_class_methods('Memcache')); => Array(.., [2] => 'addserver', ...)`

**Comment by zazabe** [comment]
@alexispeter please review

**Comment by alexispeter** [comment]
Two things that make this solution not work.
1. It seems you assume that memcache tries all servers in sequence. Judging from some testing however, memcache seems to try to distribute keys among available servers, leading to servers being connected to in any order.
2. Contrary to what the interface might suggest, the failure callback seems not to work at a per-server basis. This means the last callback added with `addserver` will be used by all servers.

We will probably have to use a counter to detect that we can't connect to any server, but even this is a bit flaky, since servers might come and go during process-runtime, messing up the counter.
Perhaps we should do what memcached suggests in this situation and simply ignore it? 
> Modern life encourages the use of "Failure", when possible. That is, if the server you intend to fetch or store a cache entry to is unavailable, simply proceed as though it was a cache miss. You might still flap between old and new data if you have a Server B situation, but the effects are reduced.

From https://github.com/memcached/memcached/wiki/ConfiguringClient#failure-or-failover

**Comment by ppp0** [comment]
Sorry to interfere, but
>memcache seems to try to distribute keys among available servers

Isn't this the case if using a memcache "cluster"? We're not! We only have one instance of a memcache server. Agree, the config looks confusing by accepting a list of servers.

**Comment by njam** [comment]
Good point!
Memcache doesn't have any *cluster* concept. Instead it distributed values in a "hash ring" on the available servers. If a node is down, there's no way to retrieve it from another node.

> That is, if the server you intend to fetch or store a cache entry to is unavailable, simply proceed as though it was a cache miss. 

That sounds like a sound plan. Let's implement it that way.

**Comment by njam** [comment]
> In the dark days of memcached, the default was to always "failover"

Urks.

**Comment by zazabe** [comment]
- seems we need to [configure the client][puppet-mm] to disable the failover with [`memcache.allow-failover = 0`][memcache-conf-failover]
- now I'm not sure when we should throw an error... maybe we could [check the status][server-status] of all servers in the `$failure_callback` and throw an error if they are all down?


  [server-status]: http://php.net/manual/en/memcache.getserverstatus.php
  [puppet-mm]: https://github.com/cargomedia/puppet-packages/blob/master/modules/php5/templates/extension/memcache/conf.ini
  [memcache-conf-failover]: http://php.net/manual/en/memcache.ini.php#ini.memcache.allow-failover

**Comment by njam** [comment]
Usually if you lose 1 memcached server then it's a critical situation, because there's no failover (in the sense of a replica that can take over the work of the failing host immediately).
See https://blog.serverdensity.com/handling-memcached-failover/

We never had problems with memcached so far, it's very robust. I think we can just throw an error if *any* server is not reachable.

**Comment by zazabe** [comment]
as discussed with @njam:
- let's log an error vs throwing an exception for any `$failure_callback`
- disable `memcache.allow-failover` to avoid the ["server B"](https://github.com/memcached/memcached/wiki/ConfiguringClient#failure-or-failover) situation (https://github.com/cargomedia/puppet-packages/issues/1480).

**Comment by alexispeter** [comment]
But why bother throwing an error if you could simply get what you wanted to get from memcache from the database or wherever instead?

**Comment by zazabe** [comment]
@alexispeter please review

**Comment by alexispeter** [comment]
I would make CM_Memcache_Client serviceManagerAware and get the logger from there.

**Comment by zazabe** [comment]
There's a delay before retrying from a failed server, as discussed with @njam, let's set it to `1s` VS `15s`.

**Comment by zazabe** [comment]
right! (seems i'm scared to use `CM_Service_ManagerAwareTrait` since i tried on a model :D) @alexispeter please review

**Comment by alexispeter** [comment]
Remove the unused variable, rest lgtm

**Pull request merged**
