### PR TITLE
Parse GA MP parameter list in trackHit()

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by fauvel** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Comment by fauvel** [comment]
Sorry, please review again

**Comment by njam** [comment]
`_queueHit` could be protected?

**Comment by fauvel** [comment]
Yep, is there any reason why `_submitHit` isn't?

**Comment by njam** [comment]
Because it's called from within the background job.

**Comment by fauvel** [comment]
Looks better now?

**Comment by njam** [comment]
lgtm

**Comment by fauvel** [comment]
Tagged 1.126.5

**Pull request merged**
