### PR TITLE
Logger: Add mongodb handler

### PR DESCRIPTION
**Pull request by fvovan**
Via https://github.com/cargomedia/cm/pull/1859

The Mongodb handler should accept a "TTL" and a "collection" configuration.
The TTL needs to be applied somewhere (setup script?).

cc @alexispeter

### CODE REVIEW

**Comment by fvovan** [comment]
@alexispeter could you review please?

**Comment by alexispeter** [comment]
* library/CM/Log/Handler/MongoDb.php
 + constructor: Invert the condition in the ternary operator. We usually make it so the "default" values comes after the colon. `

**Comment by alexispeter** [comment]
rest looks good

**Comment by fvovan** [comment]
@alexispeter  please review

**Comment by alexispeter** [comment]
lgtm

**Pull request merged**
