### PR TITLE
Simplify resource Responses and Assets

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
As discussed with @njam I won't overcomplicate it too much.

One of the problem which arised is having several problems solved by `CM_Asset_Css*`. It could be separated into 3 separate concepts - `CM_Css`, `CM_Asset_Css_Vendor/Library` and `CM_Frontend_ViewCss`...

**Comment by njam** [comment]
@tomaszdurka what about this? Some tickets depend on it now. Can we finish the not-overcomplicated version quickly?

**Comment by njam** [comment]
@tomaszdurka I was looking at this with Alexis. The changes on the branch look reasonable. But what's discussed on the ticket here is something else. Not sure what's the importance of this. What do you think - how should we proceed with this?

**Comment by njam** [comment]
Closing for now.
@tomaszdurka if you have thoughts on this one, please share and reopen

**Pull request closed without merging**
