### PR TITLE
CM_Util::jsonEncode: fails with warning

### PR DESCRIPTION
**Pull request by fvovan**
Addressing https://github.com/cargomedia/cm/issues/2235

### CODE REVIEW

**Comment by fvovan** [comment]
I managed to reproduce it but probably it's not the case for unit testing.
Basically the exception occurs either  when fluentd tries to log 404 error or when GA encodes the content of the page. So it's hard to mock without real environment.
And the testing is just checking if 'sanitized' key appears in admin 404 error log record.
We may continue keep an eye on it.

`$_server` had to be sanitized as well because of `php_self` and few other uri related values inside.

@njam please review

**Comment by njam** [comment]
How about doing this in the constructor, to cover all use cases of this class?

Could we add a unit test by using this command you showed to create an invalid string? Then show that it doesn't fail? Or it's only possible in php-fpm?

BTW it would be good to *not* transform this to a PR, so we can keep the ticket open until it's fully resolved. I opened a new one: https://github.com/cargomedia/cm/issues/2235

**Comment by fvovan** [comment]
>Could we add a unit test by using this command you showed to create an invalid string? Then show that it doesn't fail? Or it's only possible in php-fpm?

Yes, it's  a problem with `display_errors`. Besides, received 500 error is a consequence of `CMService_GoogleAnalytics_Client->getHtml(CM_Frontend_Environment)` call came from some included smarty template. and GA on test env. seems to be not configured the same way as for production.

I added the test checking if wrong utf value was converted to valid one inside of constructor.

>BTW it would be good to not transform this to a PR, so we can keep the ticket open until it's fully resolved. I opened a new one: #2235

Oh sorry. I did it "automatically".

**Comment by njam** [comment]
lgtm

**Pull request merged**
