### PR TITLE
Breaking: Revert "ElementQuery media polyfill. #1650"

### PR DESCRIPTION
**Pull request by vogdb**
The used library has a bug that it applies itself only to the visible elements on the page after dom-ready event. The elements that became visible after some user action are not tracked by this library.

### CODE REVIEW

**Comment by vogdb** [comment]
@christopheschwyzer @njam please review.

**Comment by christopheschwyzer** [comment]
lgtm

**Comment by christopheschwyzer** [comment]
Although, lessphp and breakpoint-variable changes could don't need to be reverted.

**Comment by vogdb** [comment]
We will include them in the next issue with a fix of ElementQuery library.

**Comment by christopheschwyzer** [comment]
Alright

**Comment by njam** [comment]
ok

**Pull request merged**
