### PR TITLE
CM_MenuItem::compare() fails when comparing scalars with arrays

### PR DESCRIPTION
**Pull request by alexispeter**
Present implementation fails when comparing scalars with arrays, i.e. when a parameter is defined as scalar value on a menu-item but also has valid array-values (e.g. an object is identified by an id and type) or vice versa.
It fails with an `E_NOTICE: Array to string conversion` because array_intersect_assoc() casts values to strings to do a strict comparison.

Addendum: This obviously applies to all cases were either the parameter on the menu or the one compared to it is an array.

### CODE REVIEW

**Comment by alexispeter** [comment]
please review @njam 

Doesn't distinguish values like int(0) empty string anymore, but I can't imagine a scenario where that would be a problem.

**Comment by njam** [comment]
I would keep the strict comparison. For example `count=0` is different from `count=`? Or what's the reason to not do it?

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
lgtm

**Comment by alexispeter** [comment]
please review @njam

last commit covers cases were the menu-value is a scalar and the param-value an array or vice versa (Actually the functionality I described in this issue's description).

**Comment by njam** [comment]
lgtm

**Pull request merged**
