### PR TITLE
make encryption url-safe

### PR DESCRIPTION
**Pull request by alexispeter**
`+/=` are not url-safe, see http://stackoverflow.com/questions/1374753/passing-base64-encoded-strings-in-url/5835352#5835352

### CODE REVIEW

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
lgtm, please revert test.php

@fvovan wanna have a look as well?

**Comment by alexispeter** [comment]
Hmm I think I should put a comment into the code.

**Comment by fvovan** [comment]
But why it worked before (when is was not extracted to separate class)?

**Comment by alexispeter** [comment]
I suppose the previous applications (nodejs message streaming) didn't care about it.

**Comment by alexispeter** [comment]
tagged https://github.com/cargomedia/cm/releases/tag/1.160.12

**Pull request merged**
