### PR TITLE
Add smarty_function_resourceFileContent

### PR DESCRIPTION
**Pull request by christopheschwyzer**
Function to return inline svg

UPDATE:
..to return any kind of resource file content

### CODE REVIEW

**Comment by njam** [comment]
- Extract `$params['path']` into a variable at the top (increases visibility of available parameters)?

Rest looks good.

**Comment by christopheschwyzer** [comment]
@njam like this?

**Comment by njam** [comment]
Yes! I'd also add type casting. This way the code it more robust and documentation for input arguments is clearer.
```php
$path = (string) $params['path'];
```

**Comment by christopheschwyzer** [comment]
@njam voilà ;)

**Comment by njam** [comment]
lgtm

Restarted build

**Comment by christopheschwyzer** [comment]
keeps failing :/

**Comment by njam** [comment]
It's green!

**Comment by christopheschwyzer** [comment]
:green_heart:

**Pull request merged**
