### PR TITLE
Make CM_Dom_NodeList implement ArrayAccess

### PR DESCRIPTION
**Pull request by alexispeter**
Docu: http://php.net/manual/en/class.arrayaccess.php

Use case:
```php
$domeNode = new CM_Dom_NodeList('<div/><div/>');
$domeNode[0]->getHtml();
```

cc @mariansollmann

### CODE REVIEW

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
- offsetSet: Should check that it's an instance of DomNodeList?

**Comment by alexispeter** [comment]
You mean `DOMNode`.

**Comment by njam** [comment]
Hmmm yes agree!

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
lgtm

**Pull request merged**
