### PR TITLE
Reset serviceManager instances on forking

### PR DESCRIPTION
**Pull request by alexispeter**
To avoid sharing mysql connection between processes.
Addressing https://github.com/cargomedia/puppet-cargomedia/issues/724

After forking, in the child call something like:
```php
CM_Service_Manager::getInstance()->resetInstances();
```

Can add an acceptance test with something like this:
```php
$assert = function ($expected, $actual) {
    if ($expected !== $actual) {
        throw new Exception('Assertion failed: `' . $expected . '` !== `' . $actual . '`');
    }
};

$mysql = CM_Service_Manager::getInstance()->getDatabases()->getMaster();
$mysql->setBuffered(false);

$process = CM_Process::getInstance();
$process->fork(function () use ($assert, $mysql) {
    for ($i = 0; $i < 1000; $i++) {
        $result2 = $mysql->createStatement('SELECT "bar"')->execute()->fetchColumn();
        $assert('bar', $result2);
    }
});

for ($i = 0; $i < 1000; $i++) {
    $result1 = $mysql->createStatement('SELECT "foo"')->execute()->fetchColumn();
    $assert('foo', $result1);
}

$process->waitForChildren();
```

@alexispeter for you?

### CODE REVIEW

**Comment by njam** [comment]
Why is this
```php
$serviceManager->registerInstance('debug', new CM_Debug(CM_Bootloader::getInstance()->isDebug()));
```
needed? What's the story here @tomaszdurka ?

**Comment by alexispeter** [comment]
It's the only service that's instantiated programatically instead of via config, because the debug-flag is set programatically on the bootloader. Alternatively we could set theservice-config from within the bootloader to work around this.

**Comment by njam** [comment]
As discussed we'll keep the approach, but make "debug" a service with configuraton.

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
lvgtm

**Pull request merged**
