### PR TITLE
Add short url flag to linkUrl

### PR DESCRIPTION
**Pull request by christopheschwyzer**

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
Maybe it should be called differently. Couldn't think of an accurate name. _stripProtocol_ or sth.
@njam @tomaszdurka please review

**Comment by christopheschwyzer** [comment]
Maybe just `short`

**Comment by njam** [comment]
- Shot sgtm
- I would do regexp pattern `'#^https?://(www\.)?#'`
 - Use `#` for limiting, so we don't need to escape `/`
 - Use `^` to match beginning of string
 - Match `s?` instead of `.?` (dot is any character)
 - Escape `\.` after www, because `.` is any character

**Comment by christopheschwyzer** [comment]
Thanks. Makes sense! @njam please verify

**Comment by njam** [comment]
lgtm

**Pull request merged**
