### PR TITLE
Update fastclick.js from 1.0.3 to 1.0.5.

### LINKED ISSUE #1581: Track fastclick#344
https://github.com/ftlabs/fastclick/pull/344

### PR DESCRIPTION
**Pull request by vogdb**
Closes #1581.

### CODE REVIEW

**Comment by vogdb** [comment]
@christopheschwyzer please review.
@njam FYI.

Unfortunately they shifted the tabulation to the right.

**Comment by christopheschwyzer** [comment]
lgtm

**Comment by njam** [comment]
Just to be sure, did you test this on the different browsers? (looks like lot of incoming changes..)

**Comment by vogdb** [comment]
Honestly not because the changes were marked as minor, e.g. 1.0.3 -> 1.0.5. Only iPhone5s,iPhone6 on iOS8.1.

**Comment by vogdb** [comment]
Will test now.

**Comment by njam** [comment]
BTW now there's 1.0.6!
>  Fix various Firefox bugs by disabling FastClick in Firefox 27+

Looks like after the release many new bug reports came in :)

**Comment by christopheschwyzer** [comment]
On the topic: http://developer.telerik.com/featured/300-ms-click-delay-ios-8/

**Comment by njam** [comment]
> iOS 8 also complicates things. Even though it has a fast click “solution”, that solution is only present under certain circumstances, and using a fast click JavaScript library makes your app feel responsive regardless of whether your users are fast clickers or slow clickers.

@vogdb can you update to 1.0.6?

**Pull request merged**
