### PR TITLE
Browserify: Automate library loading

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@fauvel please review

**Comment by fauvel** [comment]
Très bien conçu, but as discussed, I would suggest to split up `_appendDirectoryBrowserify` and to introduce a method `_appendFilesBrowserify` that would accept a list of single javascript files to include.

**Comment by zazabe** [comment]
@fauvel please review

**Comment by fauvel** [comment]
lgtm, let's get sk ready before merging?

**Pull request merged**
