### PR TITLE
Add missing seconds to smarty_function_date_time

### PR DESCRIPTION
**Pull request by dlondero**

### CODE REVIEW

**Comment by dlondero** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Well, I understood that we should add those only for Admin.

**Comment by dlondero** [comment]
@tomaszdurka please review. Used `show*` flag name like we do in `date` plugin with `showTime` and `showWeekday`.

**Comment by dlondero** [comment]
@tomaszdurka ?

**Comment by dlondero** [comment]
@fvovan please review.

**Comment by fvovan** [comment]
lgtm, but probably `$showSeconds` could be inlined without any lack of readability.

**Comment by dlondero** [comment]
@fvovan agree. Please check.

**Comment by fvovan** [comment]
lgtm

**Pull request merged**
