### PR TITLE
Implemented Inspectlet tracking service

### PR DESCRIPTION
**Pull request by fauvel**
Addresses #1764

### CODE REVIEW

**Comment by fauvel** [comment]
@njam please review

**Comment by dlondero** [comment]
@fauvel lgtm. An enable/disable flag in the service configuration would be helpful? Or will this be removed after the tests?

**Comment by fauvel** [comment]
The enabling/disabling of tracking services is being handled by `CM_Service_Trackings`.

**Comment by fauvel** [comment]
Tagged 1.117.5.

**Pull request merged**
