### PR TITLE
Configure redis database=2 in tests

### PR DESCRIPTION
**Pull request by njam**
Addressing https://github.com/cargomedia/sk/issues/1131

@dlondero @tomaszdurka please review

### CODE REVIEW

**Comment by dlondero** [comment]
@njam lgtm!

**Comment by tomaszdurka** [comment]
Just wanted to note down (for some time already) that I like this change a lot.
Small thing is that instantiating redis client is quite complicated and requires dev to look into code and understand config array. Maybe some extended docblock would help with that.

**Comment by njam** [comment]
I googled a bit for such a docu annotation, but couldn't find anything.

**Comment by tomaszdurka** [comment]
Yes unfortunately there is no supported (by intellij) docu syntax. But maybe use something on our own aka:
```php
    /**
     * @param array $config {
     *     @type string $host
     *     @type int $port
     * }
     */
```
Unfortunately this doesn't work well with intellij formatting.

**Comment by alexispeter** [comment]
We have a few methods where we use docs to describe the structure of an array.

```php
/**
* @param array              $chatMessage ['id' => int, 'content' => string, 'createStamp' => int, 'chat' => SK_Entity_Chat 'user' => SK_User]
* @param CM_Frontend_Render $render
* @param boolean|null       $skipOpenChatForSender
* @throws CM_Exception_Invalid
*/
```
###### CM_Model_Abstract::factoryGenericMultiple #####
```php
/**
* @param array    $idTypeList [['type' => int, 'id' => int|array],...] | [int|array,...] Pass an array of ids if $modelType is used
* @param int|null $modelType
* @return CM_Model_Abstract[] Can contain null-entries when model doesn't exist
* @throws CM_Exception_Invalid
*/
```
```php
/**
* @param string $channel
* @throws CM_Exception_Invalid
* @return array ['key' => string, 'type' => int]
*/
```

**Comment by njam** [comment]
True -> https://github.com/cargomedia/CM/pull/1612

**Pull request merged**
