### PR TITLE
Introduce CM_Util_NamedArgs for easier services configuration

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@alexispeter please review
@njam fyi

Any objections? Disadvantages?

**Comment by alexispeter** [comment]
I suppose this is to enhance readability of the config?

**Comment by tomaszdurka** [comment]
Yes, that's the goal. We can use named argumetns in config without this - as I do already. This adds some kind of validation to it.

**Comment by alexispeter** [comment]
will review it first thing tomorrow

**Comment by njam** [comment]
Good idea!
Did you research/test the impact of using reflection in production code?

**Comment by alexispeter** [comment]
* library/CM/Service/Manager.php
 + line 203: Including `$method` in the if-clause is unnecessary since getMethod() always returns an instance of ReflectionMethod or throws if it fails.
* resources/config/default.php
 + lines 146 + 159: param `adapter` should be `adapterClassName`

**Comment by tomaszdurka** [comment]
- ok
- ok

Wdyt about removing `isNamedArgs` condition and forcing to always passed named arguments?

**Comment by tomaszdurka** [comment]
Regarding the performance it will be run just couple of times and:
- single isNamedArgs run for 3 arg array takes 0.0214ms
- single matchNamedArgs for 3 arg array with 3 arg method takes 0.01806ms

I would make it standard and remove isNamedArgs check. Agree?

**Comment by alexispeter** [comment]
agree to removing isNamedArgs

**Comment by tomaszdurka** [comment]
@alexispeter please review

**Comment by alexispeter** [comment]
* library/CM/Bootloader.php
 + line 180 Using registerInstance() instead of register() might lead to problems regarding forking and service-manager reset so I'd suggest to switch back to register() until we have a better solution for this fork-problem.
* tests/library/CM/Model/SplittestTest.php
 + line 144 use registerInstance() for conformity?

**Comment by tomaszdurka** [comment]
@alexispeter please review

**Comment by alexispeter** [comment]
lgtm

**Pull request merged**
