### PR TITLE
Add time since page was rendered to cm.debug.log output

### PR DESCRIPTION
**Pull request by njam**
@zazabe please review

### CODE REVIEW

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
@zazabe please review

**Comment by njam** [comment]
@zazabe updated, please review

**Comment by zazabe** [comment]
Maybe we could use `performance.now()` vs `new Date()` (http://caniuse.com/#feat=high-resolution-time) but I don't think it will make a big difference.

**Comment by njam** [comment]
I would stick with `new Date()` because of Android 4.3 support. Also I think the differences will not be relevant for our use cases. wdyt?

**Comment by zazabe** [comment]
yes, lgtm, it was more a thought...

**Pull request merged**
