### PR TITLE
Introduce a new option 'focusElement' for jquery.floatbox.js.

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@njam please review,

**Comment by njam** [comment]
- How about raising an error if the `focusElement` is outside the floatbox - this way the developer will notice something's off!
- Add `focusElement` to `options` (as `null`) for documentation purposes?

**Comment by vogdb** [comment]
@njam please review.

**Comment by njam** [comment]
- Only call `.focus()` once, i.e. assign an intermediary `$focusElement` variable?

**Comment by vogdb** [comment]
@njam please review.

**Comment by njam** [comment]
Code looks good, one more thing, how about extracting this into `_getFocusElement()`?

**Comment by vogdb** [comment]
@njam please review.

**Comment by njam** [comment]
lgtm

**Pull request merged**
