### PR TITLE
Get rid of error 'CM_Exception_Invalid: Cannot find valid class definition for view' 

### PR DESCRIPTION
**Pull request by fvovan**
Change exception type  (to warning) in CM_View_Abstract::factory()

### CODE REVIEW

**Comment by fvovan** [comment]
@njam  please review

**Comment by njam** [comment]
I think we should keep it an "error" in the factory, as this is core business logic and potentially used in various places. I suggest we only make it a warning if it comes directly as user input through an AJAX request.
Maybe we could move the extraction and check of the classname out of `CM_Http_Response_View_Abstract::loadComponent` into `CM_View_Abstract::ajax_loadComponent`?

**Comment by fvovan** [comment]
@njam  review please

**Comment by njam** [comment]
- Could you add a test for `ajax_loadComponent()` that covers the new behaviour?
- What do you think about passing the class name normally down to `loadComponent()` (instead of within `$params`), now that we extract it anways?

**Comment by fvovan** [comment]
tests for ```CM_View_Abstract``` are completely absent, will create them

> What do you think about passing the class name normally down to loadComponent() (instead of within $params), now that we extract it anyways?

sounds reasonable but will require us to change SK too, because it has several usages.

**Comment by njam** [comment]
True, but I think it makes sense! Let's do itè

**Comment by fvovan** [comment]
@njam please review
maybe since we extracted className value from params, then we should remove it (from ```$params```)?

**Comment by njam** [comment]
Yes agree, we should remove it.

- CM_CaptchaTest: removed by accident?
- CM_View_AbstractTest::testConstructor: No need to check instance of `$view` as we create it manually

**Comment by fvovan** [comment]
@njam thanks!
yes , it seems I moved but not copied draft for test. I reverted it but for some reason it is shown like complete recreation

**Comment by njam** [comment]
- CM/CaptchaTest.php: Something's still off, if you check the diff. Probably whitespace is different? Can you check if the IDE is configured to use the "cargomedia" code styles?

**Comment by fvovan** [comment]
Old (deleted) version used CRLF for line breaks.
Reverted version was automatically converted with git to use just LF.

**Comment by njam** [comment]
ok, lgtm then!

**Comment by fvovan** [comment]
I will create new CM tag and prepare sk PR very soon

**Pull request merged**
