### PR TITLE
Wrong return-type documented for city-maxmindId

### PR DESCRIPTION
**Pull request by alexispeter**
mysql-schema says int.

### CODE REVIEW

**Comment by alexispeter** [comment]
please review @tomaszdurka

**Comment by tomaszdurka** [comment]
lgtm

**Comment by tomaszdurka** [comment]
should we also update the CM_Model_Location#getMaxMind() to int/string?

**Comment by alexispeter** [comment]
Do you mean the parameter for CM_Model_Location::createCity()? There are not other occurences in CM_Model_Location.

**Pull request merged**
