### PR TITLE
Fix of absolute header for page anchors do not work.

### PR DESCRIPTION
**Pull request by vogdb**
"btw when you navigate to this anchor link about cupids you won't see full paragraph due to "absolute header" :\" (c) the greatest test engineer.

### CODE REVIEW

**Comment by vogdb** [comment]
@fauvel please review.

**Comment by njam** [comment]
- So this will replace `SK_Layout_Default.scrollTo()`
- Isn't the `if ($anchor.length)` still needed? Otherwise we'll always scroll to `0` if there's no anchor?

**Comment by vogdb** [comment]
> - So this will replace SK_Layout_Default.scrollTo()

Yes.
@njam please review.

**Comment by njam** [comment]
lgtm

**Comment by fauvel** [comment]
So what was the problem? `page` was not the right one in this context?

**Comment by vogdb** [comment]
It's hard to explain only in the context of CM =( Lets watch how it will behave.

**Pull request merged**
