### PR TITLE
Disallow creating streamChannel with mediaId used by an existing archive

### PR DESCRIPTION
**Pull request by fvovan**
`createStreamChannel()` should check that there's no archive with the same mediaId.

Mysql:
- `WHERE NOT EXISTS` - http://dev.mysql.com/doc/refman/5.7/en/exists-and-not-exists-subqueries.html

PHP:
- Check twice: before, and after INSERT

### CODE REVIEW

**Comment by fvovan** [comment]
@alexispeter what do you exactly mean by `be valid if created with given values` ? Should it be just discussed checking if `cm_streamChannelArchive_media` with given `mediaId` not exists or should it be the checking similar to `SK_Cam_VideoStreamChannel::isValid()` method, verifying that corresponding session is active i.e extract sessionId from passed channel key  and trying to instantiate it?

**Comment by alexispeter** [comment]
The point is that we check the validity of the streamChannel when publishing/subscribing, but not when creating it.
We think this problem is caused by a new subscriber that connects right as the streamchannel is deleted on the server, but before janus realises that. As a result, the new subscriber "recreates" the streamchannel with the same key and same mediaId, realises that the streamchannel is invalid when trying to create the subscriber and subsequently deletes the whole channel again. 
This could be prevented, if we checked "isValid" before the streamchannel is actually created.

I'm not saying this should be done now, just as a thought for the future.

**Comment by fvovan** [comment]
ah. makes sense. thanks
and for mediaId checking will concurrency unsafe https://github.com/fvovan/CM/commit/a9b14c154748ac1fea20db258f3946e3e368d63f
be sufficient? 
Canonically this issue could be resolved with triggers, I guess we don't use them.

**Comment by alexispeter** [comment]
I thought the idea was to do something like "insert if not exists"?

**Comment by fvovan** [comment]
@njam , @alexispeter could you have a look please.
This ugly SQL statement works, there is just another problem

here `affected_rows` returns 0 if no records were inserted due `cm_streamChannelArchive_media::mediaId` restrictions and if `ON DUPLICATE KEY` was called and 
http://dev.mysql.com/doc/refman/5.5/en/mysql-affected-rows.html
> if an existing row is set to its current values

so to prevent it I need to modify any field (here I tried to increase `createStamp` by 1 it should be changed)

Another option is specifying `CLIENT_FOUND_ROWS ` flag for mysql connection but I'm not sure if it can affect something else.

`LAST_INSERT_ID()` is useless here because it returns inappropriate value if  `cm_streamChannelArchive_media::mediaId` "constraint" hitted.

So I propose just to create "counter of duplicated queried" column.
wdyt?

**Comment by njam** [comment]
oh!

Isn't this dangerous in case we lose connection inbetween?
```sql
$id = CM_Db_Db::exec("SELECT LAST_INSERT_ID()")
```

Maybe we should consider alternatives?
- Combine streamChannel and archive tables
- Do the check in PHP (in `createStreamChannel()` check for existing archives *after* creating the channel, then delete it again)

**Comment by fvovan** [comment]
I would prefer PHP checking then.

>Isn't this dangerous in case we lose connection inbetween?

it's possible to keep `$client`

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/cm/issues/2064 and https://github.com/cargomedia/cm/issues/2056

**Pull request closed without merging**
