### PR TITLE
Add promiseOnce/removePromiseOnce util method

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@vogdb please review

**Comment by zazabe** [comment]
@vogdb you can check usages in zazabe/sk@13031f5

**Comment by vogdb** [comment]
lgtm
How do you think? Should we throw an Error in case if there is an existing `storage[uid]` already at the stage of `promiseOnce` call?

**Comment by zazabe** [comment]
@vogdb mmmh, i don't get your idea because the expected behaviour in this case is to return the existing promise, isn't it?

**Comment by vogdb** [comment]
I meant rather the situation
```js
promiseOnce(function hello(){console.log('hello')}, 'the_same_key')
```
```js
promiseOnce(function bye(){console.log('bye')}, 'the_same_key')
```

**Comment by zazabe** [comment]
@vogdb ok, done

**Comment by vogdb** [comment]
Perfetto!

**Pull request merged**
