### PR TITLE
Performance issues with "CM_Paging_Log->_deleteOlderThan"

### PR DESCRIPTION
**Pull request by fvovan**
The mongodb query from this function times out regularly (30 seconds). See error log.

@fvovan @alexispeter can you investigate the impact of this, and how we can fix it?

### CODE REVIEW

**Comment by fvovan** [comment]
I adjusted an index.
and decided to try timeout PHP driver option  rather than mongodb write concerns
@njam please review.

**Comment by njam** [comment]
@alexispeter could you review this?

**Comment by alexispeter** [comment]
The doocumentation does not mention a `socketTimeoutMS` option for remove-operations, where did you find this?

**Comment by fvovan** [comment]
http://php.net/manual/en/mongocollection.remove.php

**Comment by alexispeter** [comment]
lgtm

**Pull request merged**
