### PR TITLE
Log non UTF request variables

### PR DESCRIPTION
**Pull request by fvovan**
followup https://github.com/cargomedia/cm/issues/2482

There's a new case :(
```
    [sanitizedFields] => Array
        (
            [code] => 434d5f5574696c2d3e6a736f6e456e636f646528272f702f4e30656d69313030394e30656d6920e75f5fe4b8aae4babae8b55f2e2e2e272c204e554c4c29
            [value] => 272f702f4e30656d69313030394e30656d6920e75f5fe4b8aae4babae8b55fe65f5f202d204675636b626f6f6b27
        )
```

Sanitizing the string *again* makes it work.
I would suggest that we detect this case and log it, *before* sanitizing it.
wdyt?
Could you add the debug code?

### CODE REVIEW

**Comment by fvovan** [comment]
is it okay that we log only uri values, since all wrong input goes from it?
@njam wdyt?

**Comment by njam** [comment]
Agree, that's enough.
But I would be stricter with the condition, to make sure we *only* catch those cases that lead to errors now. Basically if json encoding the *sanitized* value leads to an error. wdyt?

**Comment by fvovan** [comment]
good point!
moreover we'll see how it was transformed, hopefully this won't affect performance much

**Comment by njam** [comment]
lgtm

**Pull request merged**
