### PR TITLE
Handle concurrent streamchannel *archive* creations?

### PR DESCRIPTION
**Pull request by fvovan**
Could we something similar like in https://github.com/cargomedia/cm/pull/2054, but for streamchannel *archives*

ON DUPLICATE KEY UPDATE

### CODE REVIEW

**Comment by fvovan** [comment]
@njam please review.

I investigated #2057 related possible problem while was resolving this issue.
Is it okay if we fail when sequently creating two `CM_Model_StreamChannel_Media` with different keys but same `mediaId` field. I guess it should never happen, right?

**Comment by njam** [comment]
lgtm!

@tomaszdurka can you answer Vladimir's question?

**Comment by njam** [comment]
@tomaszdurka can you answer Vladimir's question?
 Show all checks

**Comment by tomaszdurka** [comment]
Should never happen.

**Pull request merged**
