### PR TITLE
Always define a type for mongo log handler

### PR DESCRIPTION
**Pull request by fvovan**

### CODE REVIEW

**Comment by fvovan** [comment]
@njam please review.

**Comment by njam** [comment]
What's the reason?

**Comment by fvovan** [comment]
>What's the reason?

Mongo does not use  index for `$exist` queries.  https://github.com/cargomedia/cm/issues/2309

**Comment by fvovan** [comment]
@njam please review.

**Comment by njam** [comment]
@alexispeter could you review this?

**Comment by alexispeter** [comment]
lgtm

**Pull request merged**
