### PR TITLE
Set minimum-scale=1

### PR DESCRIPTION
**Pull request by njam**
This will enable GPU rasterization in Chrome
See https://www.chromium.org/developers/design-documents/chromium-graphics/how-to-get-gpu-rasterization

@christopheschwyzer or @vogdb could you try how it affects the rendering behaviour of our feed page? I tried on a Samsung S6 and am not sure if it's really better..

### CODE REVIEW

**Comment by vogdb** [comment]
S6 device and my Sony M2 have GPU rasterisation enabled by default, so they don't need this `meta` to work.

S6


Sony M2

**Comment by vogdb** [comment]
And I didn't see any difference between the one with enabling settings and the opposite.

**Comment by christopheschwyzer** [comment]
screen shot 2015-08-10 at 15 19 37
@vogdb Can you check with enabled Monitor. GPU Raster should be green (on)? I think by default it isn't without `minimal-scale` set.

**Comment by vogdb** [comment]
You are right it's disabled on Desktop but I was talking about mobile devices cause I thought that our primary concern are them. Should we consider also Desktop?

**Comment by christopheschwyzer** [comment]
@vogdb oh sorry, all good!

**Comment by vogdb** [comment]
Hm but what about Desktop. Do we want to enable it there?

**Comment by christopheschwyzer** [comment]
I would add the meta tag like suggested in this PR. Doesn't do harm either way.

**Comment by njam** [comment]
Currently it only has an effect on Chrome for Android. You can check with the FPS flag for example.

Ok let's do this then.

**Comment by vogdb** [comment]
True. This `meta` does not enable GPU rasterization on Desktop. The interesting feature about this rasterization is that when I've forced it on Desktop, it had started to devour memory as hell on scroll down.

Forced GPU on Desktop
screen shot 2015-08-10 at 21 54 55


Default GPU
screen shot 2015-08-10 at 21 56 53

**Comment by njam** [comment]
Note this is only *GPU* memory. Probably if it's disabled it goes to different memory.

**Comment by vogdb** [comment]
Ok!

**Pull request merged**
