### PR TITLE
Usernames and flags are cut off in friend requests box

### PR DESCRIPTION
**Pull request by fvovan**
Follow up of https://github.com/cargomedia/sk/pull/1924
Need to add additional CSS class to location block containing flag and set correct string shrinking for it.

### CODE REVIEW

**Comment by fvovan** [comment]
@christopheschwyzer , I added 'contains-flag' CSS class to location block.
Could you change styles please? If you need another html formatting for it please just ping me.

**Comment by christopheschwyzer** [comment]
@fvovan haven't forgot about it, but low priority ;)

**Comment by NicolasSchmutz** [comment]
@christopheschwyzer wanna check?

**Comment by christopheschwyzer** [comment]
Couldn't push. 

> ERROR: Permission to fvovan/cm.git denied to christopheschwyzer.
fatal: Could not read from remote repository.

@fvovan you can pull from https://github.com/christopheschwyzer/CM/tree/function-flag-adjustments or give me access rights.

**Comment by fvovan** [comment]
@christopheschwyzer  thank you :) .
@njam please review

**Comment by njam** [comment]
If you guys say it's okay I trust you!

**Comment by christopheschwyzer** [comment]
@fvovan I pushed a small change - but too late. Did a follow-up https://github.com/cargomedia/cm/pull/1917

**Comment by tomaszdurka** [comment]
We have a failing tests on sk http://ci.cargomedia.ch:8080/job/cargomedia-sk-pr/6124/console

@fvovan is this cause of your changes?

**Pull request merged**
