### PR TITLE
Add text-overflow: ellipsis; to buttons

### PR DESCRIPTION
**Pull request by christopheschwyzer**

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@dlondero please review

**Comment by dlondero** [comment]
I'm not totally sure about this: shouldn't the form adapt to have a wider button?  If users can't read the label totally they can miss the purpose of the button.

**Comment by christopheschwyzer** [comment]
Yes, I agree. This rule only applies when there is an explicit `width` or `max-width` set - which we try to avoid of course. But there might be some edge cases where this can come in handy.

**Comment by dlondero** [comment]
Ok, thanks for the clarification. Looks good then!

**Comment by christopheschwyzer** [comment]
Build keeps failing for php 5.5. 
screen shot 2015-01-21 at 19 12 31

**Pull request merged**
