### PR TITLE
Allow to pass timeZone to smarty date helpers

### PR DESCRIPTION
**Pull request by njam**
- date
- date_time

cc @fvovan @tomaszdurka

### CODE REVIEW

**Comment by njam** [comment]
Based on https://github.com/cargomedia/cm/pull/2166

@fvovan please review

**Comment by fvovan** [comment]
lgtm

**Comment by njam** [comment]
As discussed, I think it's correct for *Intl*Date:

> This ID must be a valid identifier on ICUʼs database or an ID representing an explicit offset, such as GMT-05:30.
http://php.net/manual/en/intldateformatter.create.php

**Comment by tomaszdurka** [comment]
Why do we allow to pass a different timezone for the helper btw? Is there a use case you guys see you want to on this level change the timezone?

**Comment by njam** [comment]
Yes, for *local/physical* events. Imagine an event happening in Paris at 8pm. You'd want to render it in Paris' timezone, and not in the environment/viewer's timezone!

**Comment by tomaszdurka** [comment]
Yes, I thought about those Denkmal cases when seem this initially over the weekend.

I totally agree to this usage. Not sure if we should make timezone optional on `getDateFormatter` on `Render` though. Thought we should rather recreate instance in smarty helper (using locale, etc from Env). Probably overkill. Maybe if the `$timeZone` argument would be called `$timeZoneOverride` it would be bette :)

Anyway, dw, lgtm.

**Pull request merged**
