### PR TITLE
Use key phrases for pagination labels

### LINKED ISSUE #1551: Use dot-phrase for pagination
`.pagination.next` instead of `Next` etc.

Cc @nicolasschmutz @moby86 @christopheschwyzer

### PR DESCRIPTION
**Pull request by njam**
Closes #1551

@christopheschwyzer please review

### CODE REVIEW

**Comment by njam** [comment]
please wait with review

**Comment by njam** [comment]
@christopheschwyzer please review

@NicolasSchmutz @christopheschwyzer do you agree on these translations?
```php
if ($en = CM_Model_Language::findByAbbreviation('en')) {
    $en->setTranslation('.pagination.first', 'First');
    $en->setTranslation('.pagination.next', 'Next');
    $en->setTranslation('.pagination.previous', 'Previous');
    $en->setTranslation('.pagination.last', 'Last');
}

if ($de = CM_Model_Language::findByAbbreviation('de')) {
    $de->setTranslation('.pagination.first', 'Erste');
    $de->setTranslation('.pagination.next', 'Weiter');
    $de->setTranslation('.pagination.previous', 'Zurück');
    $de->setTranslation('.pagination.last', 'Letzte');
}
```

**Comment by NicolasSchmutz** [comment]
lgtm!

**Comment by christopheschwyzer** [comment]
lgtm

**Comment by njam** [comment]
@christopheschwyzer please review

**Comment by christopheschwyzer** [comment]
lgtm

**Pull request merged**
