### PR TITLE
Throw if S3 upload fails

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by fauvel** [comment]
@njam @tomaszdurka please review

**Comment by tomaszdurka** [comment]
If that's the only way to check then looks good.

- Can it still "fail" after copying the same amount of bytes? :panda_face: 
- What are `@` usages for closing the streams? Should we really ignore errors there?

**Comment by njam** [comment]
Let's be as strict as possible, so we should definitely check the return values of `fclose()` for example (and throw if there was a failure).

**Comment by fauvel** [comment]
Agree, please review!

**Comment by fauvel** [comment]
@ :panda_face: let's investigate which kind of issues we actually have first...

**Comment by njam** [comment]
Let's move this to a separate function! Otherwise lgtm.

**Comment by fauvel** [comment]
Agree, last review please!

**Comment by njam** [comment]
lgtm

**Pull request merged**
