### PR TITLE
FB-117 AWS SDK v3

### LINKED ISSUE #2547: Upgrade to AWS SDK PHP 3
Follow-up of #2512
See http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/migration.html

### PR DESCRIPTION
**Pull request by fauvel**
Closes #2547
Depends on https://github.com/cargomedia/puppet-cargomedia/pull/1798
Depends on https://github.com/cargomedia/puppet-packages/pull/1667

### CODE REVIEW

**Comment by fauvel** [comment]
@njam please also review the puppet changes!

**Comment by njam** [comment]
Did you acceptance test this? Especially `CM_File_Filesystem_Adapter_AwsS3`?

**Comment by fauvel** [comment]
Could you PM me with the credentials we're using for these tests?

**Comment by fauvel** [comment]
I'd need a list of production apps based on cm btw, so that I can prepare a cm upgrade in all of them as needed.

**Comment by fauvel** [comment]
@njam please review. I'm struggling with local acceptance tests, I will try again on a fresh new box.

**Comment by fauvel** [comment]
Tested locally, finally:) Everything's working fine in acceptance tests!

**Comment by njam** [comment]
@alexispeter could you review?

**Comment by fauvel** [comment]
FYI I've made the acceptance tests using the test-dev-usercontent bucket in our AWS playground. Let me know if you need the credentials!

**Comment by alexispeter** [comment]
Btw, is this even still in use? For the life of me, I cannot find any usages besides the tests.

**Comment by fauvel** [comment]
Tagged 1.239.0

**Pull request merged**
