### PR TITLE
Adjust Select2 fix

### PR DESCRIPTION
**Pull request by christopheschwyzer**
Follow-up https://github.com/cargomedia/cm/pull/2445

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
When I think about it. Not even sure this makes sense. Maybe original fix was better after all. @njam please reopen should you disagree.

**Comment by njam** [comment]
Ah, I thought we would move *all* select2 related styles to a separate stylesheet.
This seems reasonable because we also want to style select2 on the page if it is *not* inside a Suggest formfield.
wdyt?

**Comment by christopheschwyzer** [comment]
I think this is the case already. In `Suggest/default.less` there are only styles directly related to the _Suggest_ form field. Or am I missing something?

**Comment by njam** [comment]
As discussed: let's move it to a global `select2.less` and rename the relevant classes from `.suggestItem-something` to for example `.select2-item-something`.

**Comment by christopheschwyzer** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
