### PR TITLE
Add StateMachine js vendor lib

### PR DESCRIPTION
**Pull request by zazabe**
Add [StateMachine v2.3.5](https://github.com/jakesgordon/javascript-state-machine) to vendor lib.

### CODE REVIEW

**Comment by zazabe** [comment]
@vogdb please review ;)
@njam fyi

required for cargomedia/sk#2421

**Comment by vogdb** [comment]
lgtm

**Comment by njam** [comment]
We *could* have added it just in SK. But it's small anyway…

@tomaszdurka THE RETURN OF THE STATEMACHINE!

**Comment by tomaszdurka** [comment]
:)

**Pull request merged**
