### PR TITLE
New feature detections to Modernizr.

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by zazabe** [comment]
WebGL detection is not working well with the Modernizr method, please check this implementation with the three.js method: d97201f

**Comment by zazabe** [comment]
@vogdb if you agree, please cherry-pick my changes

**Comment by vogdb** [comment]
@zazabe you have generated `modernizr.js` from the latest master. I'm not sure about its stability.

**Comment by zazabe** [comment]
@vogdb yes, but there's no instruction about which version to use, i added a `README.md`. Thinking also about doing a PR on Modernizr for WebGL, the current official test doesn't work in all cases.

**Comment by vogdb** [comment]
lgtm here but lets wait a bit for Modernizr/Modernizr#1784

**Pull request merged**
