### PR TITLE
Remove some code smells

### PR DESCRIPTION
**Pull request by mariansollmann**

### CODE REVIEW

**Comment by mariansollmann** [comment]
@njam shouldn't we use `javascript:void(0)` instead of `javascript:;`?  http://stackoverflow.com/questions/134845/href-attribute-for-javascript-links-or-javascriptvoid0

@christopheschwyzer 
- /CM/layout/default/css/form.less line 278: shouldn't @sizeSwitch be assigned with `:` instead of `=`?
- we never introduce LESS variable `@breakpointSmall` is this on purpose?

**Comment by njam** [comment]
> shouldn't we use `javascript:void(0)` instead of `javascript:;` in html-tag-a-href?  http://stackoverflow.com/questions/134845/href-attribute-for-javascript-links-or-javascriptvoid0

On that stackoverflow page somebody says `javascript:;` might not work in old IE version. And some people propose to prefer `javascript:;` over `javascript:void(0)`.
I don't think we need to worry about those old IE versions. Is there another reason why you want to change it

**Comment by mariansollmann** [comment]
@njam no real other reason. Just the IDE dont like `javascript:;`

**Comment by njam** [comment]
True it doesn't like the "unnecessary ;". Not sure whether it would work without.
I would suggest to keep it as is to avoid problems in some browsers?

**Comment by mariansollmann** [comment]
agree.

**Comment by christopheschwyzer** [comment]
- in `layout/default/FormField/File/default.less` is the `font-familly` even necessary? Can be default font AFAIK.

- `form.less`: `@sizeSwitch =  @sizeCheckbox + 4px;` assignment with ":" instead "="

**Comment by mariansollmann** [comment]
@njam please review.

**Comment by njam** [comment]
@alexispeter could you review this?

**Comment by alexispeter** [comment]
* CM_Model_StorageAdapter_Cache::_generateId() is this method needed?I can't find it anywhere in the class hierarchy, maybe legacy code? Could you investigate and remove it completely if appropriate?

rest looks good
I assume you had css checked

**Comment by alexispeter** [comment]
talked about it quickly with @njam, you can remove _generateId() and throw the exception in create()

**Comment by christopheschwyzer** [comment]
`less / css` is fine

**Comment by mariansollmann** [comment]
@alexispeter please review.

**Comment by alexispeter** [comment]
lgtm

**Pull request merged**
