### PR TITLE
Check performance of mongodb queries to retrieve logs in admin II

### PR DESCRIPTION
**Pull request by fvovan**
Was addressed before in: https://github.com/cargomedia/cm/pull/2160

Loading the *error log page* (`/log?level=400`) still regularly takes a long time and often times out.

```
MongoCursorTimeoutException: www3.example.com:27017: Read timed out after reading 0 bytes, waited for 30.000000 seconds in /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/PagingSource/MongoDb.php on line 89
0. {main} at /home/example/serve/public/index.php line 0
1. CM_Http_Handler->processRequest(CM_Http_Request_Get) at /home/example/releases/20160623140811/public/index.php line 8
2. CM_Http_Response_Abstract->process() at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Http/Handler.php line 27
3. CM_Http_Response_Page->_process() at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Http/Response/Abstract.php line 50
4. CM_Http_Response_Page->_processContentOrRedirect() at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Http/Response/Page.php line 72
5. CM_Http_Response_Page->_processPageLoop(CM_Http_Request_Get) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Http/Response/Page.php line 90
6. CM_Http_Response_Page->_processPage(CM_Http_Request_Get, CM_Http_Response_Page_ProcessingResult) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Http/Response/Page.php line 103
7. CM_Http_Response_Abstract->_runWithCatching(Closure, Closure) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Http/Response/Page.php line 155
8. CM_Http_Response_Page->{closure}() at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Http/Response/Abstract.php line 275
9. CM_Http_Response_Page->_renderPage(Admin_Page_Log) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Http/Response/Page.php line 146
10. CM_RenderAdapter_Layout->fetch() at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Http/Response/Page.php line 66
11. CM_Frontend_Render->fetchViewResponse(CM_Frontend_ViewResponse) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/RenderAdapter/Layout.php line 70
12. CM_Frontend_Render->fetchViewTemplate(Admin_Layout_Default, 'default', []) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Frontend/Render.php line 473
13. CM_Frontend_Render->fetchTemplate('library/Admin/layout/default/L...', [], []) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Frontend/Render.php line 465
14. Smarty_Internal_TemplateBase->fetch() at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Frontend/Render.php line 85
15. content_576bee46981405_66285246(Smarty_Internal_Template) at /home/example/releases/20160623140811/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php line 182
16. CM_RenderAdapter_Layout->fetchPage() at /home/example/releases/20160623140811/tmp/smarty/Admin_Layout_Default_101_en^1946f6863e8a0574cb2fbab7c83b6bd9af318bc3.file.default.tpl.php line 53
17. CM_RenderAdapter_Component->fetch() at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/RenderAdapter/Layout.php line 81
18. CM_Frontend_Render->fetchViewResponse(CM_Frontend_ViewResponse) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/RenderAdapter/Component.php line 23
19. CM_Frontend_Render->fetchViewTemplate(Admin_Page_Log, 'default', []) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Frontend/Render.php line 473
20. CM_Frontend_Render->fetchTemplate('library/Admin/layout/default/P...', [], []) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Frontend/Render.php line 465
21. Smarty_Internal_TemplateBase->fetch() at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Frontend/Render.php line 85
22. content_576bee52047b31_17914791(Smarty_Internal_Template) at /home/example/releases/20160623140811/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php line 182
23. smarty_function_component([], Smarty_Internal_Template) at /home/example/releases/20160623140811/tmp/smarty/Admin_Page_Log_101_en^85241a3f18d0140bfea68fa3f940f3514abeafab.file.default.tpl.php line 44
24. CM_RenderAdapter_Component->fetch() at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/SmartyPlugins/function.component.php line 21
25. CM_Frontend_Render->fetchViewResponse(CM_Frontend_ViewResponse) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/RenderAdapter/Component.php line 23
26. CM_Frontend_Render->fetchViewTemplate(Admin_Component_LogList, 'default', []) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Frontend/Render.php line 473
27. CM_Frontend_Render->fetchTemplate('vendor/cargomedia/cm/layout/de...', [], []) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Frontend/Render.php line 465
28. Smarty_Internal_TemplateBase->fetch() at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Frontend/Render.php line 85
29. content_576bee5236fd93_70368084(Smarty_Internal_Template) at /home/example/releases/20160623140811/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php line 182
30. CM_Paging_Abstract->rewind() at /home/example/releases/20160623140811/tmp/smarty/Admin_Component_LogList_101_en^cdd46377373a65d5f43337183e6200ad3f0689f2.file.default.tpl.php line 82
31. CM_Paging_Abstract->getItems() at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Paging/Abstract.php line 485
32. CM_Paging_Abstract->_getItemsRaw() at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Paging/Abstract.php line 31
33. CM_PagingSource_MongoDb->getItems(0, 51) at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/Paging/Abstract.php line 362
34. MongoCursor->rewind() at /home/example/releases/20160623140811/vendor/cargomedia/cm/library/CM/PagingSource/MongoDb.php line 89
```

@fvovan @tomaszdurka could you have a look?
cc @alexispeter

### CODE REVIEW

**Comment by fvovan** [comment]
The majority of incidents are 'all' listings or 'unknown' ones (ie. request has 'ajax' url). 
I did  one improvement but i'm afraid it will not help a lot. And increasing timeOut like we did for records removing is probably not we should do now.
The problem is dev. environment mongodb is not sharded, so it's harder to reproduce. On dev all queries hit the index and the longest query for 1.5M records is only 4-6 secs. (when selecting and sorting all of them)
It could be a consequence of current server load (according out logs the problem appeared 13-06). Did anything significant happen?
We can try using "ReadPreference"  to decrease the load, not sure if we use it anywhere now?
@njam wdyt?

**Comment by njam** [comment]
afaik collections are not sharded by default, but this is enabled specifically for the `sk_conversation` collection, see [schema.pp](https://github.com/cargomedia/puppet-cargomedia/blob/master/modules/sk/manifests/mongodb/schema.pp#L47).

I find it strange that this should take more than 30 seconds on the production database.
Is there any other query that could somehow block this find query?

**Comment by fvovan** [comment]
>Is there any other query that could somehow block this find query?

Unfortunately yes. mongo 2.6 is really poor in concurrency aspect. It uses db level locks. and 
>However, when a write lock exists, a single write operation holds the lock exclusively, and no other read or write operations may share the lock.
Locks are “writer greedy,” which means write locks have preference over reads. When both a read and write are waiting for a lock, MongoDB grants the lock to the write.

so I understand each write operation matters.

we can check it using `db.currentOp({"waitingForLock" : true})` command
probably it would be good to pair with somebody with console permission and check it

**Comment by njam** [comment]
We use the default value of `slowOpThresholdMs` which is 100ms. When I check for such queries I can only find queries against `sk_conversation`:
```
db.system.profile.find( { millis : { $gt : 100 } } )
```

We keep track of the count and time of slow queries with bipbip. But no anomaly is visible for the 1 month graph:
screen shot 2016-06-28 at 08 50 24

And this is the report from New Relic from the last 7 days:
screen shot 2016-06-28 at 08 51 31

Even the "remove" is fast, maximum 232ms.

The queries that take longer, even reach the limit (30s) are "findone":
screen shot 2016-06-28 at 08 53 14


The issue might be that our indices don't fit into RAM (anymore).
See https://github.com/cargomedia/puppet-cargomedia/issues/1271

Please close if you agree.

**Comment by fvovan** [comment]
>The issue might be that our indices don't fit into RAM (anymore).

I checked www4 in copperegg yesterday, and it has free memory

**Comment by njam** [comment]
Isn't the memory needed on the *shard* (rep1-db4 for example)?
The shard is using the memory completely:
screen shot 2016-06-28 at 09 30 58

(see also http://blog.mongodb.org/post/101911655/mongo-db-memory-usage)

**Comment by fvovan** [comment]
yes. agree!

**Pull request closed without merging**
