### PR TITLE
Click Feedback. Reopened.

### PR DESCRIPTION
**Pull request by vogdb**
Replaces https://github.com/cargomedia/CM/pull/1795

Open issues: 
- [x] Click events get's intercepted (e.g. by clickDecorators), `mousedown` gets intercepted by _fastClick_
- [x] clickConfirm animation doesn't work on Android 4 (somehow resolved)
- [x] Remove `:hover` from `function.link.less`
- [x] Remove all `:hover` ?!
- [x] Try `<meta name="msapplication-tap-highlight" content="no" />` to disable tap highlighting on Windows Phones
- [x] FF issue (Normal links don't work anymore)

### CODE REVIEW

**Comment by vogdb** [comment]
@christopheschwyzer FYI

**Comment by vogdb** [comment]
Just a formality. @christopheschwyzer please test when you have time.

**Comment by christopheschwyzer** [comment]
There are some open issues. See updated description.

**Comment by vogdb** [comment]
ok. thanks!

**Comment by vogdb** [comment]
If we put the heavy animation inside a postponed execution then the Firefox problem will go away but I'm not sure about correctness of such solution.
```js
      setTimeout(function() {
        $elem.append($feedback);
        $feedback.transition({
          scale: 1
        }, '200ms', 'in').transition({
          opacity: 0
        }, '200ms', 'out', function() {
          $feedback.remove();
        });
      }, 100);
```

**Comment by vogdb** [comment]
Note to myself. It's just crazy. Can't fix it quickly. Possible try another implementation of ripple effect?

**Comment by fabianfrey** [comment]
You can do it! I believe in you :)

Am Donnerstag, 25. Juni 2015 schrieb Alex :

> Note to myself. It's just crazy. Can't fix it quickly. Possible try
> another implementation of ripple effect?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cargomedia/CM/pull/1815#issuecomment-115360165>.
>


-- 

cargo media AG

www.cargomedia.ch

email: ff@cargomedia.ch

phone: +41 78 820 14 82

**Comment by christopheschwyzer** [comment]
confirmClick animation doesn't work on some Android Browsers. I can't really determine which ones, as Browserstack doesn't show information about the used browser. I tested it on Android 4.1 Stock browser on the actual device (Nexus 4) and there it worked. I suggest to ignore this as it only affects a small amount of users, plus, functionality wise everything works as expected.

**Comment by christopheschwyzer** [comment]
@vogdb please review
There is only one open issue left (see description) - can you test it as well - otherwise we can do it in a separate issue as well.

**Comment by vogdb** [comment]
ok, lgtm

**Comment by vogdb** [comment]
Actually this comment should be here. What about a hover rule at `cm/layout/default/css/layout.less`:

```less
a:hover, a:active {
  text-decoration: none;
}
```

**Comment by christopheschwyzer** [comment]
@vogdb you're right. I thought this _reset_ was necessary - turns out - it's not ;) please verify. Btw. Windows Phone tap feedback is disabled, right?

**Comment by vogdb** [comment]
lgtm. Windows feedback is disabled on my 8.0 and browserstack devices.

**Pull request merged**
