### PR TITLE
Refactor New Relic logger

### PR DESCRIPTION
**Pull request by fauvel**
Implement as a `CM_Log_Handler_Abstract`

### CODE REVIEW

**Comment by fauvel** [comment]
@fvovan please review

**Comment by fauvel** [comment]
@fvovan I've added the service configuration, which relies on https://github.com/cargomedia/cm/pull/2081.

**Comment by fauvel** [comment]
@fvovan I've simplified the code as discussed. It now depends on the refactoring of `CM_Log_Record_Exception::getException` and `CM_Log_Record_Exception::getExceptionSerializable`, to be done in https://github.com/cargomedia/cm/pull/2081.

**Comment by fvovan** [comment]
it's merged to https://github.com/cargomedia/cm/pull/2081/

**Pull request closed without merging**
