### PR TITLE
FB-292 Use div[contenteditable] for textarea form-field

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
Cool. Copy/past works fine. 

Small things I noticed:
- The textarea size was too large (fixed - see last commit)
- The cursor position in Edge on focus shows up after the placeholder. (I tried to fix it by setting the pseudo element to _absolute_ - But caused other carret positioning issues in FF. 
- This branch has conflicts with the base branch

Otherwise lgtm.

**Comment by christopheschwyzer** [comment]
Edge:

file

**Comment by christopheschwyzer** [comment]
Found a solution. See last commit.

**Comment by njam** [comment]
Nice!

**Comment by christopheschwyzer** [comment]
@{c7e8ab9c-90bf-4796-bb88-9aa7c8150044,Reto Kaiser} I think it's good. Let me know when you have a minute to release this.

**Comment by njam** [comment]
@{b8eaa54c-4c7d-4289-a16b-3c527f41ba9a,Christophe Schwyzer} could you release it without me, and verify it? Thanks!

**Pull request merged**
