### PR TITLE
don't clear cache on time-reset in tests

### PR DESCRIPTION
**Pull request by alexispeter**
In order to have more control over tests related to cache-clearing.

### CODE REVIEW

**Comment by njam** [comment]
lgtm

**Comment by alexispeter** [comment]
TH::timeForward() actually clears caches as well. 
@njam do you remember if there is a specific reason for this?

**Comment by njam** [comment]
I don't remember. Agree it seems strange.
If everything works without this, I'd say it's good!

**Comment by alexispeter** [comment]
Will investigate if any tests in our projects are relying on timeForward() clearing cache.

**Comment by njam** [comment]
@alexispeter status?

**Comment by alexispeter** [comment]
On hold until I have some spare time. I imagine this is going to break a lot of tests.

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
lgtm

**Pull request merged**
