### PR TITLE
make CM_Model_StreamChannelArchive_Media::file optional

### PR DESCRIPTION
**Pull request by fvovan**

### CODE REVIEW

**Comment by fvovan** [comment]
for https://github.com/cargomedia/sk/issues/2582

**Comment by fvovan** [comment]
@njam please review

**Comment by njam** [comment]
- CM/Model/StreamChannelArchive/Media.php: Usually we tend to make getters fail if the value is unavailable. I think we can cover the use cases with `hasFile()`?
 - Adjust CM/Model/StreamChannelArchive/MediaTest.php accordingly

**Comment by fvovan** [comment]
is it okay to use only `_get()` results check inside getter?
seems a little bit odd to use `hasFile()` there and then enclose all calls to `hasFile` again

**Comment by njam** [comment]
agree, lgtm

**Pull request merged**
