### PR TITLE
Upgrade composer to alpha10

### PR DESCRIPTION
**Pull request by njam**
cc @dlondero @tomaszdurka

### CODE REVIEW

**Comment by njam** [comment]
@tomaszdurka please review

`Composer\Config::get('vendor-dir')` now returns an absolute path by default (based on a `$baseDir` you pass to its constructor).
I've opted to retrieve the relative path nonetheless (using a flag) to keep our code mostly untouched.

**Comment by tomaszdurka** [comment]
So there is a flag so config returns relative paths? Ok.
What about making `createComposer`'s `$baseDir` non optional?

**Comment by njam** [comment]
agree, please double check!

**Comment by tomaszdurka** [comment]
Looks good!

**Comment by njam** [comment]
Tagged 1.133.1

**Pull request merged**
