### PR TITLE
Promise behaviour of Form.submit()

### PR DESCRIPTION
**Pull request by vogdb**
`CM_Form_Abstract.submit()` returns a Promise which behaves like this:
- Client side validation errors: resolve
- Server side validation errors: resolve
- Successful submit: resolve

Why do we not reject on validation errors?
I have a usage where I submit a form directly and use the returned Promise to control the further control flow. In that case I would expect that the promise only resolves on successful submit. 
wdyt?

### CODE REVIEW

**Comment by vogdb** [comment]
@njam smth like this ? Don't know what to do with them, once we caught them on the click level.

**Comment by njam** [comment]
- Don't we call `handler.trigger()` twice now?
- Didn't we remove `cm.error.create` - just use `throw new CM_Exception('Form validation failed')`?
- Maybe introduce a specific error `CM_Exception_FormFieldValidation`, and *only* catch that in the click case?
 - Just add a one-line comment into the catch that the `submit()` already handles and displays errors?

**Comment by vogdb** [comment]
> - Didn't we remove `cm.error.create` - just use `throw new CM_Exception('Form validation failed')`?

Yes, we did but this issue is not yet merged, so I can't use CM_Exception.

> - Maybe introduce a specific error `CM_Exception_FormFieldValidation`, and *only* catch that in the click case?

Yes but only after CM_Exception is introduced.

>  - Just add a one-line comment into the catch that the `submit()` already handles and displays errors?

ok.

**Comment by njam** [comment]
ok let's wait for https://github.com/cargomedia/CM/pull/1832

**Comment by vogdb** [comment]
@njam wdyt now ?

**Comment by njam** [comment]
- CM_Exception_FormFieldValidation: Should the constructor then accept an `errorList` array argument?
- CM/Form/Abstract.js: Add space after `//` in comment

**Comment by vogdb** [comment]
> - CM_Exception_FormFieldValidation: Should the constructor then accept an `errorList` array argument?

Not needed. CM_Exception_FormFieldValidation <= CM_Exception <= Error. So the `errorList->toString()` will be called to set the message of Error. For now it's fine.

**Comment by vogdb** [comment]
btw @njam please review.

**Comment by njam** [comment]
ok, lgtm

**Pull request merged**
