### PR TITLE
Track banner impressions and clicks with GA events

### PR DESCRIPTION
**Pull request by njam**
Depends on https://github.com/cargomedia/CM/pull/1613

This will allow us to continuously monitor ad impressions and CTR, and segment by device, geo, gender etc in GA.
(Click tracking will only work for image banners.)

Event parameters:
- **Category, Action, Label**
- 'Banner', 'Click', '[zone-id]'
- 'Banner', 'Click', '[zone-id]'

See:
- http://www.statstory.com/tracking-clicks-and-impressions-in-google-analytics/
- http://www.opensidedigital.com/how-track-outbound-links-google-analytics

cc @moby86 @j-dalrymple @fauvel

### CODE REVIEW

**Comment by njam** [comment]
@vogdb wanna review this?
Most of it comes from another PR, it's just one commit: f2d3d80751ffe053dc35ba5f02431abea0fa8b76

Docu about GA client API is here: https://developers.google.com/analytics/devguides/collection/analyticsjs/events

**Comment by vogdb** [comment]
ok

**Comment by vogdb** [comment]
Ok. The code is ok but it can't detect click/touch events on iframe ads. If clicks are solvable by something like this http://stackoverflow.com/a/8101458/495656 then touches are mystery to me. Thinking/searhing now.

**Comment by njam** [comment]
@vogdb yes, I don't think it's possible (reliably) :/ - have a look here: https://github.com/cargomedia/media-sales/issues/24

**Comment by vogdb** [comment]
Can we disable iframe ads?

**Comment by njam** [comment]
Unfortunately not, most advertisers use them...

**Comment by vogdb** [comment]
then lgtm.

**Comment by njam** [comment]
@vogdb please check again (merged)

**Comment by vogdb** [comment]
lgtm

**Comment by njam** [comment]
@fauvel please check as well once you're feeling better

**Comment by fauvel** [comment]
Normally you would disable event bubbling and use `hitCallback` to go to the ad page after the tracking is complete: https://support.google.com/analytics/answer/1136920?hl=en

**Comment by njam** [comment]
Makes sense.
Since all our banners open in a new tab/window it shouldn't make a difference atm.

**Pull request merged**
