### PR TITLE
Kickbox timeout: Error severity?

### PR DESCRIPTION
**Pull request by fauvel**
Followup of https://github.com/cargomedia/cm/pull/1858

Timeouts are showing up in the error log, should they be warnings?

### CODE REVIEW

**Comment by fauvel** [comment]
@njam makes sense, please review!

**Comment by njam** [comment]
Hm it's actually not a `CM_Exception`:
```
RuntimeException: [curl] 7: Failed connect to api.kickbox.io:443; Connection timed out [url] https://api.kickbox.io/v1/verify?email=example%40gmail.com in /home/example/releases/20150727075712/vendor/kickbox/kickbox/lib/Kickbox/HttpClient/HttpClient.php on line 119 
```

Would be good to:
- Be restrictive - only do this for timeout errors
- Convert to CM_Exception which has *severity* (rethrow)

**Comment by fauvel** [comment]
Oops sorry. It's not straight-forward to be restrictive (see https://github.com/guzzle/guzzle/issues/1006), so I'll parse the error message.

**Comment by fauvel** [comment]
Makes sense, please review again! FYI you can find a list of cURL error codes [here](http://curl.haxx.se/libcurl/c/libcurl-errors.html).

**Comment by njam** [comment]
lgtm

**Pull request merged**
