### PR TITLE
Add TTL to the Adagnit tracking queue

### PR DESCRIPTION
**Pull request by fauvel**
Based on #1819

### CODE REVIEW

**Comment by fauvel** [comment]
@njam please review

**Comment by njam** [comment]
- CMService/Adagnit/Client.php: Constructor: docu
- CMService/Adagnit/Client.php: Add a function to add items to queue? With parameter $eventType and $data
- CMService/Adagnit/Client.php: Now we set the TTL when *getting* the queue and again when adding items to the queue. Is that needed?
- CMService/Adagnit/Client.php: IMO we can set a good default as TTL (24h?) and not make this configurable? I don't think it makes sense to change this ever?

**Comment by fauvel** [comment]
> Now we set the TTL when getting the queue and again when adding items to the queue. Is that needed?

No, I've just forgotten to remove the code from the queue getter.

> IMO we can set a good default as TTL (24h?) and not make this configurable? I don't think it makes sense to change this ever?

As for all other caching instances, it definitely makes sense to make the ttl configurable imo. You would choose different values for different apps running with a different load and on a different infrastructure – the framework must adapt to the available resources, not the other way round.

**Comment by njam** [comment]
- CM/Redis/Client.php: Remove docu comment about expiration (this function handles *any* type of keys)

>  it definitely makes sense to make the ttl configurable imo.

Agree.
Rest looks good.

**Comment by fauvel** [comment]
@njam last review please...

**Comment by njam** [comment]
lgtm

**Comment by fauvel** [comment]
Tagged 1.127.3

**Pull request merged**
