### PR TITLE
File upload adjustments

### PR DESCRIPTION
**Pull request by christopheschwyzer**
- Change label for PhotoUpload to "Upload Photo"
- Get rid of previews? Or add flag to skip previews.
- Add spinner to button?

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@njam wdyt? please review/assign

**Comment by christopheschwyzer** [comment]
One more thought. Maybe we should allow to pass the "button theme"…

**Comment by christopheschwyzer** [comment]
Ok added

**Comment by njam** [comment]
@fauvel please review

**Pull request merged**
