### PR TITLE
improved phpunit-assertions for model-class

### PR DESCRIPTION
**Pull request by alexispeter**
Improves the display of failed equality-assertions between model-classes.

`Failed asserting that SK_User(197) matches expected SK_User(196).`

Also works for arrays, making debugging pagings etc much easier.
image

Sideeffects: Instances of CM_Comparable cannot be compared with assertEquals() anymore without requiring the instance to actually be the same.

### CODE REVIEW

**Comment by njam** [comment]
Couldn't we have a comparator that accepts `CM_Comparable`?

**Comment by alexispeter** [comment]
We could.

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
Nice!

- Comparator/Comparable.php: assertEquals: Update "model" reference
- CMTest/Exporter.php: Would it make sense to use `CM_Debug_VariableInspector::getDebugInfo()`?

**Comment by alexispeter** [comment]
> CMTest/Exporter.php: Would it make sense to use `CM_Debug_VariableInspector::getDebugInfo()`?

That depends on the extent you want to use it. It could make sense to use it for objects implementing `CM_Debug_DebugInfoInterface`. But I'm not comfortable with blindly using it for anything, and making sure it doesn't break anything would be way too much effort for too little benefit.

**Comment by njam** [comment]
ok, let's not use it then.

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
ok, let's use it then ;)

lgtm

**Comment by alexispeter** [comment]
I meant it would be good to use it for objects that use the interface, just not as a general dumper for everything ;)

**Pull request merged**
