### PR TITLE
Add enable/disable feature to toggleModal

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@njam please review

**Comment by njam** [comment]
So it will disable the fully toggling (enabling and disabling). Can you show me the usecase?

**Comment by zazabe** [comment]
on cargomedia/sk#3019, to lock the panel. 

it can't be done in `ToggleModal` callback, because the state could be changed by `ModalClose` and the next "close" command will not execute the callback, so something like this will not work:

```
$el.toggleModal('open', function(state) {
  if(isEnabled) {
    $el.toggleClass('panel--active', state);
  }
});
```

**Comment by njam** [comment]
Ok makes sense, lgtm.

**Pull request merged**
