### PR TITLE
Location formField's "detectLocation" doesn't work

### PR DESCRIPTION
**Pull request by vogdb**
Due to Promises for ajax?

The formField `CM_FormField_Location` has a button "Get current location". It doesn't work anymore. You can test it for example on the "example" or "search" page.

@vogdb can you check?

### CODE REVIEW

**Comment by vogdb** [comment]
Yes! @njam or @tomaszdurka please review.

**Comment by njam** [comment]
- _lookupCoordinates: Adjust docu
- detectLocation: Add docu
- detectLocation: Why are you wrapping `navigator.geolocation.getCurrentPosition()` into a new Promise? Couldn't we just use the result of that function?
- detectLocation: Let's stick to a convention regarding indentation of "then/catch/finally"? I would suggest to put them each onto a new line:
```js
getPromise()
.then(function(){
 //
})
.catch(function(){
 //
})
```
wdyt?

**Comment by vogdb** [comment]
> - detectLocation: Why are you wrapping `navigator.geolocation.getCurrentPosition()` into a new Promise? Couldn't we just use the result of that function?

Honestly I can't think of a way to do it. Please share your solution.

**Comment by vogdb** [comment]
@njam please look.

**Comment by njam** [comment]
lgtm!

Might there be other cases like this? Did you search for "Deferred"?

**Comment by vogdb** [comment]
good point. Can I use this PR for them?

**Pull request merged**
