### PR TITLE
add 'needed' param to smarty.load

### PR DESCRIPTION
**Pull request by fvovan**

### CODE REVIEW

**Comment by fvovan** [comment]
@alexispeter please review

**Comment by alexispeter** [comment]
* library/CM/SmartyPlugins/function.load.php
 + test the returnValue of getLayoutPath() for null, instead of `$file` which might mean something else.
* tests/library/CM/SmartyPlugins/function.load.php fileName needs to end with Test, else the test-runner will ignore it.

**Comment by fvovan** [comment]
oh. bad me :( . need to stop pushing after 18-00.
thanks @alexispeter.
could you look check  it please?

**Comment by alexispeter** [comment]
lgtm

**Pull request merged**
