### PR TITLE
Epom Adprovider

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@njam please review.

**Comment by njam** [comment]
@vogdb let's pair-finish this? lmk when you have time!

**Comment by kris-lab** [comment]
look good to me!

**Comment by njam** [comment]
Few notes:
- What is `key`, shouldn't this be configurable?
- Add a test
- Maybe use `CM_Params::jsonEncode()` (which has error checking)?

**Comment by vogdb** [comment]
> - What is `key`, shouldn't this be configurable?
 - Add a test
 - Maybe use `CM_Params::jsonEncode()` (which has error checking)?

We are just testing a new provider. So, I decided not to be so perfect here. There is a big chance that we throw this code away, isn't it ?

**Comment by kris-lab** [comment]
@njam I agree on all point but what is the chance that we could stick to this provider? Do we have another options?

**Comment by njam** [comment]
Agree that this is code which might not live long, and we shouldn't invest too much time in making it shiny.

But making the `key` configurable is really just *deleting a line of code*, so not really more effort.
Regarding the test it would be a *bit* more effort to implement, but then again less to review (as you know the code runs and works)!

**Pull request merged**
