### PR TITLE
Send app releaseStamp on every ajax request

### PR DESCRIPTION
**Pull request by alexispeter**
server-part of https://github.com/cargomedia/CM/issues/1813

### CODE REVIEW

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
Some tests need to be adjusted

@vogdb wanna have a look too, does this serve the purpose?

**Comment by alexispeter** [comment]
please review @njam

**Comment by vogdb** [comment]
I did a checkout and verified on a working dev. Works fine.

**Comment by njam** [comment]
lgtm

**Comment by alexispeter** [comment]
tagged https://github.com/cargomedia/CM/releases/tag/1.131.2

**Pull request merged**
