### PR TITLE
Allow to put JS file in service library

### PR DESCRIPTION
**Pull request by zazabe**
Useful for example if a service define some models that should be exposed on the client side.

@njam wdyt?

### CODE REVIEW

**Comment by zazabe** [comment]
@njam please review

**Comment by njam** [comment]
I'm wondering if this should not be default for `rglobLibraries()` to include "XService" files? There's no real difference between "X" and "XService" from this point of view, it's just to structure the files.

**Comment by zazabe** [comment]
so `CM_Util::getModulePath($moduleName) . 'library/*/';` maybe?

**Comment by zazabe** [comment]
@njam please check again

**Comment by njam** [comment]
lgtm

**Pull request merged**
