### PR TITLE
Upgrade vagrant box to Debian 8

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@kris-lab fyi

5 tests are failing

**Comment by njam** [comment]
Depends on https://github.com/cargomedia/puppet-packages/pull/1452

**Comment by njam** [comment]
@fvovan @fauvel please review

Formatting a short date-time with PHP's "intl" extension depends on the ICU version used:
- Version 48 (Travis, Debian 7): 5/21/16 2:00 AM
- Version 52 (Debian 8): 5/21/16, 2:00 AM

I added an `if` to affected unit tests. Hopefully we can remove it in the future once all relevant environments run ICU 52. wdyt?

**Comment by fvovan** [comment]
Needed pattern could be defined as 3rd argument of `getFormatterDate()`. But as a temporary solution it's okay too.
btw did you delete php_storm tunnel setting because tests use vagrant remote interpreter?

**Comment by njam** [comment]
The *pattern* depends on the locale. E.g. in Arabic the pattern looks quite different than in English. If we would hardcode the pattern we would need to do it for every locale…

> btw did you delete php_storm tunnel setting because tests use vagrant remote interpreter?

Yes

**Comment by fvovan** [comment]
I meant not using it everywhere but passing the pattern to 
`$formatter = $render->getFormatterDate(IntlDateFormatter::SHORT, IntlDateFormatter::SHORT);`
lines in these broken tests only.

**Comment by fvovan** [comment]
lgtm

**Comment by kris-lab** [comment]
@njam out of curiosity, why it didn't fail during SK build in SK box?

**Comment by njam** [comment]
These are CM's unit tests that were failing, they are not executed when running SK's unit tests.

**Comment by fauvel** [comment]
lgtm - interesting, this approach to tweak unit tests depending on the icu version. I remember we would have needed it in another place (money formatting). Keeping it in mind!

**Pull request merged**
