### PR TITLE
Test on php7

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by fauvel** [comment]
@njam feels like [donating to Dmitry](https://github.com/zenovich/runkit/issues/87#issuecomment-146682396)?

**Comment by njam** [comment]
Let's upgrade Debian first! :)

**Comment by fauvel** [comment]
I've seen php7-rc2 has been packaged for deb8, but probably we'll have to wait for deb9 for full php7 support? ETA 1-2y...

**Comment by fauvel** [comment]
Not nice for open source projects built on top of cm :/

**Comment by njam** [comment]
Maybe instead we should drop runkit usage? :)
The only thing it's needed for I think is:
```
runkit_function_copy('time', 'time_original');
```

**Comment by fauvel** [comment]
Yep, maybe we could use a `CM_Util_Time` class for that, with a getter and a setter to "freeze" time in `CM_Bootloader_Testing`?

**Comment by njam** [comment]
There's timecop: https://github.com/hnw/php-timecop
Unfortunately also only 5.5…

**Comment by fauvel** [comment]
It looks like the simplest *reliable* way to achieve time freezing in unit tests would be to intercept the system calls made by the phpunit process – see for instance the [faketime](https://github.com/wolfcw/libfaketime) utility. Otherwise you must either write a php extension to override the time functions (and there are a lot of them), or write your own userspace wrapper class/function to mock time functions – and adjust all usages in your code (which you obviously cannot do easily for 3rd-party dependencies.)

**Comment by njam** [comment]
*libfaketime* sounds like a good solution! As it would also work for `new DateTime()`…
Let's look into this 2016 though, as it's not a priority currently!

**Comment by fauvel** [comment]
agree!

**Comment by njam** [comment]
@dlondero maybe also for you

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/cm/issues/2478

**Pull request closed without merging**
