### PR TITLE
Make static resource expiration configurable

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by fauvel** [comment]
@njam please review. Small question: Is it ok to set the default expiration to one year for `CM_Http_Response_Resource_RootProxy`, too?

**Comment by njam** [comment]
Pass it as `86400 * 365` for better readability?

RootProxy will be removed with https://github.com/cargomedia/cm/pull/2177

**Comment by fauvel** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Comment by fauvel** [comment]
Tagged 1.180.0

**Pull request merged**
