### PR TITLE
Disable foreign keys check in MySQL dump

### PR DESCRIPTION
**Pull request by zazabe**
To avoid error due to tables ordering / constraints

### CODE REVIEW

**Comment by zazabe** [comment]
@tomaszdurka please review

**Comment by zazabe** [comment]
The main reason to do that is described here: https://bugs.mysql.com/bug.php?id=16181

If there's a mistake in the SQL dump (ie. constraint with a non existing reference table), the dump will still be loaded with no errors (until the table is used)... but i'm not sure if we can really avoid that, see: http://stackoverflow.com/questions/3727905/check-for-referential-integrity-break

Anyway, if `structure.sql` files are always generated via cli, we should not have this problem...

**Comment by zazabe** [comment]
Note that without this change, using `bin/cm db db-to-file` in the app will generate a dump that can't be loaded with `CM_DB_DB::runDump()`

**Comment by tomaszdurka** [comment]
Yeah I get it all. I see that you also need to do some changes outside this method in order to support this "finally" concept i've proposed.

Let's drop the idea. We anyway load this dump when recreating application, meaning if this fails (and keeps foreign check in invalid state) we will run it again and fix it.

**Comment by zazabe** [comment]
@tomaszdurka mergeable?

**Comment by zazabe** [comment]
@tomaszdurka ?

**Comment by tomaszdurka** [comment]
Yes!

**Pull request merged**
