### PR TITLE
Allow to retrieve resource files from sameOrigin on client

### PR DESCRIPTION
**Pull request by njam**
Via https://github.com/cargomedia/CM/pull/1713

@vogdb @tomaszdurka please review

### CODE REVIEW

**Comment by njam** [comment]
..the JS implementations of `getUrlResource()` and `getUrlStatic()` are now exactly the same on the client as on the server (`CM_Frontend_Render`).

**Comment by vogdb** [comment]
lgtm.
I see that `getUrlStatic` didn't fit perfectly well into this situation =)

**Comment by njam** [comment]
Yes, I think the "sameOrigin" mode doesn't makes sense for `getUrlStatic` actually, I'm working on a better solution with yet another feature..

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/CM/pull/1717

**Pull request closed without merging**
