### PR TITLE
Add defaults to loadTypekit script

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@christopheschwyzer please review

**Comment by christopheschwyzer** [comment]
Shouldn't this be (only 2 arguments)?
```js
 config = _.defaults(config, {
    scriptTimeout: 3000,
    async: true
  });
```

http://underscorejs.org/#defaults

**Comment by vogdb** [comment]
Well, in case of two arguments, we will modify `config`. I thought it's not nice to modify it cause it can be used outside theoretically.

**Comment by christopheschwyzer** [comment]
Isn't `config` modified anyways here: `config = ` - Well, I'm no js dev - I don't understand this fully :) Seems to work, therefore lgtm.

**Comment by vogdb** [comment]
Well, you can play with this
```js
function modifiesArgument(argument) {
  _.defaults(argument, {hello: 'world'});
}
function immutableArgument(argument) {
  _.defaults({}, argument, {hello: 'world'});
}

var sample = {foo: 'bar'};

immutableArgument(sample);
console.log('After immutableArgument', sample);

modifiesArgument(sample);
console.log('After modifiesArgument', sample);
```

**Comment by christopheschwyzer** [comment]
I see. Thanks for the explanation :)

**Pull request merged**
