### PR TITLE
Make $.scrollTo($el) work with scrollables other than document

### PR DESCRIPTION
**Pull request by njam**
@vogdb please review

### CODE REVIEW

**Comment by vogdb** [comment]
ok. Should it work for a case when `target` is outside of `scrollable` ?

**Comment by njam** [comment]
I think that case should not be supported. Maybe we should throw?

**Comment by vogdb** [comment]
sgtm

**Comment by njam** [comment]
@vogdb please review

**Comment by vogdb** [comment]
lgtm. What about js docu?

**Comment by njam** [comment]
@vogdb you meant this? please review

**Comment by vogdb** [comment]
lgtm! :D

**Pull request merged**
