### PR TITLE
ClipSlide late call problem.

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@njam please review.

**Comment by njam** [comment]
- I'm not sure it's good to use *underscore* in jquery plugins like these. Especially for this small use case it might be preferable to reduce dependencies. wdyt?
- I trust you tested this and it works in Firefox?

**Comment by vogdb** [comment]
> - I'm not sure it's good to use *underscore* in jquery plugins like these. Especially for this small use case it might be preferable to reduce dependencies. wdyt?

Removed it.

> - I trust you tested this and it works in Firefox?

Nope but did it now. I can assure it wasn't only Firefox problem.

@njam please review.

**Comment by njam** [comment]
lgtm

**Pull request merged**
