### PR TITLE
Redesign FormFields

### PR DESCRIPTION
**Pull request by christopheschwyzer**
see: https://github.com/cargomedia/sk/issues/1902

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
I think it makes sense to split this issue into multiple issues. For now I did mostly refactoring, design adjustments. 

In a next step I'd like to look into: 
- Input masks for date input field: e.g. https://github.com/RobinHerbots/jquery.inputmask
- Different theme for radio buttons
- Textarea / autosize topic

**Comment by christopheschwyzer** [comment]
screen shot 2015-08-19 at 18 44 18
screen shot 2015-08-19 at 18 44 31
screen shot 2015-08-19 at 18 45 02

@seriff 1, 2 or 3?

**Comment by seriff** [comment]
I would go with number 1! but then if there a grey background it could be
tricky, so, number 3, could be a good compromise!

**Comment by christopheschwyzer** [comment]
screen shot 2015-08-20 at 09 57 27
No. 1 it is (Still works on grey background imo)

**Comment by christopheschwyzer** [comment]
@njam @vogdb please review
cc @tomaszdurka

**Comment by christopheschwyzer** [comment]
Ok to review

**Comment by seriff** [comment]
So, amen to the grey one!

**Comment by christopheschwyzer** [comment]
@vogdb Something partially related: The behavior to manipulate the the slider for Integer form fields is buggy. (You can easily reproduce by setting the focus on the slider and press left / right keys)

**Comment by njam** [comment]
@vogdb can you review and let me know if I should have a look at something too?

**Comment by vogdb** [comment]
@njam ok.
@christopheschwyzer Should I fix this behavior here?

**Comment by christopheschwyzer** [comment]
@vogdb as you wish.

**Comment by vogdb** [comment]
I haven't reviewed the code yet.
- File upload does not work on mobile.
- FancySelect in SK_Component_Share does not work. Try visibility of Blogpost or Video.
- FancySelect in SK_Form_SearchProfile does not work. Try age. I would reverify all the usages of FancySelect.
- Margin between Gender field and other fields.
screen shot 2015-08-21 at 11 34 05

**Comment by christopheschwyzer** [comment]
@vogdb lgty?

**Comment by vogdb** [comment]
Yep, looks ok. It just seems very strange to me that you want to merge with an iOS problem even I've prepared a patch for it which you have reverted >_<.

**Pull request merged**
