### PR TITLE
Breaking: Switch from phpredis client to predis

### PR DESCRIPTION
**Pull request by zazabe**
To avoid having more problems with https://github.com/phpredis/phpredis, we decided to switch to an alternative Redis client, https://github.com/nrk/predis.

The task is related to https://github.com/cargomedia/cm/issues/1920.

Note: the merge request is marked as "Breaking" even if our Redis client API has not changed, but we may have some issues because all cases are probably not well tested.

### CODE REVIEW

**Comment by zazabe** [comment]
@tomaszdurka please review

**Comment by zazabe** [comment]
@njam I changed the `read_write_timeout` connection parameter because an exception was raised after 1min, I tried to set it to `-1` to disable the timeout, then I subscribed to an idle channel during more than 15min without having this problem again.
Could you review my changes?

**Comment by njam** [comment]
- sFlush: `sMembers()` call should also be within `multi`/`exec` for it to be atomic, and use `DEL`
- subscribe: Add comment for `@param` about "Return something else than `null` to exit"

**Comment by zazabe** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
