### PR TITLE
Introduce QUnit js test framework

### PR DESCRIPTION
**Pull request by zazabe**
Introduce JS unit test with QUnit on CM

usage descibed in https://github.com/zazabe/cm/blob/js-unit-test/tests/client/README.md

### CODE REVIEW

**Comment by zazabe** [comment]
@vogdb please review

Note: the `promiseThrottler` test reproduce the #2134 issue

**Comment by vogdb** [comment]
lgtm

**Comment by vogdb** [comment]
well, one note here

**Comment by vogdb** [comment]
In `QUnit.test("cancel leading"` should be:
```js
      assert.deepEqual(check, ['call:foo', 'finally:foo', 'call:bar', 'resolve:bar', 'finally:bar']);
```
and not
```js
      assert.deepEqual(check, ['call:foo', 'finally:foo', 'call:foo', 'resolve:bar', 'finally:bar']);
```

**Comment by zazabe** [comment]
@vogdb please review

💝 > https://travis-ci.org/cargomedia/cm/jobs/127206070#L1321 ;)

**Comment by zazabe** [comment]
- not sure if it's a good idea to have `bin/qunit`, could we have some troubles with composer?
- require https://github.com/cargomedia/puppet-packages/issues/1297 to run tests inside the box

**Comment by vogdb** [comment]
ok. lgtm

**Comment by zazabe** [comment]
OK, works in the box now:
```
vagrant@www:~/cm$ ./bin/qunit

> promise-utils/promise-throttler
cancel trailing: ✔
cancel leading: ✔
cancel queue: ✔

Took 458ms to run 3 tests. 3 passed, 0 failed.
```

@vogdb @tomaszdurka what do you think about having `bin/qunit`? is it a problem for composer?

**Comment by vogdb** [comment]
I can't say anything about `bin/qunit` + composer :(

**Comment by njam** [comment]
Afaik it's ok - composer honours additional files in its "bin" dir (doesn't modify/delete them).

**Pull request merged**
