### PR TITLE
Store media channel thumbnails in separate table

### PR DESCRIPTION
**Pull request by alexispeter**
Remove `thumbnailCount` in favor of a table containing thumbnails. Each thumbnail references streamChannel or streamChannelArchive (same ID).

`CM_MediaStreams_Cli::importVideoThumbnail()` should expect the `createStamp`.

Table name: `cm_streamChannel_mediaThumbnail`?

Also let's drop `thumbnailCount` and `data`.

cc @tomaszdurka @fvovan

### CODE REVIEW

**Comment by alexispeter** [comment]
please review @tomaszdurka

**Comment by njam** [comment]
Tomasz is busy. lvgtm!

Let's wait for https://github.com/cargomedia/cm-janus/issues/170 with merging.

**Comment by njam** [comment]
We added an intermediary dummy argument in https://github.com/cargomedia/cm/pull/2070

So this is good to merge.

**Comment by alexispeter** [comment]
tagged https://github.com/cargomedia/cm/releases/tag/1.166.1

**Pull request merged**
