### PR TITLE
JS error handling when Internet down

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by njam** [comment]
How about "No Internet connection"?
Should be added to translations!

**Comment by vogdb** [comment]
Do I need to add it to `de.php` ?

**Comment by njam** [comment]
Yes! "Keine Internetverbindung"

Btw you can pass only 1 value to `setTranslation()`, and it will be used for "phrase" and "value":
`setTranslation('foo')` instead of `setTranslation('foo', 'foo')`
Maybe you can change it for the whole file so it's clear?

**Comment by njam** [comment]
lgtm

**Pull request merged**
