### PR TITLE
In cm.factory.create, check the instance type instead of a cid property

### PR DESCRIPTION
**Pull request by vogdb**
In https://github.com/cargomedia/cm/blob/master/library/CM/App.js#L292, it's not so clear what is this `data.cid`. 
I think it would be better to explicitly check if `data` in not an instance of `Backbone.Model` or `Backbone.Collection`, wdyt @vogdb?

### CODE REVIEW

**Comment by vogdb** [comment]
As always took some time to test it. @zazabe please review

**Comment by zazabe** [comment]
maybe having `return isClass && !isBackbone;` will be a bit more nice...

**Comment by vogdb** [comment]
Ok :( `instanceof` is a heavy operation

**Comment by vogdb** [comment]
@zazabe please look

**Comment by zazabe** [comment]
ok, didn't thought about the perf, but you think it could have some impact?

**Comment by vogdb** [comment]
well, I just have this habit from old times. Lets yearn for readability!

**Comment by vogdb** [comment]
@zazabe good to merge?

**Comment by zazabe** [comment]
yes!

**Pull request merged**
