### PR TITLE
Introduce RootProxy response to serve layout resource files from root dir

### PR DESCRIPTION
**Pull request by njam**
Some resource files need to be served from the root directory of the web site.
E.g. a service worker should be served at `/service-worker.js`.

I'm introducing a "root proxy" response which can serve any resource files off the
root directory, by escaping `/` with `--` in the URL.

This replaces #1715

For example we can then use this URL:
```
https://www.denkmal.dev/resource-layout--de--35--1428164686--manifest.json
```

### CODE REVIEW

**Comment by njam** [comment]
@vogdb @tomaszdurka please review

**Comment by vogdb** [comment]
lgtm

**Comment by vogdb** [comment]
btw front-end is lgtm. Didn't dig deep into back-end.

**Comment by tomaszdurka** [comment]
Woah, was not suspecting that some files really need to be served from root.
This manifest.json seems really problematic.

**Comment by njam** [comment]
The manifest.json doesn't need to be on root, but a JS service worker has to!
@tomaszdurka agree on these changes?

**Comment by tomaszdurka** [comment]
Well, I guess we have no choice! 
Looks ok.

**Comment by njam** [comment]
:)

**Pull request merged**
