### PR TITLE
Fix issue when the redis client is used within the subscribe closure

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@njam please review

**Comment by njam** [comment]
- _defineConnection: I would suggest that this function returns an array, so it doesn't have "side effects", and the control flow is simpler
 - Call it `parseConfig`
 - Rename instance variable to `_config?

**Comment by zazabe** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
