### PR TITLE
Introduce CM_Iterator_Transform / CM_Iterator_Permissive

### PR DESCRIPTION
**Pull request by zazabe**
Inspired by @tomaszdurka work :)

### CODE REVIEW

**Comment by zazabe** [comment]
@tomaszdurka please review

**Comment by njam** [comment]
Is this to have a *lazy* map function?

Could this also be written with *generators*?
```php
/**
 * @param array|Iterator $collection
 * @param callable       $function
 * @return Iterator
 */
function map($collection, callable $function) {
    foreach ($collection as $element) {
        yield $function($element);
    }
}
```
(via http://stackoverflow.com/questions/6566129/php-lazy-array-mapping/32099190#32099190)

**Comment by zazabe** [comment]
@njam yes, something like that, but in a generic iterator that wrap the iteration logic, looks a bit more OOP I guess, not sure if it's worth it...
Wondering how we could achieve the same thing with `yield`, 
- does it mean we should we have something like `CM_Utils:transform(...)` / `CM_Utils:permissive(...)`?
- or simply using `yield` specifically every time we want to map an array with some classes, with some extra logic if necessary (like for this "permissive" stuff).

**Comment by njam** [comment]
How to proceed here?

**Comment by zazabe** [comment]
Not sure if it's really needed, solved with `yield` in https://github.com/cargomedia/cm/pull/2477/files#diff-cf4749258410d777ac80766d5d8808c7R37, I would suggest to close it..

**Comment by njam** [comment]
👍

**Pull request closed without merging**
