### PR TITLE
Add CM_Janus_StreamChannelInterface

### PR DESCRIPTION
**Pull request by fvovan**
For https://github.com/cargomedia/sk/pull/3215

### CODE REVIEW

**Comment by fvovan** [comment]
@njam please reivew

**Comment by njam** [comment]
Shouldn't this be `findServerByChannelDefinition`, and fail if we don't find it? Then we don't need to check in the usage?

**Comment by fvovan** [comment]
>Shouldn't this be `findServerByChannelDefinition`

May be, I just wanted to keep signatures consistent.
i.e. `findServerByPlugin` may return `null` , so `findServerByChannelDefinition()` behaves the same.

**Comment by njam** [comment]
True, but there's also `getServerRandom()`. In this case I think failing is more useful?

The convention is that `get` should always return something (fail otherwise), and `find` can return `null`. So let's call it `get`.

otherwise lgtm

**Pull request merged**
