### PR TITLE
Remove publish dependency from media archive

### PR DESCRIPTION
**Pull request by tomaszdurka**
Hash content depends on publish existence.
```
    /**
     * @return string
     */
    public function getHash() {
        if ($this->hasStreamPublish()) {
            return md5($this->getStreamPublish()->getKey());
        }
        return md5($this->getKey());
    }
``

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@alexispeter please review

**Comment by alexispeter** [comment]
toArray() should probably not include the user anymore.

**Comment by alexispeter** [comment]
Hash issue fixed in #2062

**Comment by njam** [comment]
@alexispeter could you take over here?

Also related: https://github.com/cargomedia/cm/issues/2061

**Pull request closed without merging**
