### PR TITLE
Ignore archive-not-found with no stream channels

### PR DESCRIPTION
**Pull request by tomaszdurka**
Addressing https://github.com/cargomedia/sk/issues/3097

### CODE REVIEW

**Comment by tomaszdurka** [comment]
Paired with @fvovan

**Comment by njam** [comment]
- Remove `writeln`, we can handle this in `logException`
- How about change "Archive not created yet" to "Archive not created, please try again later".

then let's release it

**Comment by tomaszdurka** [comment]
@fvovan please review

**Comment by fvovan** [comment]
lgtm

**Pull request merged**
