### PR TITLE
Allow disabled attribute for button_link

### PR DESCRIPTION
**Pull request by christopheschwyzer**

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@tomaszdurka please review
@njam fyi

**Comment by njam** [comment]
I was just discussing with Michel a way to expose possible viewSession transitions to the client. I think this "disabled" on the server side will then not be needed anymore.
See https://github.com/cargomedia/sk/issues/3344

**Comment by christopheschwyzer** [comment]
Not sure I understand. I've planned to use disabled buttons in https://github.com/cargomedia/sk/pull/3325. This might be good to have anyways?

**Comment by njam** [comment]
I think it will not be needed in https://github.com/cargomedia/sk/pull/3325, if we make it more dynamic (change it with JS).
In general this parameter for `{button_link` is a bit strange, because it only applies to the `<button>`-case. Therefore I think it might be best to *not* do add it?

**Pull request closed without merging**
