### PR TITLE
Add iframe ad provider

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@fauvel please review

**Comment by fauvel** [comment]
There's [no browser support](http://caniuse.com/#search=seamless) for seamless iframes, the attribute [has been removed](http://www.w3schools.com/tags/att_iframe_seamless.asp) from html5. The rest lgtm!

**Comment by njam** [comment]
oh! please double check!

**Comment by fauvel** [comment]
lgtm

**Pull request merged**
