### PR TITLE
Add expirationStamp to "cm_ipBlocked"

### PR DESCRIPTION
**Pull request by mariansollmann**

### CODE REVIEW

**Comment by mariansollmann** [comment]
@alexispeter please review.

**Comment by mariansollmann** [comment]
@alexispeter please review.

**Comment by alexispeter** [comment]
What is the `if ($row['expirationStamp'] == 0) {` clause for in the update-script? You're only fetching rows with expirationStamp = 0 anyway.

**Comment by mariansollmann** [comment]
right :-) double secure. I will remove this

**Comment by mariansollmann** [comment]
@alexispeter please review.

**Comment by alexispeter** [comment]
Sorry I didn't mention this earlier, but you could simply do one "UPDATE foo SET expirationStamp = createStamp + `<maxAge>` WHERE expirationStamp = 0" instead of one query per row.

**Comment by mariansollmann** [comment]
@alexispeter right, thx. please review.

**Comment by alexispeter** [comment]
lgtm

**Pull request merged**
