### PR TITLE
CM_StreamChannel_Media invalidate key-cache on create

### PR DESCRIPTION
**Pull request by alexispeter**
Needs to invalidate cache on Create like parent class does. Probably was forgotten during refactoring.

please review @tomaszdurka

### CODE REVIEW

**Comment by alexispeter** [comment]
please review @tomaszdurka

**Comment by tomaszdurka** [comment]
Hmmm ok, but why it needs to be invalidated on creation? :o

**Comment by alexispeter** [comment]
Because findByKeyAndAdapter() caches misses as well as hits, which can lead to problems with streamchannels that have some sort of repeating key.

**Comment by tomaszdurka** [comment]
Looks good.

**Pull request merged**
