### PR TITLE
Update jquery.noUiSlider.js from 5.0.0  to 7.0.9.

### PR DESCRIPTION
**Pull request by vogdb**
The child of #1476.

### CODE REVIEW

**Comment by vogdb** [comment]
@christopheschwyzer please review.

**Comment by christopheschwyzer** [comment]
This should be tested on various devices. I will do it next Tuesday when I'm back in the office - or somebody else needs to take over.

**Comment by vogdb** [comment]
I think @NicolasSchmutz will be able to test it on all devices!

**Comment by NicolasSchmutz** [comment]
@vogdb I've tested it and it works very good with all devices.
Only one thing: The slider should be disabled if the location field is empty.
Like here: https://www.fuckbook.com/users/search

**Comment by vogdb** [comment]
perfect!

**Comment by vogdb** [comment]
Your notice made me to find a bug in CM_Field_Distance. It's kind of private. So, see an email from me.

**Comment by vogdb** [comment]
Ah. It's not a bug. I understood it incorrectly!

**Comment by NicolasSchmutz** [comment]
@vogdb deactivation of the slider (while the location field is empty or a country is selected) works perfect with all devices!
The dropdown of the location field is a bit faulty/slow with some devices - but thats another problem.

So this is good to go!

**Pull request merged**
