### PR TITLE
Make internals.js more readable

### PR DESCRIPTION
**Pull request by alexispeter**
Each entry should go on a separate line, to make it easier to spot differences.

### CODE REVIEW

**Comment by alexispeter** [comment]
please review @tomaszdurka

**Comment by tomaszdurka** [comment]
Can you tell me what is difference between `jsonEncode` and `encode`. I understand these are scalar values and there should be no real difference, right?

**Comment by alexispeter** [comment]
The difference is that jsonEncode() supports pretty-printing, i.e. each value on a separate line.

**Comment by tomaszdurka** [comment]
Ok then lgtm.

**Pull request merged**
