### PR TITLE
Add user agent getter

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by fauvel** [comment]
@dlondero please review

**Comment by dlondero** [comment]
@fauvel adding a test?

**Comment by fauvel** [comment]
Sure, please review!

**Comment by dlondero** [comment]
@fauvel lgtm

**Comment by njam** [comment]
What's the reasoning to return empty string if the header is missing - shouldn't this return `null`?

**Comment by fauvel** [comment]
Loosing information to hide complexity – a missing and a empty header should probably be handled the same in our application code, I think.

**Pull request merged**
