### PR TITLE
Breaking: Upgrade autosize plugin to version 3.

### PR DESCRIPTION
**Pull request by vogdb**
The child of #1725 and #1739.

### CODE REVIEW

**Comment by njam** [comment]
@vogdb I guess you didn't want to close this?

**Comment by vogdb** [comment]
Oops. I didn't. Thanks for reminding.

**Comment by NicolasSchmutz** [comment]
@vogdb please merge upstream

**Comment by njam** [comment]
Closing in favor of Closing in favor of https://github.com/cargomedia/cm/pull/1890

**Pull request closed without merging**
