### PR TITLE
Create CM_FormField_Search.

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@christopheschwyzer please advice. In `CM/layout/default/css/01-normalize.less` we have these rules:
```less
input[type="search"] {
  -webkit-appearance: textfield; /* 1 */
  -moz-box-sizing: content-box;
  -webkit-box-sizing: content-box; /* 2 */
  box-sizing: content-box;
}
```
This `box-sizing: content-box;` breaks our layout.

**Comment by christopheschwyzer** [comment]
As discussed: I agree with @vogdb that overwriting in `CM_FormField_Search` is the least :imp:

**Comment by vogdb** [comment]
@christopheschwyzer please review the front-end part.
@alexispeter please review the back-end part.

**Comment by christopheschwyzer** [comment]
Lgtm. Maybe add a test?

**Comment by vogdb** [comment]
It does not add any new behavior and does not have any specific validation. As I can see from the existing implementation such fields do not have tests. For example, CM_FormField_Money or CM_FormField_Password. They do not have tests.

**Comment by christopheschwyzer** [comment]
Fair enough.

**Comment by vogdb** [comment]
Ok. We're waiting for @alexispeter then.

**Comment by alexispeter** [comment]
Looks good from what I can tell.

**Pull request merged**
