### PR TITLE
Fix tracking queue names

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by fauvel** [comment]
@njam please review

**Comment by njam** [comment]
We checked it together - queue names are mixed up:
```
redis 127.0.0.1:6379> keys *
12) "Queue.CM_Service_Tracking_QueueTrait::_getTrackingQueue:12741592"
13) "Queue.CM_Service_Tracking_QueueTrait::_getTrackingQueue:15184246"
14) "Queue.CM_Service_Tracking_QueueTrait::_getTrackingQueue:13855460"
15) "Queue.CMService_GoogleAnalytics_Client::_getTrackingQueue:15202284"
16) "Queue.CMService_GoogleAnalytics_Client::_getTrackingQueue:15200288"
```

cc @dlondero

**Comment by fauvel** [comment]
@dlondero please review

**Comment by njam** [comment]
lgtm

**Comment by fauvel** [comment]
Looks like a php bug... reproduced in php 7.0.4:
```bash
php -a
Interactive shell

php > trait t { function t() { echo __METHOD__; } } class a { use t; } (new a)->t();
t::t
```

**Pull request merged**
