### PR TITLE
Only enable split tests for new users

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by fauvel** [comment]
@njam please review

**Comment by njam** [comment]
- CM/Model/Splittest.php::_getVariationFixture: Shouldn't the skipping logic rather to `_isVariationFixture`, then we don't have to return empty string. 
 - Maybe also move this logic to `CM_Model_Splittest_RequestClient` and `CM_Model_Splittest_User` so we don't need the `switch`?

**Comment by fauvel** [comment]
> CM/Model/Splittest.php::_getVariationFixture: Shouldn't the skipping logic rather to `_isVariationFixture`, then we don't have to return empty string. 

I think it's better for unit testing / mocking if we have it in `_getVariationFixture`. But I could returning `null` for instance. Wdyt?

**Comment by njam** [comment]
But the public API only exposes the `is*` functions (as we don't wanna allow to retrieve the actual variation).
Why is it better to put it into `get*` for testing? We could still mock either `_isVariationFixture()` or even `_getVariationFixture()` when testing the public interface `isVariationFixture`?

**Comment by fauvel** [comment]
I agree it looks cleaner like this... It is a bit strange that we have model fields in `CM_Model_Splittest` that are only used in its implementations, but ok.

**Comment by fauvel** [comment]
@njam please review!

**Comment by njam** [comment]
lgtm

**Comment by fauvel** [comment]
Tagged 1.114.2

**Pull request merged**
