### PR TITLE
Update Icons

### PR DESCRIPTION
**Pull request by christopheschwyzer**
added _birthday_, _chat_flash_, _facebook_, _profile-edit_, _text_

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Comment by christopheschwyzer** [comment]
We will update _coin_ icon as well

**Comment by christopheschwyzer** [comment]
@njam please review ;)

**Comment by njam** [comment]
lgtm

**Pull request merged**
