### PR TITLE
Update aws/aws-sdk-php to >=2.7.17

### PR DESCRIPTION
**Pull request by ppp0**
Needed for https://github.com/cargomedia/s3export_backup/issues/11 (method implemented there)

### CODE REVIEW

**Comment by ppp0** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Maybe rather use `"~2.7"` semantically correct versioning.

**Comment by tomaszdurka** [comment]
Otherwise looks good.

**Comment by tomaszdurka** [comment]
Looks good

**Pull request merged**
